const proof = (file, marker) => ({ file, marker });

export const ENFORCEMENT_PROOFS = {
  global: proof('tests/contract/skill-agents-contract.test.mjs', 'global AGENTS rule preserves current-state documentation and core routing'),
  clarification: proof('tests/state/state-machine.test.mjs', 'material uncertainty enters a non-mutating clarification hold'),
  preflight: proof('tests/ship/preflight.test.mjs', 'Ship preflight rejects environment files'),
  implementation: proof('tests/build/build-loop.test.mjs', 'Build requires red, implementation, fresh verification, and review'),
  size: proof('tests/contract/source-tree.test.mjs', 'owned text sources stay below 700 lines'),
  skill_hygiene: proof('tests/contract/skill-hygiene.test.mjs', 'skill workflow hygiene fails on long entrypoint workflows'),
  plan: proof('tests/plan/plan-validator.test.mjs', 'validator rejects open domains, incomplete adversarial coverage'),
  support: proof('tests/continuity/support-observer.test.mjs', 'Codebase Memory structural receipts execute a bounded exact-project graph query'),
  route: proof('tests/routing/route.test.mjs', 'route matrix sends new, ambiguous, expanded, and material-risk work to Plan'),
  build: proof('tests/build/build-loop.test.mjs', 'failed verification returns to the same slice'),
  commit: proof('tests/ship/commit-message.test.mjs', 'commit-message policy rejects co-authors'),
  docs: proof('tests/contract/readme.test.mjs', 'every README shell command is syntax-checked'),
  sentry: proof('tests/contract/sentry-routing.test.mjs', 'single native Sentry router covers every pinned upstream entrypoint'),
  discovery: proof('tests/contract/codex-skill-discovery.test.mjs', 'clean Codex app-server discovers every native user skill'),
  native_skills: proof('tests/contract/native-skills.test.mjs', 'canonical native skill root is complete and plugin-free'),
};

function row(line, owners, proofId, {
  disposition = 'retained-strengthened',
  guard = 'deterministic',
  context = 'global-rule',
} = {}) {
  return {
    id: `E${String(line).padStart(2, '0')}`,
    source: `59014f3:AGENTS.md:${line}`,
    source_line: line,
    owners,
    proof: proofId,
    disposition,
    guard,
    context,
  };
}

export const ENFORCEMENT_PARITY = [
  row(4, ['AGENTS.md', 'runtime/lib/state-machine.mjs', 'runtime/lib/setup-transaction.mjs'], 'clarification'),
  row(5, ['AGENTS.md', 'runtime/lib/ship-preflight.mjs'], 'preflight'),
  row(6, ['AGENTS.md', 'runtime/lib/ship-preflight.mjs'], 'preflight'),
  row(7, ['AGENTS.md', 'runtime/lib/change-contract.mjs'], 'implementation'),
  row(8, ['AGENTS.md', 'skills/hard-eng/references/plan.md', 'skills/hard-eng/references/build.md'], 'plan', { guard: 'semantic-plus-deterministic' }),
  row(9, ['AGENTS.md', 'tests/contract/source-tree.test.mjs'], 'size'),
  row(10, ['AGENTS.md', 'tests/contract/skill-hygiene.test.mjs'], 'skill_hygiene'),
  row(11, ['AGENTS.md', 'skills/atomic-ui/SKILL.md', 'DESIGN.md'], 'plan', { guard: 'semantic-plus-deterministic' }),
  row(12, ['AGENTS.md', 'PRODUCT.md', 'DESIGN.md'], 'docs', { guard: 'semantic-plus-deterministic' }),
  row(15, ['AGENTS.md'], 'global', { guard: 'semantic-plus-deterministic' }),
  row(16, ['AGENTS.md', 'runtime/lib/change-contract.mjs'], 'implementation'),
  row(17, ['AGENTS.md', 'runtime/lib/check-registry.mjs'], 'build'),
  row(18, ['AGENTS.md', 'runtime/lib/commit-message.mjs'], 'commit'),
  row(19, ['AGENTS.md'], 'global', { guard: 'semantic-release-dogfood' }),
  row(22, ['AGENTS.md', 'skills/codebase-memory/SKILL.md'], 'support'),
  row(23, ['AGENTS.md', 'skills/codebase-memory/SKILL.md', 'runtime/lib/support-observer.mjs'], 'support'),
  row(24, ['AGENTS.md'], 'global', { guard: 'semantic-plus-deterministic' }),
  row(25, ['AGENTS.md'], 'global'),
  row(26, ['AGENTS.md'], 'native_skills'),
  row(29, ['AGENTS.md'], 'global', { guard: 'semantic-plus-deterministic' }),
  row(30, ['AGENTS.md'], 'global', { guard: 'semantic-plus-deterministic' }),
  row(31, ['AGENTS.md'], 'global', { guard: 'semantic-plus-deterministic' }),
  row(32, ['AGENTS.md', 'skills/hard-eng/references/build.md', 'runtime/lib/change-contract.mjs'], 'implementation'),
  row(35, ['AGENTS.md'], 'native_skills', { context: 'on-demand-skill' }),
  row(36, ['AGENTS.md', 'skills/building-flutter-apps/SKILL.md'], 'native_skills', { context: 'on-demand-skill' }),
  row(37, ['AGENTS.md', 'skills/appwrite-backend/SKILL.md'], 'native_skills', { context: 'on-demand-skill' }),
  row(38, ['AGENTS.md', 'skills/research/SKILL.md'], 'native_skills', { context: 'on-demand-skill' }),
  row(39, ['AGENTS.md', 'skills/repeated-failure-learning/SKILL.md', 'skills/writing-great-skills/SKILL.md', 'skills/find-skills/SKILL.md'], 'native_skills', { context: 'on-demand-skill' }),
  row(40, ['AGENTS.md', 'skills/hard-eng/references/route.md'], 'route', { disposition: 'consolidated', context: 'on-demand-skill' }),
  row(41, ['AGENTS.md', 'skills/hard-eng/references/route.md'], 'route', { disposition: 'consolidated', context: 'on-demand-skill' }),
  row(42, ['AGENTS.md', 'skills/hard-eng/SKILL.md'], 'route', { disposition: 'consolidated', context: 'on-demand-skill' }),
  row(43, ['AGENTS.md', 'skills/diagnosing-bugs/SKILL.md'], 'native_skills', { context: 'on-demand-skill' }),
  row(44, ['AGENTS.md', 'skills/codebase-design/SKILL.md'], 'implementation', { context: 'on-demand-skill' }),
  row(45, ['skills/hard-eng/references/plan.md', 'runtime/lib/plan.mjs'], 'plan', { disposition: 'consolidated', context: 'on-demand-skill' }),
  row(46, ['AGENTS.md', 'skills/react-doctor/SKILL.md', 'skills/fallow/SKILL.md', 'skills/vercel-react-best-practices/SKILL.md'], 'native_skills', { context: 'on-demand-skill' }),
  row(47, ['AGENTS.md', 'skills/test-quality/SKILL.md'], 'build', { context: 'on-demand-skill' }),
  row(48, ['AGENTS.md', 'skills/atomic-ui/SKILL.md', 'skills/hard-eng/references/plan.md'], 'plan', { disposition: 'retired-approved', context: 'on-demand-skill' }),
  row(49, ['AGENTS.md', 'skills/sentry-workflow/SKILL.md'], 'sentry', { context: 'on-demand-skill' }),
  row(50, ['AGENTS.md', 'skills/terse/SKILL.md'], 'native_skills', { context: 'on-demand-skill' }),
  row(53, ['AGENTS.md'], 'global', { guard: 'semantic-plus-deterministic' }),
  row(54, ['AGENTS.md'], 'global'),
  row(55, ['AGENTS.md', 'skills/hard-eng/references/route.md'], 'route', { disposition: 'consolidated' }),
  row(56, ['AGENTS.md', 'skills/test-quality/SKILL.md'], 'build'),
  row(57, ['AGENTS.md', 'tests/contract/skill-hygiene.test.mjs'], 'skill_hygiene'),
  row(58, ['AGENTS.md'], 'global', { guard: 'semantic-plus-deterministic' }),
  row(59, ['AGENTS.md'], 'global', { guard: 'semantic-plus-deterministic' }),
  row(60, ['AGENTS.md'], 'global', { guard: 'semantic-plus-deterministic' }),
  row(61, ['AGENTS.md', 'runtime/lib/change-contract.mjs'], 'implementation', { guard: 'semantic-plus-deterministic' }),
  row(62, ['AGENTS.md'], 'global', { guard: 'semantic-plus-deterministic' }),
];
