const proof = (file, marker) => ({ file, marker });
const row = (number, owners, proofs, release_gate = 'none') => ({
  id: `R${String(number).padStart(2, '0')}`,
  owners,
  proofs,
  release_gate,
});

export const REQUIREMENT_PROOFS = [
  row(1, ['skills/hard-eng/SKILL.md'], [proof('tests/contract/codex-skill-discovery.test.mjs', 'clean Codex app-server discovers every native user skill')]),
  row(2, ['runtime/lib/route.mjs'], [proof('tests/routing/route.test.mjs', 'route matrix sends new, ambiguous, expanded, and material-risk work to Plan')]),
  row(3, ['runtime/lib/route.mjs', 'runtime/lib/state-build.mjs'], [proof('tests/routing/route.test.mjs', 'small clear fixes, read-only work, and mechanical edits stay Direct')]),
  row(4, ['skills/hard-eng/references/plan.md'], [proof('tests/plan/plan-validator.test.mjs', 'validator rejects open domains, incomplete adversarial coverage')]),
  row(5, ['skills/hard-eng/references/plan.md'], [proof('tests/contract/skill-agents-contract.test.mjs', 'Hard Eng preserves the complete Plan, Build loop, Ship, and conditional Learn contract')]),
  row(6, ['runtime/lib/plan.mjs'], [proof('tests/contract/source-tree.test.mjs', 'one repository-root plan remains the feature SSOT')]),
  row(7, ['runtime/lib/ui-decision.mjs'], [proof('tests/plan/plan-validator.test.mjs', 'UI plan verifies a run-owned coded prototype and realistic edge states')]),
  row(8, ['skills/atomic-ui/SKILL.md', 'runtime/lib/ui-decision.mjs'], [proof('tests/plan/plan-validator.test.mjs', 'existing UI baseline proves reproducible scenario metadata')]),
  row(9, ['runtime/lib/ui-decision.mjs'], [proof('tests/plan/plan-validator.test.mjs', 'UI plan verifies a run-owned coded prototype and realistic edge states')]),
  row(10, ['runtime/lib/ui-decision.mjs'], [proof('tests/plan/plan-validator.test.mjs', 'Imagegen exploration requires explicit budget')]),
  row(11, ['runtime/lib/state-build.mjs'], [proof('tests/build/build-loop.test.mjs', 'Build requires red, implementation, fresh verification, and review')]),
  row(12, ['skills/e2e/SKILL.md', 'runtime/lib/evidence.mjs'], [proof('tests/ui/visual-evidence.test.mjs', 'visual evidence proves comparable baseline, final screenshots, and required video')]),
  row(13, ['runtime/lib/check-registry.mjs', 'runtime/lib/ship-preflight.mjs'], [proof('tests/ship/check-registry.test.mjs', 'ordinary registry refuses model, daemon, legacy')]),
  row(14, ['runtime/lib/findings.mjs'], [proof('tests/learn/learn-loop.test.mjs', 'Learn requires admitted provenance and fail-before/pass-after guard proof')]),
  row(15, ['runtime/lib/state-machine.mjs'], [proof('tests/state/state-machine.test.mjs', 'Build enforces red, implement, verify, review, and Ship order')]),
  row(16, ['runtime/lib/store.mjs', 'runtime/lib/capsule.mjs'], [proof('tests/continuity/mcp-continuity.test.mjs', 'typed mutation replay advances revision once')]),
  row(17, ['runtime/server.mjs'], [proof('tests/continuity/mcp-continuity.test.mjs', 'start binds exact task, replay is idempotent, and unrelated tasks see only unbound')]),
  row(18, ['runtime/lib/store.mjs', 'runtime/lib/worktree.mjs'], [proof('tests/continuity/mcp-continuity.test.mjs', 'same Git-common family resumes explicitly across a native worktree')]),
  row(19, ['runtime/lib/worktree.mjs'], [proof('tests/worktree/worktree-doctor.test.mjs', 'worktree doctor validates exact ignored inputs while Codex owns the copy')]),
  row(20, ['runtime/lib/release-eval.mjs', 'runtime/lib/capsule.mjs'], [proof('tests/ship/release-eval.test.mjs', 'release eval previews exact models, purpose, cases, call count, and cap')], 'explicit-model-quota-approval'),
  row(21, ['runtime/lib/release-eval.mjs', 'runtime/lib/check-registry.mjs'], [proof('tests/ship/release-eval.test.mjs', 'stops on first failure and never retries or exceeds the approved cap')]),
  row(22, ['runtime/lib/findings.mjs', 'skills/repeated-failure-learning/SKILL.md'], [proof('tests/learn/learn-loop.test.mjs', 'Learn requires admitted provenance and fail-before/pass-after guard proof')]),
  row(23, ['runtime/lib/worktree.mjs', 'runtime/lib/skill-parity.mjs'], [proof('tests/contract/removed-surfaces.test.mjs', 'retired dependency, foreign-harness, plugin, and old-eval paths remain absent')]),
  row(24, ['skills/atomic-ui/SKILL.md', 'runtime/lib/skill-parity.mjs'], [proof('tests/contract/skill-parity.test.mjs', 'only approved Impeccable and Treehouse entrypoints retire')]),
  row(25, ['runtime/lib/check-registry.mjs', 'runtime/lib/legacy-control-plane.mjs', 'runtime/lib/skill-parity.mjs'], [
    proof('tests/setup/legacy-control-plane.test.mjs', 'external no-mistakes is preserved'),
    proof('tests/contract/skill-parity.test.mjs', 'no-mistakes is consolidated'),
  ]),
  row(26, ['runtime/lib/approved-cutover-inventory.mjs', 'runtime/lib/enforcement-parity.mjs', 'runtime/lib/skill-parity.mjs'], [
    proof('tests/contract/cutover-inventory.test.mjs', 'approved destructive retirements are exact, parity-owned'),
    proof('tests/contract/skill-parity.test.mjs', 'every pre-migration native skill is classified exactly once with retained-resource proof'),
  ]),
  row(27, ['scripts/setup.mjs'], [proof('tests/setup/setup-modes.test.mjs', 'install is dry-run-first, approval-bound, idempotent, and hash-owned')]),
  row(28, ['AGENTS.md', 'runtime/lib/codex-wiring.mjs'], [proof('tests/contract/removed-surfaces.test.mjs', 'retired dependency, foreign-harness, plugin, and old-eval paths remain absent')]),
  row(29, ['runtime/lib/codex-cutover.mjs', 'runtime/lib/setup-state.mjs'], [
    proof('tests/contract/removed-surfaces.test.mjs', 'retired tool names are confined to exact migration evidence and negative guards'),
    proof('tests/setup/state-migration.test.mjs', 'canonical cutover receipt without a legacy schema field'),
  ]),
  row(30, ['tests'], [proof('tests/contract/removed-surfaces.test.mjs', 'retired dependency, foreign-harness, plugin, and old-eval paths remain absent')]),
  row(31, ['runtime/lib/publication-observer.mjs'], [proof('tests/ship/publication-observer.test.mjs', 'direct-main preparation binds current main and protection/rules restoration')]),
  row(32, ['README.md', 'assets/readme/hard-eng-hero.png'], [proof('tests/contract/readme.test.mjs', 'every README shell command is syntax-checked and exercised through a fixture')]),
  row(33, ['runtime/lib/setup-transaction.mjs', 'runtime/lib/codex-cutover.mjs'], [proof('tests/setup/codex-cutover.test.mjs', 'cutover preview and apply use official Codex commands and preserve unrelated state')]),
  row(34, ['AGENTS.md', 'runtime/lib/legacy-control-plane.mjs'], [proof('tests/setup/legacy-control-plane.test.mjs', 'external no-mistakes is preserved')]),
  row(35, ['skills/hard-eng/references/plan.md', 'runtime/lib/plan.mjs'], [proof('tests/plan/plan-validator.test.mjs', 'validator rejects open domains, incomplete adversarial coverage')]),
  row(36, ['runtime/lib/evidence.mjs', 'runtime/lib/state-build.mjs'], [proof('tests/ui/visual-evidence.test.mjs', 'Build blocks at a visual milestone and routes feedback to the right boundary')]),
  row(37, ['runtime/lib/support-observer.mjs', 'runtime/lib/setup-doctor.mjs'], [proof('tests/continuity/support-observer.test.mjs', 'Codebase Memory receipts are generated from exact runtime commands')]),
  row(38, ['AGENTS.md', 'runtime/lib/state-machine.mjs'], [proof('tests/state/state-machine.test.mjs', 'material uncertainty enters a non-mutating clarification hold')]),
  row(39, ['runtime/lib/enforcement-parity.mjs', 'runtime/lib/skill-parity.mjs'], [
    proof('tests/contract/enforcement-parity.test.mjs', 'every pre-migration AGENTS obligation has one active owner'),
    proof('tests/contract/skill-parity.test.mjs', 'every pre-migration native skill is classified exactly once with retained-resource proof'),
  ]),
  row(40, ['skills', 'vendor/skill-upstreams', 'runtime/lib/codex-wiring.mjs'], [proof('tests/contract/codex-skill-discovery.test.mjs', 'clean Codex app-server discovers every native user skill')]),
  row(41, ['AGENTS.md', 'runtime/lib/change-contract.mjs'], [proof('tests/build/build-loop.test.mjs', 'pass-through wrapper')]),
];
