#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  hasImplementationProofCommand,
  hasTestFirstProofCommand,
  matchesTestFirstProofGuardrail,
} from '../scripts/he-state-proof.mjs';
import { emptyRepo, proofOptions } from './helpers/he-proof-options.mjs';

for (const command of [
  'npm test || true',
  'npm test; true',
  'npm test | cat',
  'npm test && true || true',
  'npm test && false',
  'npm test && exit 1',
  'npm test && command false',
  'npm test && command exit 1',
  'npm test >/',
  'npm test </missing',
  'npm test &',
  'npm test & true',
  'npm(){ true; }; npm test',
  'npm() ( true ); npm test',
  'pytest() ( true ); pytest',
  'env() ( true ); env NODE_ENV=test npm test',
  'function npm { true; }; npm test',
  'npm()\n{ true; }\nnpm test',
  'npm()\n( true; )\nnpm test',
  'function npm\n{ true; }\nnpm test',
  'jest(){ true; }; jest',
  'function stryker { true; }; stryker run',
  'true() ( false ); true && npm test',
  'false() ( true ); false || npm test',
  'export PYTEST_ADDOPTS=--collect-only; unset() ( true ); unset PYTEST_ADDOPTS; pytest',
  'test -d . && exit 0; npm test',
  'export PYTEST_ADDOPTS=--collect-only || unset PYTEST_ADDOPTS; pytest',
  'set -a; PYTEST_ADDOPTS=--collect-only || unset PYTEST_ADDOPTS; pytest',
  'echo ok || npm test',
  'PATH=./fake-bin npm test',
  'env PATH=./fake-bin npm test',
  '"NODE_ENV=test" npm test',
  'export PATH=./fake-bin:$PATH; npm test',
  'export FOO=ok PATH=./fake-bin:$PATH; npm test',
  'set -e; false; npm test',
  'set -o errexit; false; npm test',
  'set -euo pipefail; false; npm test',
  'set -o pipefail; false | true && npm test',
  'set -eo pipefail; false | true && npm test',
  'npm --if-present test',
  'npm --workspaces --if-present test',
  'npm run test --if-present',
  'npm test -- --help',
  'jest "--passWithNoTests"',
  'jest --passWithNoTests',
  'jest $(printf %s --passWithNoTests)',
  'jest "$(printf %s --passWithNoTests)"',
  'jest `printf %s --passWithNoTests`',
  'jest "`printf %s --passWithNoTests`"',
  'jest --passWithNoTest?',
  'jest *',
  'jest {--passWithNoTests,owner}',
  'pytest {--collect-only,tests}',
  'cargo test "--no-run"',
  'mvn test -DskipTests',
  'mvn test -DskipTests=true',
  'mvn test -Dmaven.test.skip',
  'mvn test -Dmaven.test.skip=true',
  'mvn test -Dmaven.test.skip.exec=true',
  'mvn test -Dmaven.test.failure.ignore=true',
  'mvn test -Dtest=NoSuch -Dsurefire.failIfNoSpecifiedTests=false',
  'mvn -Dtest=NoSuch -Dsurefire.failIfNoSpecifiedTests=false test',
  'mvn test -fn',
  'mvn test --fail-never',
  'mvn -q -DskipTests test',
  'mvn -q -DskipTests=true test',
  './mvnw -q -DskipTests test',
  'mvn -q --help test',
  "jest $'--passWithNoTests'",
  "jest $'--passWithNo\\x54ests'",
  'jest $"--passWithNoTests"',
  "cargo test $'--no-run'",
  'pytest --collect-only',
  'mocha --dry-run',
  'node --test --help',
  'go test -list .',
  '{ false; } && npm test',
  '{ exit 0; }; npm test',
  'alias npm=true; npm test',
  'alias jest="jest --passWithNoTests"; jest',
  'alias env=true; env NODE_ENV=test npm test',
  'hash -p /bin/true npm; npm test',
  'hash npm=/bin/true; npm test',
  'eval "npm(){ true; }"; npm test',
  'source ./fake-runners.sh; npm test',
  '. ./fake-runners.sh; npm test',
  'builtin export PATH=./fake-bin:$PATH; npm test',
  'command export PATH=./fake-bin:$PATH; npm test',
  'builtin cd /tmp; npm test',
  'command cd /tmp; npm test',
  'builtin source ./fake-runners.sh; npm test',
  'command source ./fake-runners.sh; npm test',
  'export "PATH=./fake-bin:$PATH"; npm test',
  "export $'PATH=./fake-bin:$PATH'; npm test",
  "export $'P\\x41TH=./fake-bin:$PATH'; npm test",
  'export $"PATH=./fake-bin:$PATH"; npm test',
  'npm --prefix /tmp/fake test',
  'npm --prefix=/tmp/fake test',
  'npm --prefix ../other test',
  'npm --prefix web test',
  'npm --prefix=packages/web test',
  'npm --prefix . --workspace web test',
  'npm -w web test',
  'npm --workspace web test',
  'npm --workspace=web test',
  'npm --workspaces test',
  'npm test --workspaces=true',
  'npm --ws test',
  'npm test --ws=true',
  'npm --workspaces run test',
  'npm test --prefix /tmp/fake',
  'npm test --prefix=/tmp/fake',
  'npm test --prefix ../other',
  'npm test --prefix web',
  'npm test --prefix=packages/web',
  'npm --prefix web test --prefix /tmp/fake',
  'pnpm --dir ../other test',
  'pnpm --dir=../other test',
  'pnpm --dir packages/web test',
  'pnpm --dir . --filter web test',
  'pnpm --filter web test',
  'pnpm --filter=web test',
  'pnpm -r test',
  'pnpm --recursive test',
  'pnpm test --recursive=true',
  'pnpm -w test',
  'pnpm --workspace-root test',
  'pnpm test --workspace-root=true',
  'pnpm test --dir ../other',
  'pnpm test --dir=../other',
  'pnpm test --dir packages/web',
  'yarn --cwd /tmp/fake test',
  'yarn --cwd ./web test',
  'yarn --cwd . workspace web test',
  'yarn workspace web test',
  'yarn test --cwd /tmp/fake',
  'yarn test --cwd ./web',
  'cd /tmp/fake; npm test',
  'pushd web; npm test',
  'popd; npm test',
  'grep __missing__ /dev/null && npm test',
  '(false) && npm test',
  '(exit 0); npm test',
  "cat <<'#EOF'\nnpm test\n#EOF",
  'cat <<-EOF\nnpm test\nEOF',
  'echo <(true && npm test )',
  'echo >(true && npm test )',
  'echo =(true && npm test )',
  'typeset PATH=./fake-bin:$PATH; npm test',
  'declare -x PATH=./fake-bin:$PATH; npm test',
  'local PATH=./fake-bin:$PATH; npm test',
  'readonly PATH=./fake-bin:$PATH; npm test',
  "trap 'exit 0' ERR; npm test",
  "trap 'exit 0' EXIT; npm test",
  'cargo test --no-run',
  'MAKEFLAGS=-n make test',
  'MAKEFLAGS=-i make test',
  'MAKEFLAGS=--ignore-errors make test',
  'MFLAGS=-n make test',
  'MFLAGS=-i make test',
  'GNUMAKEFLAGS=-n make test',
  'GNUMAKEFLAGS=-i make test',
  'export MAKEFLAGS=-n; make test',
  'export MAKEFLAGS=-i; make test',
  'export GNUMAKEFLAGS=-n; make test',
  'export GNUMAKEFLAGS=-i; make test',
  'set -a; MFLAGS=-n; make test',
  'set -a; MFLAGS=-i; make test',
  'make test -n',
  'make test -i',
  'make test --just-print',
  'make test --ignore-errors',
  'make test MAKEFLAGS=-n',
  'make test MAKEFLAGS=-i',
  'make test MFLAGS=-n',
  'make test MFLAGS=-i',
  'make test GNUMAKEFLAGS=-n',
  'make test GNUMAKEFLAGS=-i',
  'make test SHELL=/usr/bin/true',
  'make SHELL=/usr/bin/true test',
  'make mutation --just-print',
  'make make-it-fail -q',
  'make make-it-fail --question',
  'make test -t',
  'make test --eval "test: ; @true"',
  'make test --eval=test:',
  'mvn test --no-test',
  'mvn -f /tmp/pom.xml test',
  'mvn -f=/tmp/pom.xml test',
  'mvn test -f /tmp/pom.xml',
  'mvn test -s /tmp/settings.xml',
  'mvn test --settings=/tmp/settings.xml',
  'mvn test -gs /tmp/settings.xml',
  'mvn test --global-settings=/tmp/settings.xml',
  'mvn test -t /tmp/toolchains.xml',
  'mvn test --toolchains=/tmp/toolchains.xml',
  './mvnw -f /tmp/pom.xml test',
  './mvnw test -DskipTests',
  'gradle test --no-execute',
  'gradle -p /tmp/fake test',
  'gradle -p=/tmp/fake test',
  'gradle --project-dir ../fake test',
  'gradle --project-dir=/tmp/fake test',
  'gradle -b /tmp/build.gradle test',
  'gradle test --init-script /tmp/skip.gradle',
  'gradle test --init-script=/tmp/skip.gradle',
  'gradle test -m',
  'gradle test --test-dry-run',
  'gradle --no-daemon test -m',
  'gradle test -p /tmp/fake',
  'gradle test --project-dir ../fake',
  'gradle test --project-dir=/tmp/fake',
  'gradle test -b /tmp/build.gradle',
  'gradle test -p app -p /tmp/fake',
  'gradle test -x test',
  'gradle test -x :test',
  'gradle :test -x :test',
  'gradle :app:test -x :app:test',
  'gradle --no-daemon test -x test',
  './gradlew test -m',
  './gradlew test -I /tmp/skip.gradle',
  './gradlew test -I/tmp/skip.gradle',
  './gradlew test --test-dry-run',
  './gradlew --no-daemon test -m',
  './gradlew test --exclude-task test',
  './gradlew test --exclude-task :test',
  './gradlew test --exclude-task=test',
  './gradlew test --exclude-task=:test',
  './gradlew --no-daemon test --exclude-task=test',
  'PYTEST_ADDOPTS=--collect-only pytest',
  'PYTEST_ADDOPTS=--collect- PYTEST_ADDOPTS+=only pytest',
  'PYTEST_ADDOPTS=--co pytest',
  'PYTEST_ADDOPTS=--co=tests pytest',
  'PYTEST_ADDOPTS=--help pytest',
  'PYTEST_ADDOPTS=--version pytest',
  'PYTEST_ADDOPTS=--fixtures pytest',
  'PYTEST_ADDOPTS=--markers pytest',
  'PYTEST_ADDOPTS=--setup-plan python -m pytest',
  'PYTEST_ADDOPTS=--setup-only pytest',
  'PYTEST_ADDOPTS="-c /tmp/pytest.ini" pytest',
  'PYTEST_ADDOPTS="--rootdir /tmp/tests" python -m pytest',
  'PYTEST_ADDOPTS="-c ../pytest.ini" pytest',
  'PYTEST_ADDOPTS="-q --help" pytest',
  'PYTEST_ADDOPTS="--collect-only -q" pytest',
  'PYTEST_ADDOPTS="--fixtures -q" pytest',
  'env PYTEST_ADDOPTS=--collect-only python -m pytest',
  'npm_config_if_present=true npm test',
  'npm_config_if_present=tr npm_config_if_present+=ue npm test',
  'NPM_CONFIG_IF_PRESENT=1 npm run test',
  'npm_config_ignore_scripts=tr npm_config_ignore_scripts+=ue npm test',
  'npm_config_ignore_scripts=true npm test',
  'npm_config_script_shell=/bin/true npm test',
  'NPM_CONFIG_SCRIPT_SHELL=/bin/true npm test',
  'env npm_config_script_shell=/bin/true npm test',
  'npm_config_prefix=/tmp/fake npm test',
  'npm_config_prefix=packages/app npm test',
  'npm_config_userconfig=/tmp/npmrc npm test',
  'npm_config_userconfig=.npmrc npm test',
  'npm_config_cache=/tmp/npm-cache npm test',
  'npm_config_cache=.npm-cache npm test',
  'npm_config_workspace=../fake npm test',
  'npm_config_workspace=packages/app npm test',
  'npm_config_workspaces=true npm test',
  'npm_config_ws=true npm test',
  'npm_config_filter=web npm test',
  'env npm_config_workspaces=true npm test',
  'export npm_config_workspaces=true; npm test',
  'export npm_config_filter=web; npm test',
  'set -k; npm test npm_config_workspaces=true',
  'env npm_config_prefix=/tmp/fake npm test',
  'export npm_config_prefix=packages/app; npm test',
  'export npm_config_userconfig=/tmp/npmrc; npm test',
  'npm_config_prefix=/tmp/fake export npm_config_prefix; npm test',
  'pnpm_config_dir=/tmp/fake pnpm test',
  'pnpm_config_dir=packages/app pnpm test',
  'pnpm_config_userconfig=../pnpmrc pnpm test',
  'pnpm_config_userconfig=.npmrc pnpm test',
  'pnpm_config_workspace=packages/app pnpm test',
  'pnpm_config_workspaces=true pnpm test',
  'pnpm_config_workspace_root=true pnpm test',
  'pnpm_config_ws=true pnpm test',
  'pnpm_config_filter=web pnpm test',
  'pnpm_config_recursive=true pnpm test',
  'env pnpm_config_filter=web pnpm test',
  'export pnpm_config_filter=web; pnpm test',
  'export pnpm_config_recursive=true; pnpm test',
  'set -k; pnpm test pnpm_config_filter=web',
  'yarn_config_cwd=/tmp/fake yarn test',
  'yarn_config_cwd=packages/app yarn test',
  'yarn_cache_folder=../cache yarn test',
  'yarn_cache_folder=.yarn/cache yarn test',
  'FLAG=--passWithNoTests jest $FLAG',
  'OPTS=--collect-only pytest $OPTS',
  'FLAG=--passWithNoTests jest ${FLAG}',
  'OPTS=--collect-only pytest "$OPTS"',
  'export PYTEST_ADDOPTS=--collect-only; pytest',
  'export PYTEST_ADDOPTS=--help; python -m pytest',
  'PYTEST_ADDOPTS=--collect-only export PYTEST_ADDOPTS; pytest',
  'PYTEST_ADDOPTS=--setup-plan export PYTEST_ADDOPTS; python -m pytest',
  'PYTEST_ADDOPTS=--collect-only; export PYTEST_ADDOPTS; pytest',
  'typeset -x PYTEST_ADDOPTS=--collect-only; pytest',
  'declare -x PYTEST_ADDOPTS=--help; pytest',
  'set -a; PYTEST_ADDOPTS=--collect-only; pytest',
  'set -o allexport; PYTEST_ADDOPTS=--collect-only; python -m pytest',
  'set -k; npm test npm_config_if_present=true',
  'set -o keyword; npm test npm_config_if_present=true',
  'set -k; pytest PYTEST_ADDOPTS=--collect-only',
  'set -o keyword; pytest PYTEST_ADDOPTS=--collect-only',
  "export PYTEST_ADDOPTS='--collect-only '; export PYTEST_ADDOPTS+=-q; pytest",
  'export npm_config_if_present=true; npm test',
  'export npm_config_ignore_scripts=true; npm test',
  'export npm_config_script_shell=/bin/true; npm test',
  'declare -x npm_config_script_shell=/bin/true; npm test',
  'npm_config_if_present=true export npm_config_if_present; npm test',
  'npm_config_ignore_scripts=true export npm_config_ignore_scripts; npm test',
  'npm_config_script_shell=/bin/true export npm_config_script_shell; npm test',
  'npm_config_if_present=true; export npm_config_if_present; npm test',
  'typeset -x npm_config_if_present=true; npm test',
  'declare -x npm_config_ignore_scripts=true; npm test',
  'set -a; npm_config_if_present=true; npm test',
  'set -o allexport; npm_config_ignore_scripts=true; npm test',
  'export npm_config_if_present=; export npm_config_if_present+=true; npm test',
  'make test -f /tmp/Makefile',
  'make test --file ../Makefile',
  'make test --makefile=/tmp/Makefile',
  'make test -f build/Makefile -f /tmp/Makefile',
  'make test -C /tmp/fake',
  'make -C /tmp/fake test',
  'make -f /tmp/Makefile test',
  'pytest --fixtures',
  'pytest --markers',
  'pytest --setup-only',
  'pytest --setup-plan',
  'pytest -c /tmp/pytest.ini',
  'pytest --rootdir /tmp/tests',
  'pytest --rootdir=../tests',
  'pytest /tmp/fake',
  'pytest ../fake',
  'pytest -o addopts=--collect-only',
  'pytest --override-ini addopts=--collect-only',
  'python -m pytest --setup-only',
  'python -m pytest --setup-plan',
  'python -m pytest -c /tmp/pytest.ini',
  'python -m pytest --fixtures-per-test',
  'python -m pytest /tmp/fake',
  'python -m pytest --override-ini addopts=--setup-plan',
  'jest -c=/tmp/jest.config.js',
  'jest --showConfig',
  'jest --clearCache',
  'jest --config /tmp/jest.config.js',
  'jest --config="{passWithNoTests:true}"',
  'jest --config=../jest.config.js',
  'jest --rootDir /tmp/fake',
  'jest --rootDir=../fake',
  'jest /tmp/fake.test.js',
  'jest ../fake.test.js',
  'yarn jest --showConfig',
  'npm run jest -- --clearCache',
  'yarn jest --config /tmp/jest.config.js',
  'yarn jest --rootDir /tmp/fake',
  'npm run jest -- --config /tmp/jest.config.js',
  'npm run jest -- --rootDir /tmp/fake',
  'npx jest --config /tmp/jest.config.js',
  'npx jest --rootDir /tmp/fake',
  'npm exec jest --config /tmp/jest.config.js',
  'npm exec jest --rootDir /tmp/fake',
  'vitest -r=/tmp/app',
  'vitest --config /tmp/vitest.config.ts',
  'vitest --root /tmp/app',
  'vitest /tmp/fake.test.ts',
  'vitest ../fake.test.ts',
  'yarn test --showConfig',
  'yarn test --config /tmp/jest.config.js',
  'yarn vitest --config /tmp/vitest.config.ts',
  'npm run vitest -- --config /tmp/vitest.config.ts',
  'npx vitest --config /tmp/vitest.config.ts',
  'npx jest --showConfig',
  'npm exec jest --clearCache',
  'go test -run=^$',
  'go test -run "^$"',
  'GOFLAGS=-run=^$ go test',
  'GOFLAGS="-run ^$" go test',
  'env GOFLAGS=-run=^$ go test',
  'export GOFLAGS=-run=^$; go test',
  'GOFLAGS=-run=^$ export GOFLAGS; go test',
  'set -a; GOFLAGS=-run=^$; go test',
  'go test -skip=.',
  'go test -skip .',
  'go test -skip=^',
  'go test -skip /^/',
  'go test -skip=$',
  'go test -skip /$/',
  'go test -count=0',
  'go test -count 0',
  'GOFLAGS=-skip=. go test',
  'GOFLAGS="-skip ." go test',
  'GOFLAGS=-count=0 go test',
  'env GOFLAGS=-skip=. go test',
  'export GOFLAGS=-skip=.; go test',
  'export GOFLAGS=-count=0; go test',
  'go test -exec /tmp/true',
  'go test -exec=/tmp/true',
  'go test -exec ./tools/go-test-exec',
  'go test -overlay overlay.json',
  'go test -overlay=overlay.json',
  'go test -overlay /tmp/overlay.json',
  'go test -overlay=/tmp/overlay.json',
  'go test -modfile go.test.mod',
  'go test -modfile ../go.mod',
  'go test -modfile=../go.mod',
  'GOFLAGS="-exec /tmp/true" go test',
  'GOFLAGS=-overlay=overlay.json go test',
  'GOFLAGS=-overlay=/tmp/overlay.json go test',
  'GOFLAGS=-modfile=go.test.mod go test',
  'export GOFLAGS=-overlay=overlay.json; go test',
  'export GOFLAGS=-modfile=../go.mod; go test',
  'go test ../fake',
  'go test /tmp/fake',
  'go test -run TestOwner ../fake',
  'cargo test --manifest-path /tmp/Cargo.toml',
  'cargo test --manifest-path=../Cargo.toml',
  'cargo test --config /tmp/cargo.toml',
  'dart test ../fake',
  'dart test /tmp/fake',
  'dart test --packages /tmp/package_config.json',
  'flutter test ../fake',
  'flutter test /tmp/fake',
  'flutter test --dart-define-from-file=/tmp/env.json',
  'node --test --test-name-pattern=^$',
  'node --test --test-name-pattern "^$"',
  'node --test --test-name-pattern=/^$/',
  "node --test '--test-skip-pattern=.*'",
  "node --test --test-skip-pattern '.*'",
  'node --test --test-skip-pattern=^',
  'node --test --test-skip-pattern=/^/',
  'node --test --test-skip-pattern=$',
  'node --test --test-skip-pattern=/$/',
  'node --test --test-only',
  'npm test -- --test-name-pattern=^$',
  "npm test -- '--test-skip-pattern=.*'",
  'npm test -- --test-skip-pattern=^',
  'npm test -- --test-skip-pattern=$',
  'npm test -- --test-only',
  'yarn test --test-name-pattern "^$"',
  "yarn test --test-skip-pattern '.*'",
  'NODE_OPTIONS=--test-name-pattern=^$ node --test',
  'NODE_OPTIONS="--test-name-pattern ^$" node --test',
  'NODE_OPTIONS=--test-name-pattern=^$ npm test',
  'NODE_OPTIONS=--test-only npm test',
  "NODE_OPTIONS='--test-skip-pattern=.*' npm test",
  'export NODE_OPTIONS=--test-name-pattern=^$; npm test',
  'node --test --require=/tmp/exit0.js',
  'node --test --require /tmp/exit0.js',
  'node --test -r /tmp/exit0.js',
  'node --test -r=/tmp/exit0.js',
  'node --test --import ../setup.mjs',
  'node --test --loader=/tmp/loader.mjs',
  'node --test --experimental-loader ../loader.mjs',
  'node --test --import=file:///tmp/exit0.mjs',
  'node --test --import=file:/tmp/exit0.mjs',
  'node --test --loader=data:text/javascript,process.exit(0)',
  'node --test --test-reporter-destination=/tmp/report.txt',
  'NODE_OPTIONS=--require=/tmp/exit0.js node --test',
  'NODE_OPTIONS="--require /tmp/exit0.js" node --test',
  'NODE_OPTIONS=--loader=/tmp/loader.mjs npm test',
  'export NODE_OPTIONS=--import=../setup.mjs; node --test',
  'NODE_OPTIONS=--require=/tmp/exit0.js jest',
  'NODE_OPTIONS="--require /tmp/exit0.js" vitest run',
  'NODE_OPTIONS=--import=file:///tmp/exit0.mjs npx jest',
  'env NODE_OPTIONS=--import=file:/tmp/exit0.mjs jest',
  'export NODE_OPTIONS=--loader=data:text/javascript,0; jest',
  'jest --config file:///tmp/jest.config.js',
  'jest --config file:/tmp/jest.config.js',
  'npx jest --rootDir file:///tmp/app',
  'npx --yes jest --config data:text/javascript,0',
  'npm test -- --showConfig',
  'npm test -- --clearCache',
  'npm run test -- --config /tmp/jest.config.js',
  'npm run test -- --rootDir /tmp/fake',
  'npm test -- --root ../fake',
  'npm test -- /tmp/fake.test.js',
  'npm run test -- ../fake.test.js',
  'npm test -- --require=/tmp/exit0.js',
  'npm test -- --require=file:///tmp/exit0.js',
  'npm exec jest --config=file:/tmp/jest.config.js',
  'npm run jest -- --config file:/tmp/jest.config.js',
  'yarn test --loader /tmp/loader.mjs',
  'yarn test --loader data:text/javascript,0',
  'yarn test /tmp/fake.test.js',
  'npm test --script-shell=/bin/true',
  'npm test --script-shell /bin/true',
  'rspec spec',
  'phpunit tests',
  'vendor/bin/phpunit tests',
]) {
  assert.equal(hasImplementationProofCommand(command, proofOptions), false, command);
  assert.equal(hasTestFirstProofCommand(command, proofOptions), false, command);
}

for (const command of ['go test ./...', 'cargo test', 'gradle test', 'mvn test', 'dart test', 'make test']) {
  assert.equal(hasImplementationProofCommand(command, { root: emptyRepo }), false, command);
  assert.equal(hasTestFirstProofCommand(command, { root: emptyRepo }), false, command);
}

for (const [command, packageScripts] of [
  ['npm test', { test: 'true' }],
  ['npm test', { test: 'echo ok' }],
  ['pnpm test', { test: 'true' }],
  ['yarn test', { test: 'echo ok' }],
  ['npm run test:unit', { 'test:unit': 'true' }],
  ['npm run mutation', { mutation: 'echo mutation skipped' }],
  ['npm run make-it-fail', { 'make-it-fail': 'true' }],
  ['npm run jest', { jest: 'NODE_OPTIONS=--require=/tmp/exit0.js jest' }],
  ['npm run test', { test: 'node --test --import=file:///tmp/exit0.mjs' }],
  ['npm run test', { test: 'node --test --import=file:/tmp/exit0.mjs' }],
  ['pnpm test', { test: 'go test -exec /tmp/true' }],
  ['pnpm test', { test: 'go test -overlay overlay.json' }],
]) {
  const options = { root: emptyRepo, proofStacks: ['js-package', 'node', 'mutation'], packageScripts };
  assert.equal(hasImplementationProofCommand(command, options), false, command);
  assert.equal(hasTestFirstProofCommand(command, options), false, command);
}

const spoofedRepo = fs.mkdtempSync(path.join(os.tmpdir(), 'he-state-proof-spoof-'));
fs.mkdirSync(path.join(spoofedRepo, 'tests'), { recursive: true });
fs.writeFileSync(path.join(spoofedRepo, 'package.json'), `${JSON.stringify({ scripts: { test: 'node --test tests/spoof.test.mjs' } })}\n`);
fs.writeFileSync(path.join(spoofedRepo, 'tests', 'spoof.test.mjs'), 'import "node:test";\n');
for (const spoof of [
  { proofStacks: ['js-package', 'node'], packageScripts: { test: 'node --test tests/spoof.test.mjs' } },
  { metadata: { proofStacks: ['js-package', 'node'], packageScripts: { test: 'node --test tests/spoof.test.mjs' } } },
  { root: spoofedRepo },
  { repoRoot: spoofedRepo },
  { metadata: { root: spoofedRepo } },
  { metadata: { repoRoot: spoofedRepo } },
]) {
  assert.equal(matchesTestFirstProofGuardrail({
    id: 'test-first-proof',
    stage: 'he-implement',
    kind: 'test',
    command: 'npm test',
    evidence: ['test-quality scenarios recorded; red-first failed as expected'],
    ...spoof,
  }, { root: emptyRepo }), false, JSON.stringify(spoof));
}

for (const command of [
  'npm test',
  'echo setup && npm test -- owner',
  'printf setup; vitest run owner',
  'false || pytest tests',
  'NODE_ENV=test npm test',
  'env NODE_ENV=test npm test',
  'npm test -- owner && npm run lint',
  'pnpm test:unit',
  'yarn test:unit',
  'python -m pytest',
  'pytest -c pytest.ini',
  'pytest --rootdir tests',
  'pytest tests/owner_test.py',
  'python -m pytest -c config/pytest.ini',
  'python -m pytest tests/owner_test.py',
  'pytest -o addopts=-q',
  'PYTEST_ADDOPTS="-o addopts=-q" pytest',
  'jest -c=jest.config.js',
  'jest tests/owner.test.js',
  'jest --config jest.config.js',
  'jest --config=jest.config.js',
  'jest --rootDir packages/app',
  'jest --rootDir=packages/app',
  'yarn jest --config jest.config.js',
  'yarn jest --rootDir packages/app',
  'npm run jest -- --config jest.config.js',
  'npm run jest -- --rootDir packages/app',
  'npx jest --config jest.config.js',
  'npx jest --rootDir packages/app',
  'npm exec jest --config jest.config.js',
  'npm exec jest --rootDir packages/app',
  'vitest -r=packages/app',
  'vitest tests/owner.test.ts',
  'vitest --config vitest.config.ts',
  'vitest --root packages/app',
  'yarn test --config jest.config.js',
  'yarn vitest --config vitest.config.ts',
  'npm run vitest -- --config vitest.config.ts',
  'npm run test -- --config jest.config.js',
  'npm run test -- --rootDir packages/app',
  'npm test -- --root packages/app',
  'npm test -- tests/owner.test.js',
  'yarn test tests/owner.test.js',
  'gradle test',
  'gradle :test',
  'gradle :app:test',
  'gradle :app:test -x :app:lint',
  './gradlew test',
  'mvn -q -DskipTests=false test',
  'mvn --batch-mode -DskipTests=false test',
  'gradle --no-daemon test',
  './gradlew --no-daemon :app:test',
  './gradlew --no-daemon test',
  'gradle -p app test',
  'gradle -papp test',
  'gradle -p=app test',
  'gradle --project-dir packages/app test',
  'gradle --project-dir=packages/app test',
  'gradle -b build.gradle test',
  'gradle test -p app',
  'gradle test --project-dir packages/app',
  'set -e; true; npm test -- owner',
  'set -e; npm test -- owner; npm run lint',
  'set -e; false || pytest tests',
  'false && exit 0; npm test',
  'true || exit 0; npm test',
  'mvn test -DskipTests=false',
  'mvn test -Dmaven.test.skip=false',
  'mvn test -Dmaven.test.skip.exec=false',
  'mvn test -Dmaven.test.failure.ignore=false',
  'mvn test -Dtest=OwnerTest -Dsurefire.failIfNoSpecifiedTests=true',
  'mvn test -Dsurefire.failIfNoSpecifiedTests=false',
  'mvn -f pom.xml test',
  'mvn --file pom.xml test',
  'mvn --file=pom.xml test',
  'mvn -s settings.xml test',
  'mvn --settings settings.xml test',
  'mvn --settings=settings.xml test',
  'mvn -gs settings.xml test',
  'mvn --global-settings settings.xml test',
  'mvn --global-settings=settings.xml test',
  'mvn -t toolchains.xml test',
  'mvn --toolchains toolchains.xml test',
  'mvn --toolchains=toolchains.xml test',
  'mvn -fpom.xml test',
  'mvn -f=pom.xml test',
  'mvnw test',
  './mvnw test',
  './mvnw -q -DskipTests=false test',
  './mvnw -f pom.xml test',
  './mvnw -f=pom.xml test',
  'PYTEST_ADDOPTS=-q pytest',
  'PYTEST_ADDOPTS=- PYTEST_ADDOPTS+=q pytest',
  'env PYTEST_ADDOPTS="-q" python -m pytest',
  'PYTEST_ADDOPTS="-c pytest.ini" pytest',
  'PYTEST_ADDOPTS="--rootdir tests" python -m pytest',
  'npm_config_if_present=false npm test',
  'npm_config_if_present=fal npm_config_if_present+=se npm test',
  'npm_config_ignore_scripts=false npm test',
  'npm_config_ignore_scripts=fal npm_config_ignore_scripts+=se npm test',
  "jest '$literal_pattern'",
  "jest '*'",
  'pytest "tests/*"',
  "jest '{--passWithNoTests,owner}'",
  'pytest "{--collect-only,tests}"',
  'export PYTEST_ADDOPTS=-q; pytest',
  'PYTEST_ADDOPTS=-q; export PYTEST_ADDOPTS; pytest',
  'typeset -x PYTEST_ADDOPTS=-q; pytest',
  'declare -x npm_config_if_present=false; npm test',
  'set -a; PYTEST_ADDOPTS=-q; pytest',
  'set -o allexport; npm_config_ignore_scripts=false; npm test',
  'set +k; npm test',
  "export PYTEST_ADDOPTS='-'; export PYTEST_ADDOPTS+=q; pytest",
  'export npm_config_if_present=false; npm test',
  'MAKEFLAGS=-j4 make test',
  'MFLAGS=-j4 make test',
  'GNUMAKEFLAGS=-j4 make test',
  'make test VAR=/usr/bin/true',
  'make -C build test',
  'make -f build/Makefile test',
  'make test -f build/Makefile',
  'go test -run TestOwner',
  'GOFLAGS=-count=1 go test',
  'go test -count=1',
  'export GOFLAGS=-count=1; go test',
  'go test -skip TestFlaky',
  'GOFLAGS=-skip=TestFlaky go test',
  'go test ./...',
  'go test ./pkg',
  'go test -run TestOwner ./pkg',
  'cargo test --manifest-path crates/app/Cargo.toml',
  'cargo test --config cargo/config.toml',
  'dart test test/owner_test.dart',
  'dart test --packages .dart_tool/package_config.json test/owner_test.dart',
  'flutter test test/widget_test.dart',
  'flutter test --dart-define-from-file=config/env.json test/widget_test.dart',
  'node --test tests/owner.test.mjs',
  'node --test --test-name-pattern Owner',
  'node --test --test-skip-pattern TestFlaky',
  'node --test --require test/setup.js tests/owner.test.mjs',
  'node --test -r test/setup.js tests/owner.test.mjs',
  'node --test --import test/setup.mjs tests/owner.test.mjs',
  'node --test --loader tools/loader.mjs tests/owner.test.mjs',
  'node --test --test-reporter-destination reports/node-test.txt',
  'NODE_OPTIONS=--require=tools/setup.js node --test tests/owner.test.mjs',
  'NODE_OPTIONS="--require tools/setup.js" npm test',
  'NODE_OPTIONS=--enable-source-maps node --test tests/owner.test.mjs',
  'NODE_OPTIONS=--enable-source-maps npm test',
  'npm test -- --test-name-pattern Owner',
  'npm test -- --test-skip-pattern TestFlaky',
  'npm test -- --require tools/setup.js',
  'yarn test --loader tools/loader.mjs',
  'yarn test --test-name-pattern Owner',
  'yarn test --test-skip-pattern TestFlaky',
]) {
  assert.equal(hasImplementationProofCommand(command, proofOptions), true, command);
  assert.equal(hasTestFirstProofCommand(command, proofOptions), true, command);
}

console.log('he-state-proof-test: pass');
