#!/usr/bin/env node
import assert from 'node:assert/strict';
import {
  hasGreenProof,
  hasImplementationProofCommand,
  hasRedProof,
  hasTestFirstProofCommand,
  hasTestQualityEvidence,
  matchesTestFirstProofGuardrail,
} from '../scripts/he-state-proof.mjs';

for (const command of [
  'npm test || true',
  'npm test; true',
  'npm test | cat',
  'npm test && true || true',
  'npm test && false',
  'npm test && exit 1',
  'npm test && command false',
  'npm test && command exit 1',
  'npm test >/',
  'npm test </missing',
  'npm test &',
  'npm test & true',
  'npm(){ true; }; npm test',
  'npm() ( true ); npm test',
  'pytest() ( true ); pytest',
  'env() ( true ); env NODE_ENV=test npm test',
  'function npm { true; }; npm test',
  'npm()\n{ true; }\nnpm test',
  'npm()\n( true; )\nnpm test',
  'function npm\n{ true; }\nnpm test',
  'jest(){ true; }; jest',
  'function stryker { true; }; stryker run',
  'echo ok || npm test',
  'PATH=./fake-bin npm test',
  'env PATH=./fake-bin npm test',
  '"NODE_ENV=test" npm test',
  'export PATH=./fake-bin:$PATH; npm test',
  'export FOO=ok PATH=./fake-bin:$PATH; npm test',
  'set -e; false; npm test',
  'set -o errexit; false; npm test',
  'set -euo pipefail; false; npm test',
  'set -o pipefail; false | true && npm test',
  'set -eo pipefail; false | true && npm test',
  'npm --if-present test',
  'npm --workspaces --if-present test',
  'npm run test --if-present',
  'npm test -- --help',
  'jest "--passWithNoTests"',
  'jest --passWithNoTests',
  'jest $(printf %s --passWithNoTests)',
  'jest "$(printf %s --passWithNoTests)"',
  'jest `printf %s --passWithNoTests`',
  'jest "`printf %s --passWithNoTests`"',
  'jest --passWithNoTest?',
  'jest *',
  'jest {--passWithNoTests,owner}',
  'pytest {--collect-only,tests}',
  'cargo test "--no-run"',
  'mvn test -DskipTests',
  'mvn test -DskipTests=true',
  'mvn test -Dmaven.test.skip',
  'mvn test -Dmaven.test.skip=true',
  'mvn -q -DskipTests test',
  'mvn -q -DskipTests=true test',
  './mvnw -q -DskipTests test',
  'mvn -q --help test',
  "jest $'--passWithNoTests'",
  "jest $'--passWithNo\\x54ests'",
  'jest $"--passWithNoTests"',
  "cargo test $'--no-run'",
  'pytest --collect-only',
  'mocha --dry-run',
  'node --test --help',
  'go test -list .',
  '{ false; } && npm test',
  '{ exit 0; }; npm test',
  'alias npm=true; npm test',
  'alias jest="jest --passWithNoTests"; jest',
  'alias env=true; env NODE_ENV=test npm test',
  'hash -p /bin/true npm; npm test',
  'hash npm=/bin/true; npm test',
  'eval "npm(){ true; }"; npm test',
  'source ./fake-runners.sh; npm test',
  '. ./fake-runners.sh; npm test',
  'builtin export PATH=./fake-bin:$PATH; npm test',
  'command export PATH=./fake-bin:$PATH; npm test',
  'builtin cd /tmp; npm test',
  'command cd /tmp; npm test',
  'builtin source ./fake-runners.sh; npm test',
  'command source ./fake-runners.sh; npm test',
  'export "PATH=./fake-bin:$PATH"; npm test',
  "export $'PATH=./fake-bin:$PATH'; npm test",
  "export $'P\\x41TH=./fake-bin:$PATH'; npm test",
  'export $"PATH=./fake-bin:$PATH"; npm test',
  'npm --prefix /tmp/fake test',
  'npm --prefix=/tmp/fake test',
  'npm --prefix ../other test',
  'npm test --prefix /tmp/fake',
  'npm test --prefix=/tmp/fake',
  'npm test --prefix ../other',
  'npm --prefix web test --prefix /tmp/fake',
  'pnpm --dir ../other test',
  'pnpm --dir=../other test',
  'pnpm test --dir ../other',
  'pnpm test --dir=../other',
  'yarn --cwd /tmp/fake test',
  'yarn test --cwd /tmp/fake',
  'cd /tmp/fake; npm test',
  'pushd web; npm test',
  'popd; npm test',
  'grep __missing__ /dev/null && npm test',
  '(false) && npm test',
  '(exit 0); npm test',
  "cat <<'#EOF'\nnpm test\n#EOF",
  'cat <<-EOF\nnpm test\nEOF',
  'echo <(true && npm test )',
  'echo >(true && npm test )',
  'echo =(true && npm test )',
  'typeset PATH=./fake-bin:$PATH; npm test',
  'declare -x PATH=./fake-bin:$PATH; npm test',
  'local PATH=./fake-bin:$PATH; npm test',
  'readonly PATH=./fake-bin:$PATH; npm test',
  "trap 'exit 0' ERR; npm test",
  "trap 'exit 0' EXIT; npm test",
  'cargo test --no-run',
  'make test -n',
  'make test --just-print',
  'make mutation --just-print',
  'make make-it-fail -q',
  'make make-it-fail --question',
  'make test -t',
  'mvn test --no-test',
  'mvn -f /tmp/pom.xml test',
  'mvn -f=/tmp/pom.xml test',
  'mvn test -f /tmp/pom.xml',
  './mvnw -f /tmp/pom.xml test',
  './mvnw test -DskipTests',
  'gradle test --no-execute',
  'gradle -p /tmp/fake test',
  'gradle -p=/tmp/fake test',
  'gradle --project-dir ../fake test',
  'gradle --project-dir=/tmp/fake test',
  'gradle -b /tmp/build.gradle test',
  'gradle test -m',
  'gradle --no-daemon test -m',
  'gradle test -p /tmp/fake',
  'gradle test --project-dir ../fake',
  'gradle test --project-dir=/tmp/fake',
  'gradle test -b /tmp/build.gradle',
  'gradle test -p app -p /tmp/fake',
  'gradle test -x test',
  'gradle test -x :test',
  'gradle :test -x :test',
  'gradle :app:test -x :app:test',
  'gradle --no-daemon test -x test',
  './gradlew test -m',
  './gradlew --no-daemon test -m',
  './gradlew test --exclude-task test',
  './gradlew test --exclude-task :test',
  './gradlew test --exclude-task=test',
  './gradlew test --exclude-task=:test',
  './gradlew --no-daemon test --exclude-task=test',
  'PYTEST_ADDOPTS=--collect-only pytest',
  'PYTEST_ADDOPTS=--co pytest',
  'PYTEST_ADDOPTS=--co=tests pytest',
  'PYTEST_ADDOPTS=--help pytest',
  'PYTEST_ADDOPTS=--version pytest',
  'PYTEST_ADDOPTS="-q --help" pytest',
  'PYTEST_ADDOPTS="--collect-only -q" pytest',
  'env PYTEST_ADDOPTS=--collect-only python -m pytest',
  'npm_config_if_present=true npm test',
  'NPM_CONFIG_IF_PRESENT=1 npm run test',
  'npm_config_ignore_scripts=true npm test',
  'npm_config_script_shell=/bin/true npm test',
  'NPM_CONFIG_SCRIPT_SHELL=/bin/true npm test',
  'env npm_config_script_shell=/bin/true npm test',
  'FLAG=--passWithNoTests jest $FLAG',
  'OPTS=--collect-only pytest $OPTS',
  'FLAG=--passWithNoTests jest ${FLAG}',
  'OPTS=--collect-only pytest "$OPTS"',
  'export PYTEST_ADDOPTS=--collect-only; pytest',
  'export PYTEST_ADDOPTS=--help; python -m pytest',
  'PYTEST_ADDOPTS=--collect-only; export PYTEST_ADDOPTS; pytest',
  'typeset -x PYTEST_ADDOPTS=--collect-only; pytest',
  'declare -x PYTEST_ADDOPTS=--help; pytest',
  'set -a; PYTEST_ADDOPTS=--collect-only; pytest',
  'set -o allexport; PYTEST_ADDOPTS=--collect-only; python -m pytest',
  "export PYTEST_ADDOPTS='--collect-only '; export PYTEST_ADDOPTS+=-q; pytest",
  'export npm_config_if_present=true; npm test',
  'export npm_config_ignore_scripts=true; npm test',
  'export npm_config_script_shell=/bin/true; npm test',
  'declare -x npm_config_script_shell=/bin/true; npm test',
  'npm_config_if_present=true; export npm_config_if_present; npm test',
  'typeset -x npm_config_if_present=true; npm test',
  'declare -x npm_config_ignore_scripts=true; npm test',
  'set -a; npm_config_if_present=true; npm test',
  'set -o allexport; npm_config_ignore_scripts=true; npm test',
  'export npm_config_if_present=; export npm_config_if_present+=true; npm test',
  'make test -f /tmp/Makefile',
  'make test --file ../Makefile',
  'make test --makefile=/tmp/Makefile',
  'make test -f build/Makefile -f /tmp/Makefile',
  'make test -C /tmp/fake',
  'pytest --fixtures',
  'pytest --markers',
  'pytest --setup-only',
  'pytest --setup-plan',
  'pytest -c /tmp/pytest.ini',
  'pytest --rootdir /tmp/tests',
  'pytest --rootdir=../tests',
  'python -m pytest --setup-only',
  'python -m pytest --setup-plan',
  'python -m pytest -c /tmp/pytest.ini',
  'python -m pytest --fixtures-per-test',
  'jest -c=/tmp/jest.config.js',
  'jest --showConfig',
  'jest --clearCache',
  'jest --config /tmp/jest.config.js',
  'jest --config=../jest.config.js',
  'jest --rootDir /tmp/fake',
  'jest --rootDir=../fake',
  'yarn jest --showConfig',
  'npm run jest -- --clearCache',
  'yarn jest --config /tmp/jest.config.js',
  'yarn jest --rootDir /tmp/fake',
  'npm run jest -- --config /tmp/jest.config.js',
  'npm run jest -- --rootDir /tmp/fake',
  'npx jest --config /tmp/jest.config.js',
  'npx jest --rootDir /tmp/fake',
  'npm exec jest --config /tmp/jest.config.js',
  'npm exec jest --rootDir /tmp/fake',
  'vitest -r=/tmp/app',
  'vitest --config /tmp/vitest.config.ts',
  'vitest --root /tmp/app',
  'yarn vitest --config /tmp/vitest.config.ts',
  'npm run vitest -- --config /tmp/vitest.config.ts',
  'npx vitest --config /tmp/vitest.config.ts',
  'npx jest --showConfig',
  'npm exec jest --clearCache',
  'go test -run=^$',
  'go test -run "^$"',
  'npm test --script-shell=/bin/true',
  'npm test --script-shell /bin/true',
]) {
  assert.equal(hasImplementationProofCommand(command), false, command);
  assert.equal(hasTestFirstProofCommand(command), false, command);
}

for (const command of [
  'npm test',
  'echo setup && npm test -- owner',
  'printf setup; vitest run owner',
  'false || pytest tests',
  'NODE_ENV=test npm test',
  'env NODE_ENV=test npm test',
  'npm -w web test',
  'npm --workspaces test',
  'npm --ws test',
  'npm --workspaces run test',
  'npm --prefix web test',
  'npm --prefix=packages/web test',
  'npm test --prefix web',
  'npm test --prefix=packages/web',
  'pnpm -w test',
  'pnpm --workspace-root test',
  'pnpm --dir packages/web test',
  'pnpm test --dir packages/web',
  'yarn --cwd ./web test',
  'yarn test --cwd ./web',
  'npm test -- owner && npm run lint',
  'pnpm test:unit',
  'yarn test:unit',
  'python -m pytest',
  'pytest -c pytest.ini',
  'pytest --rootdir tests',
  'python -m pytest -c config/pytest.ini',
  'jest -c=jest.config.js',
  'jest --config jest.config.js',
  'jest --rootDir packages/app',
  'jest --rootDir=packages/app',
  'yarn jest --config jest.config.js',
  'yarn jest --rootDir packages/app',
  'npm run jest -- --config jest.config.js',
  'npm run jest -- --rootDir packages/app',
  'npx jest --config jest.config.js',
  'npx jest --rootDir packages/app',
  'npm exec jest --config jest.config.js',
  'npm exec jest --rootDir packages/app',
  'vitest -r=packages/app',
  'vitest --config vitest.config.ts',
  'vitest --root packages/app',
  'yarn vitest --config vitest.config.ts',
  'npm run vitest -- --config vitest.config.ts',
  'gradle test',
  'gradle :test',
  'gradle :app:test',
  'gradle :app:test -x :app:lint',
  './gradlew test',
  'mvn -q -DskipTests=false test',
  'mvn --batch-mode -DskipTests=false test',
  'gradle --no-daemon test',
  './gradlew --no-daemon :app:test',
  './gradlew --no-daemon test',
  'gradle -p app test',
  'gradle -papp test',
  'gradle -p=app test',
  'gradle --project-dir packages/app test',
  'gradle --project-dir=packages/app test',
  'gradle -b build.gradle test',
  'gradle test -p app',
  'gradle test --project-dir packages/app',
  'set -e; true; npm test -- owner',
  'set -e; npm test -- owner; npm run lint',
  'set -e; false || pytest tests',
  'mvn test -DskipTests=false',
  'mvn test -Dmaven.test.skip=false',
  'mvn -f pom.xml test',
  'mvn --file pom.xml test',
  'mvn --file=pom.xml test',
  'mvn -fpom.xml test',
  'mvn -f=pom.xml test',
  'mvnw test',
  './mvnw test',
  './mvnw -q -DskipTests=false test',
  './mvnw -f pom.xml test',
  './mvnw -f=pom.xml test',
  'PYTEST_ADDOPTS=-q pytest',
  'env PYTEST_ADDOPTS="-q" python -m pytest',
  'npm_config_if_present=false npm test',
  'npm_config_ignore_scripts=false npm test',
  "jest '$literal_pattern'",
  "jest '*'",
  'pytest "tests/*"',
  "jest '{--passWithNoTests,owner}'",
  'pytest "{--collect-only,tests}"',
  'export PYTEST_ADDOPTS=-q; pytest',
  'PYTEST_ADDOPTS=-q; export PYTEST_ADDOPTS; pytest',
  'typeset -x PYTEST_ADDOPTS=-q; pytest',
  'declare -x npm_config_if_present=false; npm test',
  'set -a; PYTEST_ADDOPTS=-q; pytest',
  'set -o allexport; npm_config_ignore_scripts=false; npm test',
  "export PYTEST_ADDOPTS='-'; export PYTEST_ADDOPTS+=q; pytest",
  'export npm_config_if_present=false; npm test',
  'make test -f build/Makefile',
  'go test -run TestOwner',
]) {
  assert.equal(hasImplementationProofCommand(command), true, command);
  assert.equal(hasTestFirstProofCommand(command), true, command);
}

for (const evidence of [
  'test-quality not used; 1 failed test',
  'without test-quality; 1 failed test',
  'skipped test-quality; 1 failed test',
  'no test-quality; 1 failed test',
  'test-quality evidence missing; 1 failed test',
  'test-quality skill was skipped; 1 failed test',
  'test-quality scenario was not used; 1 failed test',
  'test-quality review missing; 1 failed test',
  'test-quality review is missing; 1 failed test',
  'test-quality scenarios are missing; 1 failed test',
  'test-quality review is disabled; 1 failed test',
  'test-quality scenarios are unavailable; 1 failed test',
  'test-quality skill was not loaded; 1 failed test',
  'test-quality skill; 1 failed test',
  'not recorded test-quality evidence; 1 failed test',
  'no recorded test-quality evidence; 1 failed test',
  'without used test-quality review; 1 failed test',
  'no used test-quality review; 1 failed test',
  'never used test-quality review; 1 failed test',
  'failed to use test-quality evidence; 1 failed test',
  'without `test-quality`; test-quality scenarios recorded; 1 failed test',
]) {
  const guardrail = {
    id: 'test-first-proof',
    stage: 'he-implement',
    kind: 'test',
    command: 'npm test -- owner',
    evidence: [evidence],
  };
  assert.equal(hasTestQualityEvidence(guardrail), false, evidence);
  assert.equal(matchesTestFirstProofGuardrail(guardrail), false, evidence);
}

for (const evidence of ['test-quality scenarios recorded; 1 failed test', 'test-quality review was used; 1 failed test', 'used test-quality review; 1 failed test', 'loaded `test-quality`; 1 failed test']) {
  const guardrail = {
    id: 'test-first-proof',
    stage: 'he-implement',
    kind: 'test',
    command: 'npm test -- owner',
    evidence: [evidence],
  };
  assert.equal(hasTestQualityEvidence(guardrail), true, evidence);
  assert.equal(matchesTestFirstProofGuardrail(guardrail), true, evidence);
}

for (const [command, evidence] of [
  ['npm test -- owner', 'test-quality scenarios recorded; mutation proof killed: 1 expected mutant before implementation'],
  ['npm test -- owner', 'test-quality scenarios recorded; mutation proof failed as expected before implementation'],
  ['npm test -- owner', 'test-quality scenarios recorded; make-it-fail failed as expected before implementation'],
  ['stryker run owner-mutants', 'test-quality scenarios recorded; 1 failed test'],
  ['npm run make-it-fail', 'test-quality scenarios recorded; 1 failed test'],
]) {
  assert.equal(matchesTestFirstProofGuardrail({
    id: 'test-first-proof',
    stage: 'he-implement',
    kind: 'test',
    command,
    evidence: [evidence],
  }), false, `${command}: ${evidence}`);
}

for (const evidence of ['1 failed, 5 passed; expected green button', '2 failed, 10 passed; expected clean label', 'red-first failed as expected for green button', 'red-first failed as expected for clean label', 'expected 1 failed test, got 1 failed, 5 passed', 'expected 1 failed test; recorded red output: 1 failed test', 'test-quality scenarios recorded; actual red output recorded: 1 failed test', 'mutation proof killed: 1 expected mutant before implementation', 'mutation proof failed as expected before implementation']) {
  assert.equal(hasRedProof(evidence), true, evidence);
}

for (const evidence of [
  'all tests passed green',
  'clean test run',
  '0 failed, 5 passed; expected green button',
  'test-quality scenarios recorded; expected 1 failed test but it did not fail',
  'test-quality scenarios recorded; expected 1 failed test but it did not run',
  'test-quality scenarios recorded; mutation score 0%; 0 killed, 1 survived',
  'test-quality scenarios recorded; mutation run: none killed',
  'test-quality scenarios recorded; mutation run failed as expected; 0 killed, 1 survived',
  'test-quality scenarios recorded; expected 1 failed test, got 5 passed',
  'test-quality scenarios recorded; expected 2 failing tests, actual 7 tests passed',
  'test-quality scenarios recorded; expected failures: 1 but passed',
  'test-quality scenarios recorded; expected 1 failed test',
  'test-quality scenarios recorded; expected 1 failed test recorded',
  'test-quality scenarios recorded; recorded failure expectation: expected 1 failed test',
  'test-quality scenarios recorded: expected 1 failed test',
  'test-quality scenarios recorded; should report 1 failed test',
  'test-quality scenarios recorded; would show 1 failing test',
]) {
  assert.equal(hasRedProof(evidence), false, evidence);
}

for (const evidence of ['expected tests passed', 'should be green', 'would be clean']) {
  assert.equal(hasGreenProof(evidence), false, evidence);
}

for (const evidence of ['actual tests passed', 'green test run recorded', '5 passed, 1 skipped']) {
  assert.equal(hasGreenProof(evidence), true, evidence);
}

for (const evidence of [
  'test-quality scenarios recorded; mutation score 0%; 0 killed, 1 survived',
  'test-quality scenarios recorded; mutation run: none killed',
  'test-quality scenarios recorded; mutation run failed as expected',
  'test-quality scenarios recorded; mutation run failed as expected; 1 mutant survived',
  'test-quality scenarios recorded; mutation run failed as expected; survived mutants: 1',
  'test-quality scenarios recorded; mutation run failed as expected; 1 mutant escaped',
  'test-quality scenarios recorded; mutation run failed as expected; 1 mutation undetected',
  'test-quality scenarios recorded; mutation run failed as expected; mutation undetected: 1',
  'test-quality scenarios recorded; mutation run failed as expected; mutants undetected: 1',
  'test-quality scenarios recorded; mutation run failed as expected; 0 killed, 1 survived',
  'test-quality scenarios recorded; mutation proof did not fail; mutation proof failed as expected',
]) {
  assert.equal(matchesTestFirstProofGuardrail({
    id: 'test-first-proof',
    stage: 'he-implement',
    kind: 'test',
    command: 'stryker run owner-mutants',
    evidence: [evidence],
  }), false, evidence);
}

assert.equal(matchesTestFirstProofGuardrail({
  id: 'test-first-proof',
  stage: 'he-implement',
  kind: 'test',
  command: 'npm run make-it-fail',
  evidence: ['test-quality scenarios recorded; make-it-fail did not fail; make-it-fail failed as expected'],
}), false);

for (const [command, evidence] of [
  ['stryker run owner-mutants', 'test-quality scenarios recorded; all tests passed; 1 mutant killed'],
  ['stryker run owner-mutants', 'test-quality scenarios recorded; 0 failed, 5 passed; mutation killed: 1'],
  ['npm run make-it-fail', 'test-quality scenarios recorded; all tests passed; make-it-fail failed as expected'],
  ['npm run make-it-fail', 'test-quality scenarios recorded; 0 failed, 5 passed; make-it-fail failed as expected'],
]) {
  assert.equal(matchesTestFirstProofGuardrail({
    id: 'test-first-proof',
    stage: 'he-implement',
    kind: 'test',
    command,
    evidence: [evidence],
  }), true, evidence);
}

console.log('he-state-proof-test: pass');
