"""Setup adopting existing repositories: old generations, repair and project formatters."""

import json
import shutil
import subprocess
from pathlib import Path
from types import ModuleType
from unittest.mock import Mock

import pytest
import update
from conftest import commit, git
from gate_config import json_file
from test_setup import repository
from test_updates import select_release

OLD_COMMAND = 'bash "$(env -u GIT_DIR git rev-parse --show-toplevel)/.hard-eng/{}" {}'
OLD_FILES = {
    ".hard-eng/bootstrap.sh": "#!/usr/bin/env bash\n# Generated by Hard Eng. Fetches the newest Hard Eng.\n",
    ".hard-eng/hook.sh": "#!/usr/bin/env bash\n# Generated by Hard Eng. Runs the repository copy.\n",
    "AGENTS.override.md": "<!-- Generated by Hard Eng for Codex: rules. -->\n\n# Old rules\n",
    ".github/instructions/hard-eng.instructions.md": '---\napplyTo: "**"\n---\n\n'
    "<!-- Generated by Hard Eng from .agents/hard-eng/current/AGENTS.md. -->\n\n# Old\n",
}


def write_old_generation(root: Path) -> dict[str, str]:
    """Write the previous generation's wiring beside project-owned files."""
    for name, content in OLD_FILES.items():
        (root / name).parent.mkdir(parents=True, exist_ok=True)
        (root / name).write_text(content)
    project = {
        ".github/copilot-instructions.md": "Project Copilot rules\n",
        ".github/instructions/project.instructions.md": "Project rules\n",
    }
    for name, content in project.items():
        (root / name).write_text(content)
    handler = {"type": "command", "command": "project-guard"}
    for agent, name in (
        ("claude", ".claude/settings.json"),
        ("codex", ".codex/hooks.json"),
    ):
        (root / name).parent.mkdir(exist_ok=True)
        (root / name).write_text(
            json.dumps(
                {
                    "hooks": {
                        "SessionStart": [
                            {
                                "matcher": "startup|resume",
                                "hooks": [
                                    {
                                        "type": "command",
                                        "command": OLD_COMMAND.format(
                                            "bootstrap.sh", agent
                                        ),
                                    }
                                ],
                            }
                        ],
                        "PreToolUse": [
                            {
                                "hooks": [
                                    {
                                        "type": "command",
                                        "command": OLD_COMMAND.format(
                                            "hook.sh", agent + " pretooluse"
                                        ),
                                    },
                                    handler,
                                ]
                            }
                        ],
                    }
                }
            )
        )
    (root / ".github/hooks").mkdir(parents=True, exist_ok=True)
    (root / ".github/hooks/hard-eng.json").write_text(
        json.dumps(
            {
                "version": 1,
                "hooks": {
                    "sessionStart": [
                        {
                            "type": "command",
                            "bash": OLD_COMMAND.format("bootstrap.sh", "copilot"),
                        }
                    ],
                    "preToolUse": [
                        {
                            "type": "command",
                            "bash": OLD_COMMAND.format("hook.sh", "copilot pretooluse"),
                        }
                    ],
                },
            }
        )
    )
    (root / ".hard-eng/sessions").mkdir(parents=True, exist_ok=True)
    (root / ".hard-eng/sessions/current.json").write_text("{}\n")
    return project


def assert_old_generation_retired(root: Path, project: dict[str, str]) -> None:
    for name in OLD_FILES:
        assert not (root / name).exists(), name
    for name, content in project.items():
        assert (root / name).read_text() == content
    assert (root / ".hard-eng/sessions/current.json").is_file()
    for name in (
        ".claude/settings.json",
        ".codex/hooks.json",
        ".github/hooks/hard-eng.json",
    ):
        assert ".hard-eng/" not in (root / name).read_text(), name
    for name in (".claude/settings.json", ".codex/hooks.json"):
        (group,) = json.loads((root / name).read_text())["hooks"]["PreToolUse"]
        assert group == {"hooks": [{"type": "command", "command": "project-guard"}]}


@pytest.mark.parametrize("tracked", [True, False])
def test_install_retires_old_generation_and_keeps_project_files(
    installer: ModuleType, tmp_path: Path, tracked: bool
) -> None:
    repository(tmp_path)
    project = write_old_generation(tmp_path)
    if tracked:
        subprocess.run(["git", "add", "."], cwd=tmp_path, check=True)
        subprocess.run(
            [
                "git",
                "-c",
                "user.name=Fixture",
                "-c",
                "user.email=fixture@example.invalid",
                "commit",
                "-qm",
                "old",
            ],
            cwd=tmp_path,
            check=True,
        )
    else:
        (tmp_path / ".git/info/exclude").write_text("\n".join(OLD_FILES) + "\n")
    installer.install(tmp_path)
    assert_old_generation_retired(tmp_path, project)
    tracked_names = subprocess.check_output(
        ["git", "ls-files"], cwd=tmp_path, text=True
    ).split()
    assert not set(OLD_FILES) & set(tracked_names)
    assert ".hard-eng/" not in (tmp_path / "hard-eng.gates.json").read_text()


def test_install_removes_edited_old_generation_files(
    installer: ModuleType, tmp_path: Path
) -> None:
    repository(tmp_path)
    edited = {name: "Local notes\n" + content for name, content in OLD_FILES.items()}
    for name, content in edited.items():
        (tmp_path / name).parent.mkdir(parents=True, exist_ok=True)
        (tmp_path / name).write_text(content)
    installer.install(tmp_path)
    for name in edited:
        assert not (tmp_path / name).exists(), name


@pytest.mark.parametrize("committed", [True, False])
def test_setup_rerun_restores_missing_installed_files(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch, committed: bool
) -> None:
    _, target, _ = release
    gates = (target / "hard-eng.gates.json").read_bytes()
    shutil.rmtree(target / ".agents")
    if committed:
        git(target, "commit", "-qam", "remove installed skills")
    monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    assert "available." in update.update(target)
    assert not (target / ".agents").exists()
    message = update.update(target, repair=True)
    assert ".agents/skills/he/" in message
    assert (target / ".claude/skills/he/SKILL.md").is_file()
    assert (target / "hard-eng.gates.json").read_bytes() == gates
    assert (target / "project.txt").read_text() == "original\n"
    assert git(target, "status", "--porcelain") == ""


def test_setup_rerun_retires_old_generation(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch
) -> None:
    _, target, _ = release
    project = write_old_generation(target)
    git(target, "add", "--force", *OLD_FILES)
    commit(target, "old generation wiring")
    monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    update.update(target, repair=True)
    assert not set(OLD_FILES) & set(git(target, "ls-files").splitlines())
    assert_old_generation_retired(target, project)
    assert git(target, "status", "--porcelain") == ""


@pytest.mark.parametrize(
    ("repair", "options", "edited"),
    [
        (False, [], False),
        (True, [], False),
        (False, ["--external-sources"], False),
        (True, ["--external-sources"], False),
        (True, [], True),
    ],
)
def test_update_retires_old_generation(
    release: tuple[Path, Path, str],
    monkeypatch: pytest.MonkeyPatch,
    repair: bool,
    options: list[str],
    edited: bool,
) -> None:
    source, target, _ = release
    project = write_old_generation(target)
    gates = target / "hard-eng.gates.json"
    config = json.loads(gates.read_text().replace("raise SystemExit(1)", "None"))
    scripts = [".hard-eng/bootstrap.sh", ".hard-eng/hook.sh"]
    config["shared"].append(
        {
            "name": "shellcheck",
            "role": "shell",
            "command": ["shellcheck", *options, "--", *scripts],
        }
    )
    gates.write_text(json.dumps(config))
    (target / "package.json").unlink()
    git(target, "add", "--force", *OLD_FILES)
    commit(target, "old generation wiring")
    if edited:
        with (target / scripts[1]).open("a") as script:
            script.write("echo local\n")
    if repair:
        monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    else:
        select_release(source, monkeypatch)
    update.update(target, repair=repair)
    tracked = set(git(target, "ls-files").splitlines())
    assert edited or not set(OLD_FILES) & tracked
    assert_old_generation_retired(target, project)
    assert ".hard-eng/" not in gates.read_text()
    assert "shellcheck" not in gates.read_text()


@pytest.mark.parametrize(
    ("config", "opening"),
    [
        ("{}\n", "{\n\t"),
        (
            (
                '{\n  // project style\n  "formatter": {"indentStyle": "space",},\n'
                '  "json": {"formatter": {"indentWidth": 4}}\n}\n'
            ),
            "{\n    ",
        ),
    ],
)
def test_setup_json_stays_in_the_project_biome_layout(
    installer: ModuleType, tmp_path: Path, config: str, opening: str
) -> None:
    repository(tmp_path)
    (tmp_path / "index.js").write_text("export {};\n")
    (tmp_path / "biome.jsonc").write_text(config)
    changes = installer.plan_install(tmp_path.resolve())[0]
    shipped = ".agents/biome.json"
    assert changes[shipped] == (installer.SOURCE / shipped).read_text()
    written = {
        name: text
        for name, text in changes.items()
        if name.endswith(".json") and not name.startswith(".agents/")
    }
    assert {".mcp.json", ".hooks/hard-eng-source.json", "tsconfig.json"} <= set(written)
    for text in written.values():
        assert text == json_file(tmp_path, json.loads(text))
        assert text.startswith(opening)


def test_setup_rerun_leaves_local_settings_edits_uncommitted(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch
) -> None:
    _, target, _ = release
    write_old_generation(target)
    git(target, "add", "--force", *OLD_FILES)
    commit(target, "old generation wiring")
    settings = target / ".claude/settings.json"
    edited = json.loads(settings.read_text())
    edited["permissions"] = {"allow": ["Bash(ls)"]}
    settings.write_text(json.dumps(edited))
    override = target / "AGENTS.override.md"
    override.write_text(override.read_text() + "Local deployment rule\n")
    monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    update.update(target, repair=True)
    assert not override.exists()
    assert "permissions" not in git(target, "show", "HEAD:.claude/settings.json")
    assert "permissions" in settings.read_text()


def test_install_removes_every_old_hook_command(
    installer: ModuleType, tmp_path: Path
) -> None:
    repository(tmp_path)
    write_old_generation(tmp_path)
    settings = tmp_path / ".claude/settings.json"
    current = json.loads(settings.read_text())
    current["hooks"]["PreToolUse"][0]["hooks"] += [
        {"type": "command", "command": "cd .hard-eng && bash hook.sh && ./guard"},
        {"type": "command", "command": "bash .hard-eng/bootstrap.sh claude"},
    ]
    settings.write_text(json.dumps(current))
    copilot = tmp_path / ".github/hooks/hard-eng.json"
    wiring = json.loads(copilot.read_text())
    wiring["hooks"]["preToolUse"][0]["powershell"] = "./guard.ps1"
    copilot.write_text(json.dumps(wiring))
    policy = tmp_path / ".github/hooks/project-policy.json"
    guard = {"type": "command", "bash": "./guard.sh"}
    old = {"type": "command", "bash": "bash .hard-eng/hook.sh copilot"}
    policy.write_text(json.dumps({"version": 1, "hooks": {"preToolUse": [old, guard]}}))
    git(tmp_path, "add", "--force", ".")
    commit(tmp_path, "old generation wiring")
    installer.install(tmp_path)
    for name in (settings, copilot, policy):
        assert ".hard-eng" not in name.read_text()
    assert json.loads(policy.read_text())["hooks"]["preToolUse"] == [guard]
    (group,) = json.loads(settings.read_text())["hooks"]["PreToolUse"]
    assert group["hooks"] == [{"type": "command", "command": "project-guard"}]
    assert not (tmp_path / ".hard-eng/hook.sh").exists()


def test_install_retires_a_claude_md_that_only_imports_agents_md(
    installer: ModuleType, tmp_path: Path
) -> None:
    repository(tmp_path)
    (tmp_path / "CLAUDE.md").write_text(
        "<!-- hard-eng:start -->\n@AGENTS.md\n<!-- hard-eng:end -->\n\n"
    )
    git(tmp_path, "add", "CLAUDE.md")
    commit(tmp_path, "Install Hard Eng")
    installer.install(tmp_path)
    assert not (tmp_path / "CLAUDE.md").exists()
    assert "CLAUDE.md" not in git(tmp_path, "ls-files").splitlines()


def test_install_rejects_an_edited_import_only_claude_md(
    installer: ModuleType, tmp_path: Path
) -> None:
    repository(tmp_path)
    (tmp_path / "CLAUDE.md").write_text(
        "<!-- hard-eng:start -->\n@docs/rules.md\n<!-- hard-eng:end -->\n\n"
    )
    with pytest.raises(ValueError, match="CLAUDE.md"):
        installer.install(tmp_path)


def test_install_imports_agents_md_under_a_parent_claude_md(
    installer: ModuleType, tmp_path: Path
) -> None:
    (tmp_path / "CLAUDE.md").write_text("Workspace rules\n")
    root = tmp_path / "project"
    root.mkdir()
    repository(root)
    installer.install(root)
    assert "\n@AGENTS.md\n" in (root / "CLAUDE.md").read_text()


def test_install_leaves_old_scripts_behind_a_linked_directory(
    installer: ModuleType, tmp_path: Path
) -> None:
    shared = tmp_path / "shared"
    shared.mkdir()
    (shared / "hook.sh").write_text(OLD_FILES[".hard-eng/hook.sh"])
    root = tmp_path / "project"
    root.mkdir()
    repository(root)
    (root / ".hard-eng").symlink_to(shared, target_is_directory=True)
    installer.install(root)
    assert (shared / "hook.sh").read_text() == OLD_FILES[".hard-eng/hook.sh"]


def test_setup_rerun_imports_agents_md_into_a_new_project_claude_md(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch
) -> None:
    _, target, _ = release
    (target / "CLAUDE.md").write_text("Project rules\n")
    commit(target, "project rules")
    monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    update.update(target, repair=True)
    text = (target / "CLAUDE.md").read_text()
    assert "\n@AGENTS.md\n" in text
    assert text.endswith("Project rules\n")


def test_install_removes_the_old_local_hard_eng_copy(
    installer: ModuleType, tmp_path: Path
) -> None:
    repository(tmp_path)
    payload = tmp_path / ".agents/hard-eng/current"
    (payload / "skills/plain-english").mkdir(parents=True)
    (payload / "skills/plain-english/SKILL.md").write_text("old\n")
    (tmp_path / ".claude/skills").mkdir(parents=True)
    (tmp_path / ".claude/skills/plain-english").symlink_to(
        "../../.agents/hard-eng/current/skills/plain-english"
    )
    (payload / "output-styles").mkdir()
    (payload / "output-styles/plain-english.md").write_text("old\n")
    (tmp_path / ".claude/output-styles").mkdir()
    (tmp_path / ".claude/output-styles/plain-english.md").symlink_to(
        "../../.agents/hard-eng/current/output-styles/plain-english.md"
    )
    (tmp_path / "CLAUDE.local.md").write_text("@.agents/hard-eng/current/AGENTS.md\n")
    old = f"bash {payload}/scripts/hooks/agent-hook.sh claude pretooluse"
    local = {
        "outputStyle": "Plain English",
        "permissions": {"allow": ["Bash(ls)"]},
        "hooks": {
            "PreToolUse": [
                {"hooks": [{"type": "command", "command": old}]},
                {"hooks": [{"type": "command", "command": "bash .hard-eng/hook.sh"}]},
            ]
        },
    }
    (tmp_path / ".claude/settings.local.json").write_text(json.dumps(local))
    (tmp_path / ".codex").mkdir()
    (tmp_path / ".codex/config.toml").write_text(
        'model = "o3"\nproject_doc_max_bytes = 65536 # Generated by Hard Eng\n'
    )
    exclude = tmp_path / ".git/info/exclude"
    exclude.write_text(
        "*.log\n\n# >>> hard-eng repository fallback >>>\n/.agents/hard-eng/\n"
        "/.claude/settings.local.json\n/.claude/output-styles/plain-english.md\n"
        "# <<< hard-eng repository fallback <<<\n"
    )
    installer.install(tmp_path)
    assert not (tmp_path / ".agents/hard-eng").exists()
    assert not (tmp_path / ".claude/skills/plain-english").is_symlink()
    assert not (tmp_path / ".claude/output-styles/plain-english.md").is_symlink()
    assert not (tmp_path / "CLAUDE.local.md").exists()
    assert json.loads((tmp_path / ".claude/settings.local.json").read_text()) == {
        "permissions": {"allow": ["Bash(ls)"]}
    }
    codex = (tmp_path / ".codex/config.toml").read_text()
    assert codex.startswith('model = "o3"\n')
    assert "project_doc_max_bytes" not in codex
    assert exclude.read_text() == (
        "*.log\n\n/.agents/hard-eng/\n/.claude/settings.local.json\n"
        "/.claude/output-styles/plain-english.md\n"
    )
    assert not (tmp_path / "CLAUDE.md").exists()


def test_install_leaves_linked_legacy_folders_untouched(
    installer: ModuleType, tmp_path: Path
) -> None:
    shared = tmp_path / "shared"
    (shared / "agents/hard-eng/current").mkdir(parents=True)
    (shared / "claude").mkdir()
    settings = '{"outputStyle": "Plain English"}'
    (shared / "claude/settings.local.json").write_text(settings)
    root = tmp_path / "project"
    root.mkdir()
    repository(root)
    (root / ".agents").symlink_to(shared / "agents", target_is_directory=True)
    (root / ".claude").symlink_to(shared / "claude", target_is_directory=True)
    with pytest.raises(ValueError, match=r"\.agents|\.claude"):
        installer.install(root)
    assert (shared / "agents/hard-eng/current").is_dir()
    assert (shared / "claude/settings.local.json").read_text() == settings


def test_install_refuses_a_skills_folder_linked_into_another_copy(
    installer: ModuleType, tmp_path: Path
) -> None:
    shared = tmp_path / "other/.agents/hard-eng/current/skills"
    shared.mkdir(parents=True)
    root = tmp_path / "project"
    root.mkdir()
    repository(root)
    (root / ".agents").mkdir()
    (root / ".agents/skills").symlink_to(shared, target_is_directory=True)
    with pytest.raises(ValueError, match="symlink"):
        installer.install(root)
    assert not any(shared.iterdir())


def test_install_keeps_the_old_copy_when_local_settings_are_malformed(
    installer: ModuleType, tmp_path: Path
) -> None:
    repository(tmp_path)
    (tmp_path / ".agents/hard-eng/current").mkdir(parents=True)
    (tmp_path / ".claude").mkdir()
    (tmp_path / ".claude/settings.local.json").write_text("{")
    with pytest.raises(ValueError):
        installer.install(tmp_path)
    assert (tmp_path / ".agents/hard-eng/current").is_dir()


@pytest.mark.parametrize("repair", [True, False])
def test_update_replaces_old_skill_links_and_cleans_local_settings(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch, repair: bool
) -> None:
    _, target, _ = release
    (target / ".agents/hard-eng/current/skills/he").mkdir(parents=True)
    link = target / ".claude/skills/he"
    link.unlink()
    link.symlink_to("../../.agents/hard-eng/current/skills/he")
    local = {
        "hooks": {
            "Stop": [
                {"hooks": [{"type": "command", "command": "bash .hard-eng/hook.sh"}]}
            ]
        }
    }
    (target / ".claude/settings.local.json").write_text(json.dumps(local))
    monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    update.update(target, repair=repair)
    assert link.resolve() == (target / ".agents/skills/he").resolve()
    assert not (target / ".agents/hard-eng").exists()
    assert json.loads((target / ".claude/settings.local.json").read_text()) == {}


@pytest.mark.parametrize("repair", [True, False])
def test_update_replaces_a_skill_folder_linked_into_the_old_copy(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch, repair: bool
) -> None:
    source, target, _ = release
    skill = target / ".agents/skills/he"
    (target / ".agents/hard-eng/current/skills").mkdir(parents=True)
    skill.rename(target / ".agents/hard-eng/current/skills/he")
    skill.symlink_to("../hard-eng/current/skills/he", target_is_directory=True)
    with (target / ".git/info/exclude").open("a") as exclude:
        exclude.write(".agents/hard-eng/\n")
    git(target, "add", "--all", ".agents/skills")
    commit(target, "old skill link")
    if repair:
        monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    else:
        select_release(source, monkeypatch)
    update.update(target, repair=repair)
    assert not skill.is_symlink()
    assert (target / ".claude/skills/he/SKILL.md").is_file()
    assert not (target / ".agents/hard-eng").exists()
    assert git(target, "status", "--porcelain") == ""


def test_install_replaces_older_skill_files_behind_an_old_link(
    installer: ModuleType, tmp_path: Path
) -> None:
    repository(tmp_path)
    old = tmp_path / ".agents/hard-eng/current/skills/he"
    old.mkdir(parents=True)
    (old / "SKILL.md").write_text("older release\n")
    (tmp_path / ".agents/skills").mkdir()
    (tmp_path / ".agents/skills/he").symlink_to("../hard-eng/current/skills/he")
    installer.install(tmp_path)
    skill = tmp_path / ".agents/skills/he/SKILL.md"
    assert not skill.parent.is_symlink()
    assert (
        skill.read_text()
        == (installer.SOURCE / ".agents/skills/he/SKILL.md").read_text()
    )
    assert not (tmp_path / ".agents/hard-eng").exists()


def test_update_checks_local_settings_before_committing(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch
) -> None:
    source, target, _ = release
    (target / ".agents/hard-eng/current").mkdir(parents=True)
    settings = target / ".claude/settings.local.json"
    settings.write_text("{")
    select_release(source, monkeypatch)
    with pytest.raises(ValueError):
        update.update(target)
    assert (target / ".agents/hard-eng/current").is_dir()
    settings.write_text('{"outputStyle": "Plain English"}')
    update.update(target)
    assert not (target / ".agents/hard-eng").exists()
    assert json.loads(settings.read_text()) == {}


def test_update_plan_deletes_only_tracked_old_files(
    installer: ModuleType, tmp_path: Path
) -> None:
    repository(tmp_path)
    write_old_generation(tmp_path)
    git(tmp_path, "add", "--force", "AGENTS.override.md")
    git(tmp_path, "commit", "-qm", "tracked old file")
    *_, retired = installer.plan_install(tmp_path)
    assert retired == ["AGENTS.override.md"]


def test_session_start_removes_untracked_fallback_files(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch
) -> None:
    _, target, _ = release
    (target / "AGENTS.override.md").write_text(OLD_FILES["AGENTS.override.md"])
    (target / "CLAUDE.local.md").write_text("@.agents/hard-eng/current/AGENTS.md\n")
    exclude = target / ".git/info/exclude"
    before = exclude.read_text()
    exclude.write_text(
        before + "# >>> hard-eng repository fallback >>>\n/AGENTS.override.md\n"
        "/CLAUDE.local.md\n# <<< hard-eng repository fallback <<<\n"
    )
    monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    update.update(target)
    assert not (target / "AGENTS.override.md").exists()
    assert not (target / "CLAUDE.local.md").exists()
    assert exclude.read_text() == before + "/AGENTS.override.md\n/CLAUDE.local.md\n"
    assert git(target, "status", "--porcelain") == ""


def test_install_refuses_linked_local_settings_that_run_the_old_copy(
    installer: ModuleType, tmp_path: Path
) -> None:
    root = tmp_path / "project"
    root.mkdir()
    repository(root)
    (root / ".agents/hard-eng/current").mkdir(parents=True)
    shared = tmp_path / "settings.local.json"
    command = "bash .agents/hard-eng/current/scripts/hooks/agent-hook.sh"
    shared.write_text(
        json.dumps({"hooks": {"Stop": [{"hooks": [{"command": command}]}]}})
    )
    (root / ".claude").mkdir()
    (root / ".claude/settings.local.json").symlink_to(shared)
    with pytest.raises(ValueError, match="settings.local.json"):
        installer.install(root)
    assert (root / ".agents/hard-eng/current").is_dir()


def test_candidate_ignores_base_changes_the_branch_lacks(
    release: tuple[Path, Path, str],
) -> None:
    source, target, _ = release
    commit(source, "verified source candidate")
    (target / "package.json").unlink()
    config = json.loads((target / "hard-eng.gates.json").read_text())
    config["shared"][0]["command"] = ["python3", "-c", "raise SystemExit(0)"]
    (target / "hard-eng.gates.json").write_text(json.dumps(config))
    shared = target / "shared.py"
    shared.write_text("# one\n# two\n# three\nVALUE = 1\n")
    git(target, "branch", "-M", "main")
    commit(target, "remote baseline")
    remote = target.parent / "remote.git"
    git(target, "clone", "--bare", str(target), str(remote))
    git(target, "remote", "add", "origin", str(remote))
    git(target, "switch", "-c", "feature/update")
    git(target, "switch", "main")
    shared.write_text("VALUE = 2\n")
    commit(target, "base moves on")
    git(target, "push", "-q", "--no-verify", "origin", "main")
    git(target, "switch", "feature/update")
    changes: dict[str, str | None] = {"new-managed.mjs": "export const value = 1;\n"}
    update.verify_candidate(target, source, changes, {}, target.parent / "candidate")
