"""Setup adopting existing repositories: old generations, repair and project formatters."""

import json
import shutil
import subprocess
from pathlib import Path
from types import ModuleType
from unittest.mock import Mock

import pytest
import update
from conftest import commit, git
from gate_config import json_file
from test_setup import repository
from test_updates import select_release

OLD_COMMAND = 'bash "$(env -u GIT_DIR git rev-parse --show-toplevel)/.hard-eng/{}" {}'
OLD_FILES = {
    ".hard-eng/bootstrap.sh": "#!/usr/bin/env bash\n# Generated by Hard Eng. Fetches the newest Hard Eng.\n",
    ".hard-eng/hook.sh": "#!/usr/bin/env bash\n# Generated by Hard Eng. Runs the repository copy.\n",
    "AGENTS.override.md": "<!-- Generated by Hard Eng for Codex: rules. -->\n\n# Old rules\n",
    ".github/instructions/hard-eng.instructions.md": '---\napplyTo: "**"\n---\n\n'
    "<!-- Generated by Hard Eng from .agents/hard-eng/current/AGENTS.md. -->\n\n# Old\n",
}


def write_old_generation(root: Path) -> dict[str, str]:
    """Write the previous generation's wiring beside project-owned files."""
    for name, content in OLD_FILES.items():
        (root / name).parent.mkdir(parents=True, exist_ok=True)
        (root / name).write_text(content)
    project = {
        ".github/copilot-instructions.md": "Project Copilot rules\n",
        ".github/instructions/project.instructions.md": "Project rules\n",
    }
    for name, content in project.items():
        (root / name).write_text(content)
    handler = {"type": "command", "command": "project-guard"}
    for agent, name in (
        ("claude", ".claude/settings.json"),
        ("codex", ".codex/hooks.json"),
    ):
        (root / name).parent.mkdir(exist_ok=True)
        (root / name).write_text(
            json.dumps(
                {
                    "hooks": {
                        "SessionStart": [
                            {
                                "matcher": "startup|resume",
                                "hooks": [
                                    {
                                        "type": "command",
                                        "command": OLD_COMMAND.format(
                                            "bootstrap.sh", agent
                                        ),
                                    }
                                ],
                            }
                        ],
                        "PreToolUse": [
                            {
                                "hooks": [
                                    {
                                        "type": "command",
                                        "command": OLD_COMMAND.format(
                                            "hook.sh", agent + " pretooluse"
                                        ),
                                    },
                                    handler,
                                ]
                            }
                        ],
                    }
                }
            )
        )
    (root / ".github/hooks").mkdir(parents=True, exist_ok=True)
    (root / ".github/hooks/hard-eng.json").write_text(
        json.dumps(
            {
                "version": 1,
                "hooks": {
                    "sessionStart": [
                        {
                            "type": "command",
                            "bash": OLD_COMMAND.format("bootstrap.sh", "copilot"),
                        }
                    ],
                    "preToolUse": [
                        {
                            "type": "command",
                            "bash": OLD_COMMAND.format("hook.sh", "copilot pretooluse"),
                        }
                    ],
                },
            }
        )
    )
    (root / ".hard-eng/sessions").mkdir(parents=True, exist_ok=True)
    (root / ".hard-eng/sessions/current.json").write_text("{}\n")
    return project


def assert_old_generation_retired(root: Path, project: dict[str, str]) -> None:
    for name in OLD_FILES:
        assert not (root / name).exists(), name
    for name, content in project.items():
        assert (root / name).read_text() == content
    assert (root / ".hard-eng/sessions/current.json").is_file()
    for name in (
        ".claude/settings.json",
        ".codex/hooks.json",
        ".github/hooks/hard-eng.json",
    ):
        assert ".hard-eng/" not in (root / name).read_text(), name
    for name in (".claude/settings.json", ".codex/hooks.json"):
        (group,) = json.loads((root / name).read_text())["hooks"]["PreToolUse"]
        assert group == {"hooks": [{"type": "command", "command": "project-guard"}]}


@pytest.mark.parametrize("tracked", [True, False])
def test_install_retires_old_generation_and_keeps_project_files(
    installer: ModuleType,
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
    tracked: bool,
) -> None:
    repository(tmp_path)
    project = write_old_generation(tmp_path)
    if tracked:
        subprocess.run(["git", "add", "."], cwd=tmp_path, check=True)
        subprocess.run(
            [
                "git",
                "-c",
                "user.name=Fixture",
                "-c",
                "user.email=fixture@example.invalid",
                "commit",
                "-qm",
                "old",
            ],
            cwd=tmp_path,
            check=True,
        )
    else:
        (tmp_path / ".git/info/exclude").write_text("\n".join(OLD_FILES) + "\n")
    installer.install(tmp_path)
    if not tracked:
        assert all((tmp_path / name).exists() for name in OLD_FILES)
        assert "Kept uncommitted old Hard Eng files" in capsys.readouterr().err
        return
    assert_old_generation_retired(tmp_path, project)
    tracked_names = subprocess.check_output(
        ["git", "ls-files"], cwd=tmp_path, text=True
    ).split()
    assert not set(OLD_FILES) & set(tracked_names)
    assert ".hard-eng/" not in (tmp_path / "hard-eng.gates.json").read_text()


def test_install_keeps_edited_old_generation_files_and_reports_them(
    installer: ModuleType, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    repository(tmp_path)
    edited = {name: "Local notes\n" + content for name, content in OLD_FILES.items()}
    for name, content in edited.items():
        (tmp_path / name).parent.mkdir(parents=True, exist_ok=True)
        (tmp_path / name).write_text(content)
    installer.install(tmp_path)
    for name, content in edited.items():
        assert (tmp_path / name).read_text().endswith(content)
    reported = capsys.readouterr().err
    for name in OLD_FILES:
        assert name in reported


@pytest.mark.parametrize("committed", [True, False])
def test_setup_rerun_restores_missing_installed_files(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch, committed: bool
) -> None:
    _, target, _ = release
    gates = (target / "hard-eng.gates.json").read_bytes()
    shutil.rmtree(target / ".agents")
    if committed:
        git(target, "commit", "-qam", "remove installed skills")
    monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    assert "available." in update.update(target)
    assert not (target / ".agents").exists()
    message = update.update(target, repair=True)
    assert ".agents/skills/he/" in message
    assert (target / ".claude/skills/he/SKILL.md").is_file()
    assert (target / "hard-eng.gates.json").read_bytes() == gates
    assert (target / "project.txt").read_text() == "original\n"
    assert git(target, "status", "--porcelain") == ""


def test_setup_rerun_retires_old_generation(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch
) -> None:
    _, target, _ = release
    project = write_old_generation(target)
    git(target, "add", "--force", *OLD_FILES)
    commit(target, "old generation wiring")
    monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    update.update(target, repair=True)
    assert not set(OLD_FILES) & set(git(target, "ls-files").splitlines())
    assert_old_generation_retired(target, project)
    assert git(target, "status", "--porcelain") == ""


@pytest.mark.parametrize(
    ("options", "edited"), [([], False), (["--external-sources"], False), ([], True)]
)
@pytest.mark.parametrize("repair", [False, True])
def test_update_retires_old_generation(
    release: tuple[Path, Path, str],
    monkeypatch: pytest.MonkeyPatch,
    repair: bool,
    options: list[str],
    edited: bool,
) -> None:
    source, target, _ = release
    project = write_old_generation(target)
    gates = target / "hard-eng.gates.json"
    config = json.loads(gates.read_text().replace("raise SystemExit(1)", "None"))
    scripts = [".hard-eng/bootstrap.sh", ".hard-eng/hook.sh"]
    config["shared"].append(
        {
            "name": "shellcheck",
            "role": "shell",
            "command": ["shellcheck", *options, "--", *scripts],
        }
    )
    gates.write_text(json.dumps(config))
    (target / "package.json").unlink()
    git(target, "add", "--force", *OLD_FILES)
    commit(target, "old generation wiring")
    if edited:
        with (target / scripts[1]).open("a") as script:
            script.write("echo local\n")
    if repair:
        monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    else:
        select_release(source, monkeypatch)
    update.update(target, repair=repair)
    if edited:
        shell = [gate["command"] for gate in json.loads(gates.read_text())["shared"]]
        assert ["shellcheck", "--", scripts[1]] in shell
        assert (target / scripts[1]).read_text().endswith("echo local\n")
        assert not (target / scripts[0]).exists()
        return
    assert not set(OLD_FILES) & set(git(target, "ls-files").splitlines())
    assert_old_generation_retired(target, project)
    assert ".hard-eng/" not in gates.read_text()
    assert "shellcheck" not in gates.read_text()


@pytest.mark.parametrize(
    ("config", "opening"),
    [
        ("{}\n", "{\n\t"),
        (
            (
                '{\n  // project style\n  "formatter": {"indentStyle": "space",},\n'
                '  "json": {"formatter": {"indentWidth": 4}}\n}\n'
            ),
            "{\n    ",
        ),
    ],
)
def test_setup_json_stays_in_the_project_biome_layout(
    installer: ModuleType, tmp_path: Path, config: str, opening: str
) -> None:
    repository(tmp_path)
    (tmp_path / "index.js").write_text("export {};\n")
    (tmp_path / "biome.jsonc").write_text(config)
    changes = installer.plan_install(tmp_path.resolve())[0]
    shipped = ".agents/biome.json"
    assert changes[shipped] == (installer.SOURCE / shipped).read_text()
    written = {
        name: text
        for name, text in changes.items()
        if name.endswith(".json") and not name.startswith(".agents/")
    }
    assert {".mcp.json", ".hooks/hard-eng-source.json", "tsconfig.json"} <= set(written)
    for text in written.values():
        assert text == json_file(tmp_path, json.loads(text))
        assert text.startswith(opening)


def test_setup_rerun_leaves_local_settings_edits_uncommitted(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch
) -> None:
    _, target, _ = release
    write_old_generation(target)
    git(target, "add", "--force", *OLD_FILES)
    commit(target, "old generation wiring")
    settings = target / ".claude/settings.json"
    edited = json.loads(settings.read_text())
    edited["permissions"] = {"allow": ["Bash(ls)"]}
    settings.write_text(json.dumps(edited))
    override = target / "AGENTS.override.md"
    override.write_text(override.read_text() + "Local deployment rule\n")
    monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    update.update(target, repair=True)
    assert override.read_text().endswith("Local deployment rule\n")
    assert "permissions" not in git(target, "show", "HEAD:.claude/settings.json")
    assert "permissions" in settings.read_text()


def test_install_keeps_compound_project_hooks_and_the_script_they_run(
    installer: ModuleType, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    repository(tmp_path)
    write_old_generation(tmp_path)
    settings = tmp_path / ".claude/settings.json"
    current = json.loads(settings.read_text())
    compound = {
        "type": "command",
        "command": OLD_COMMAND.format("hook.sh", "claude pretooluse") + " && ./guard",
    }
    generated = {
        "type": "command",
        "command": 'bash "$(git rev-parse --show-toplevel)/.hard-eng/hook.sh" claude',
    }
    relative = {
        "type": "command",
        "command": "bash .hard-eng/bootstrap.sh claude && ./guard",
    }
    current["hooks"]["PreToolUse"][0]["hooks"] += [compound, relative, generated]
    settings.write_text(json.dumps(current))
    git(tmp_path, "add", "--force", ".")
    commit(tmp_path, "old generation wiring")
    installer.install(tmp_path)
    (group,) = json.loads(settings.read_text())["hooks"]["PreToolUse"]
    project = {"type": "command", "command": "project-guard"}
    assert group["hooks"] == [project, compound, relative]
    assert (tmp_path / ".hard-eng/hook.sh").is_file()
    assert (tmp_path / ".hard-eng/bootstrap.sh").is_file()
    assert not (tmp_path / "AGENTS.override.md").exists()
    assert ".hard-eng/bootstrap.sh" in capsys.readouterr().err
