"""Setup adopting existing repositories: old generations, repair and project formatters."""

import json
import shutil
import subprocess
from pathlib import Path
from types import ModuleType
from unittest.mock import Mock

import pytest
import update
from conftest import commit, git, init
from gate_config import json_file
from test_setup import repository, snapshot
from test_updates import select_release

OLD_COMMAND = 'bash "$(env -u GIT_DIR git rev-parse --show-toplevel)/.hard-eng/{}" {}'
OLD_FILES = {
    ".hard-eng/bootstrap.sh": "#!/usr/bin/env bash\n# Generated by Hard Eng. Fetches the newest Hard Eng.\n",
    ".hard-eng/hook.sh": "#!/usr/bin/env bash\n# Generated by Hard Eng. Runs the repository copy.\n",
    "AGENTS.override.md": "<!-- Generated by Hard Eng for Codex: rules. -->\n\n# Old rules\n",
    ".github/instructions/hard-eng.instructions.md": '---\napplyTo: "**"\n---\n\n'
    "<!-- Generated by Hard Eng from .agents/hard-eng/current/AGENTS.md. -->\n\n# Old\n",
}


@pytest.mark.parametrize("custom_suite", [False, True])
def test_install_preserves_reviewed_performance_exception(
    installer: ModuleType, tmp_path: Path, custom_suite: bool
) -> None:
    repository(tmp_path)
    config = installer.gate_config(tmp_path)
    package = config["packages"][0]
    assert "performance_exception" not in package
    performance = next(
        gate for gate in package["checks"] if gate.get("role") == "performance"
    )
    if custom_suite:
        performance["command"] = ["node", "project-budget.js"]
    else:
        package["checks"].remove(performance)
    reason = "Reviewed scalar conversion owner; no justified workload budget. Revisit for bulk operations."
    package["performance_exception"] = reason
    target = tmp_path / "hard-eng.gates.json"
    target.write_text(json.dumps(config))
    installer.install(tmp_path)
    installed = json.loads(target.read_text())["packages"][0]
    assert installed["performance_exception"] == reason
    assert [
        gate for gate in installed["checks"] if gate.get("role") == "performance"
    ] == ([performance] if custom_suite else [])
    before = snapshot(tmp_path)
    installer.install(tmp_path)
    assert snapshot(tmp_path) == before


@pytest.mark.parametrize(
    ("scripts", "kept"),
    [
        ({"typecheck": "tsc --noEmit"}, False),
        ({"typecheck": "tsc --noEmit", "pretypecheck": "node generate.js"}, True),
        ({"typecheck": "tsc -p tsconfig.app.json --noEmit"}, True),
    ],
)
def test_setup_keeps_only_a_distinct_project_typecheck(
    installer: ModuleType, tmp_path: Path, scripts: dict[str, str], kept: bool
) -> None:
    repository(tmp_path)
    (tmp_path / "package.json").write_text(json.dumps({"scripts": scripts}))
    wrapper = {"name": "project-typecheck", "role": "project-typecheck"}

    def planned() -> list[object]:
        config = json.loads(installer.plan_install(tmp_path)[0]["hard-eng.gates.json"])
        return [
            gate
            for gate in config["packages"][0]["checks"]
            if wrapper.items() <= gate.items()
        ]

    assert bool(planned()) is kept
    config = installer.gate_config(tmp_path)
    config["packages"][0]["checks"].append(
        {**wrapper, "command": ["npm", "run", "typecheck"]}
    )
    (tmp_path / "hard-eng.gates.json").write_text(json.dumps(config))
    assert bool(planned()) is kept


@pytest.mark.parametrize("suffix", ["", "\n", "\nKeep project instructions.\n"])
def test_managed_instruction_update_preserves_native_scaffold_proof(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch, suffix: str
) -> None:
    source, target, _ = release
    instructions = target / "AGENTS.md"
    instructions.write_text(instructions.read_text().rstrip("\n") + "\n" + suffix)
    git(target, "add", "AGENTS.md")
    git(target, "commit", "--allow-empty", "-qm", "existing instruction separator")
    base = git(target, "rev-parse", "HEAD")
    guide = source / "AGENTS.md"
    guide.write_text(guide.read_text() + "\nUpdated managed fixture guidance.\n")
    select_release(source, monkeypatch)
    assert "Updated Hard Eng" in update.update(target)
    git(target, "diff", "--check", base)
    monkeypatch.setattr(update, "verified_revision", Mock(return_value=True))
    assert update.check_scaffold_update(target, base)
    if suffix.strip():
        instructions.write_text(
            instructions.read_text().replace("Keep project", "Edited project")
        )
        assert not update.preserved_instructions(target, base, {"AGENTS.md"})


def write_old_generation(root: Path) -> dict[str, str]:
    """Write the previous generation's wiring beside project-owned files."""
    for name, content in OLD_FILES.items():
        (root / name).parent.mkdir(parents=True, exist_ok=True)
        (root / name).write_text(content)
    project = {
        ".github/copilot-instructions.md": "Project Copilot rules\n",
        ".github/instructions/project.instructions.md": "Project rules\n",
    }
    for name, content in project.items():
        (root / name).write_text(content)
    handler = {"type": "command", "command": "project-guard"}
    for agent, name in (
        ("claude", ".claude/settings.json"),
        ("codex", ".codex/hooks.json"),
    ):
        (root / name).parent.mkdir(exist_ok=True)
        (root / name).write_text(
            json.dumps(
                {
                    "hooks": {
                        "SessionStart": [
                            {
                                "matcher": "startup|resume",
                                "hooks": [
                                    {
                                        "type": "command",
                                        "command": OLD_COMMAND.format(
                                            "bootstrap.sh", agent
                                        ),
                                    }
                                ],
                            }
                        ],
                        "PreToolUse": [
                            {
                                "hooks": [
                                    {
                                        "type": "command",
                                        "command": OLD_COMMAND.format(
                                            "hook.sh", agent + " pretooluse"
                                        ),
                                    },
                                    handler,
                                ]
                            }
                        ],
                    }
                }
            )
        )
    (root / ".github/hooks").mkdir(parents=True, exist_ok=True)
    (root / ".github/hooks/hard-eng.json").write_text(
        json.dumps(
            {
                "version": 1,
                "hooks": {
                    "sessionStart": [
                        {
                            "type": "command",
                            "bash": OLD_COMMAND.format("bootstrap.sh", "copilot"),
                        }
                    ],
                    "preToolUse": [
                        {
                            "type": "command",
                            "bash": OLD_COMMAND.format("hook.sh", "copilot pretooluse"),
                        }
                    ],
                },
            }
        )
    )
    (root / ".hard-eng/sessions").mkdir(parents=True, exist_ok=True)
    (root / ".hard-eng/sessions/current.json").write_text("{}\n")
    return project


def assert_old_generation_retired(root: Path, project: dict[str, str]) -> None:
    for name in OLD_FILES:
        assert not (root / name).exists(), name
    for name, content in project.items():
        assert (root / name).read_text() == content
    assert (root / ".hard-eng/sessions/current.json").is_file()
    assert not (root / ".github/hooks/hard-eng.json").exists()
    for name in (".claude/settings.json", ".codex/hooks.json"):
        assert ".hard-eng/" not in (root / name).read_text(), name
    for name in (".claude/settings.json", ".codex/hooks.json"):
        (group,) = json.loads((root / name).read_text())["hooks"]["PreToolUse"]
        assert group == {"hooks": [{"type": "command", "command": "project-guard"}]}


@pytest.mark.parametrize("tracked", [True, False])
def test_install_retires_old_generation_and_keeps_project_files(
    installer: ModuleType, tmp_path: Path, tracked: bool
) -> None:
    repository(tmp_path)
    project = write_old_generation(tmp_path)
    if tracked:
        subprocess.run(["git", "add", "."], cwd=tmp_path, check=True)
        subprocess.run(
            [
                "git",
                "-c",
                "user.name=Fixture",
                "-c",
                "user.email=fixture@example.invalid",
                "commit",
                "-qm",
                "old",
            ],
            cwd=tmp_path,
            check=True,
        )
    else:
        (tmp_path / ".git/info/exclude").write_text("\n".join(OLD_FILES) + "\n")
    installer.install(tmp_path)
    assert_old_generation_retired(tmp_path, project)
    tracked_names = subprocess.check_output(
        ["git", "ls-files"], cwd=tmp_path, text=True
    ).split()
    assert not set(OLD_FILES) & set(tracked_names)
    assert ".hard-eng/" not in (tmp_path / "hard-eng.gates.json").read_text()


def test_install_removes_edited_old_generation_files(
    installer: ModuleType, tmp_path: Path
) -> None:
    repository(tmp_path)
    edited = {name: "Local notes\n" + content for name, content in OLD_FILES.items()}
    for name, content in edited.items():
        (tmp_path / name).parent.mkdir(parents=True, exist_ok=True)
        (tmp_path / name).write_text(content)
    installer.install(tmp_path)
    for name in edited:
        assert not (tmp_path / name).exists(), name


@pytest.mark.parametrize("committed", [True, False])
def test_setup_rerun_restores_missing_installed_files(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch, committed: bool
) -> None:
    _, target, _ = release
    gates = (target / "hard-eng.gates.json").read_bytes()
    shutil.rmtree(target / ".agents")
    if committed:
        git(target, "commit", "-qam", "remove installed skills")
    monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    assert "available." in update.update(target)
    assert not (target / ".agents").exists()
    message = update.update(target, repair=True)
    assert ".agents/skills/he/" in message
    assert (target / ".claude/skills/he/SKILL.md").is_file()
    assert (target / "hard-eng.gates.json").read_bytes() == gates
    assert (target / "project.txt").read_text() == "original\n"
    assert git(target, "status", "--porcelain") == ""


def test_setup_rerun_retires_old_generation(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch
) -> None:
    _, target, _ = release
    project = write_old_generation(target)
    git(target, "add", "--force", *OLD_FILES)
    commit(target, "old generation wiring")
    monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    update.update(target, repair=True)
    assert not set(OLD_FILES) & set(git(target, "ls-files").splitlines())
    assert_old_generation_retired(target, project)
    assert git(target, "status", "--porcelain") == ""


@pytest.mark.parametrize(
    ("repair", "options", "edited"),
    [
        (False, [], False),
        (True, [], False),
        (False, ["--external-sources"], False),
        (True, ["--external-sources"], False),
        (True, [], True),
    ],
)
def test_update_retires_old_generation(
    release: tuple[Path, Path, str],
    monkeypatch: pytest.MonkeyPatch,
    repair: bool,
    options: list[str],
    edited: bool,
) -> None:
    source, target, _ = release
    project = write_old_generation(target)
    gates = target / "hard-eng.gates.json"
    config = json.loads(gates.read_text().replace("raise SystemExit(1)", "None"))
    scripts = [".hard-eng/bootstrap.sh", ".hard-eng/hook.sh"]
    config["shared"].append(
        {
            "name": "shellcheck",
            "role": "shell",
            "command": ["shellcheck", *options, "--", *scripts],
        }
    )
    gates.write_text(json.dumps(config))
    (target / "package.json").unlink()
    git(target, "add", "--force", *OLD_FILES)
    commit(target, "old generation wiring")
    if edited:
        with (target / scripts[1]).open("a") as script:
            script.write("echo local\n")
    if repair:
        monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    else:
        select_release(source, monkeypatch)
    update.update(target, repair=repair)
    tracked = set(git(target, "ls-files").splitlines())
    assert edited or not set(OLD_FILES) & tracked
    assert_old_generation_retired(target, project)
    assert ".hard-eng/" not in gates.read_text()
    assert "shellcheck" not in gates.read_text()


@pytest.mark.parametrize(
    ("config", "opening"),
    [
        ("{}\n", "{\n\t"),
        (
            (
                '{\n  // project style\n  "formatter": {"indentStyle": "space",},\n'
                '  "json": {"formatter": {"indentWidth": 4}}\n}\n'
            ),
            "{\n    ",
        ),
    ],
)
def test_setup_json_stays_in_the_project_biome_layout(
    installer: ModuleType, tmp_path: Path, config: str, opening: str
) -> None:
    repository(tmp_path)
    (tmp_path / "index.js").write_text("export {};\n")
    (tmp_path / "biome.jsonc").write_text(config)
    changes = installer.plan_install(tmp_path.resolve())[0]
    shipped = ".agents/biome.json"
    assert changes[shipped] == (installer.SOURCE / shipped).read_text()
    written = {
        name: text
        for name, text in changes.items()
        if name.endswith(".json") and not name.startswith(".agents/")
    }
    assert {".hooks/hard-eng-source.json", "tsconfig.json"} <= set(written)
    for text in written.values():
        assert text == json_file(tmp_path, json.loads(text))
        assert text.startswith(opening)


def test_setup_rerun_leaves_local_settings_edits_uncommitted(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch
) -> None:
    _, target, _ = release
    write_old_generation(target)
    git(target, "add", "--force", *OLD_FILES)
    commit(target, "old generation wiring")
    settings = target / ".claude/settings.json"
    edited = json.loads(settings.read_text())
    edited["permissions"] = {"allow": ["Bash(ls)"]}
    settings.write_text(json.dumps(edited))
    override = target / "AGENTS.override.md"
    override.write_text(override.read_text() + "Local deployment rule\n")
    monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    update.update(target, repair=True)
    assert not override.exists()
    assert "permissions" not in git(target, "show", "HEAD:.claude/settings.json")
    assert "permissions" in settings.read_text()


def test_install_preserves_custom_retired_hooks_until_supported_migration(
    installer: ModuleType, tmp_path: Path
) -> None:
    repository(tmp_path)
    write_old_generation(tmp_path)
    settings = tmp_path / ".claude/settings.json"
    current = json.loads(settings.read_text())
    current["hooks"]["PreToolUse"][0]["hooks"] += [
        {"type": "command", "command": "bash .hard-eng/bootstrap.sh claude"},
    ]
    settings.write_text(json.dumps(current))
    copilot = tmp_path / ".github/hooks/hard-eng.json"
    wiring = json.loads(copilot.read_text())
    wiring["hooks"]["preToolUse"][0]["powershell"] = "./guard.ps1"
    copilot.write_text(json.dumps(wiring))
    policy = tmp_path / ".github/hooks/project-policy.json"
    guard = {"type": "command", "bash": "./guard.sh"}
    old = {"type": "command", "bash": "bash .hard-eng/hook.sh copilot"}
    policy.write_text(json.dumps({"version": 1, "hooks": {"preToolUse": [old, guard]}}))
    git(tmp_path, "add", "--force", ".")
    commit(tmp_path, "old generation wiring")
    original = {path: path.read_bytes() for path in (settings, copilot, policy)}
    with pytest.raises(ValueError, match="Harness migration required"):
        installer.install(tmp_path)
    assert {path: path.read_bytes() for path in original} == original
    assert not (tmp_path / ".hooks").exists()
    migrated = [
        {"type": "command", "command": "./guard.sh"},
        {"type": "command", "command": "powershell -File ./guard.ps1"},
    ]
    current["hooks"]["PreToolUse"][0]["hooks"] += migrated
    settings.write_text(json.dumps(current))
    copilot.unlink()
    policy.unlink()
    installer.install(tmp_path)
    assert ".hard-eng" not in settings.read_text()
    (group,) = json.loads(settings.read_text())["hooks"]["PreToolUse"]
    assert group["hooks"] == [
        {"type": "command", "command": "project-guard"},
        *migrated,
    ]
    assert not (tmp_path / ".hard-eng/hook.sh").exists()


def test_install_retires_a_claude_md_that_only_imports_agents_md(
    installer: ModuleType, tmp_path: Path
) -> None:
    repository(tmp_path)
    (tmp_path / "CLAUDE.md").write_text(
        "<!-- hard-eng:start -->\n@AGENTS.md\n<!-- hard-eng:end -->\n\n"
    )
    git(tmp_path, "add", "CLAUDE.md")
    commit(tmp_path, "Install Hard Eng")
    installer.install(tmp_path)
    assert not (tmp_path / "CLAUDE.md").exists()
    assert "CLAUDE.md" not in git(tmp_path, "ls-files").splitlines()


def test_install_rejects_an_edited_import_only_claude_md(
    installer: ModuleType, tmp_path: Path
) -> None:
    repository(tmp_path)
    (tmp_path / "CLAUDE.md").write_text(
        "<!-- hard-eng:start -->\n@docs/rules.md\n<!-- hard-eng:end -->\n\n"
    )
    with pytest.raises(ValueError, match="CLAUDE.md"):
        installer.install(tmp_path)


@pytest.mark.parametrize("name", ["CLAUDE.md", "CLAUDE.local.md", ".claude/CLAUDE.md"])
def test_install_preserves_blocking_ancestor_instructions_without_a_fallback(
    installer: ModuleType, tmp_path: Path, name: str
) -> None:
    ancestor = tmp_path / name
    ancestor.parent.mkdir(parents=True, exist_ok=True)
    ancestor.write_text("Workspace rules\n")
    root = tmp_path / "project"
    root.mkdir()
    repository(root)
    with pytest.raises(ValueError, match="Ancestor CLAUDE instructions"):
        installer.install(root)
    assert ancestor.read_text() == "Workspace rules\n"
    assert not (root / "CLAUDE.md").exists()
    assert not (root / ".hooks").exists()


def test_install_leaves_old_scripts_behind_a_linked_directory(
    installer: ModuleType, tmp_path: Path
) -> None:
    shared = tmp_path / "shared"
    shared.mkdir()
    (shared / "hook.sh").write_text(OLD_FILES[".hard-eng/hook.sh"])
    root = tmp_path / "project"
    root.mkdir()
    repository(root)
    (root / ".hard-eng").symlink_to(shared, target_is_directory=True)
    installer.install(root)
    assert (shared / "hook.sh").read_text() == OLD_FILES[".hard-eng/hook.sh"]


def test_setup_rerun_preserves_new_claude_rules_for_review(
    release: tuple[Path, Path, str],
    monkeypatch: pytest.MonkeyPatch,
    capfd: pytest.CaptureFixture[str],
) -> None:
    _, target, _ = release
    (target / "CLAUDE.md").write_text("Project rules\n")
    commit(target, "project rules")
    monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    with pytest.raises(subprocess.CalledProcessError):
        update.update(target, repair=True)
    assert (
        "Repository CLAUDE instructions prevent native AGENTS.md loading"
        in capfd.readouterr().err
    )
    assert (target / "CLAUDE.md").read_text() == "Project rules\n"


def test_install_removes_the_old_local_hard_eng_copy(
    installer: ModuleType, tmp_path: Path
) -> None:
    repository(tmp_path)
    payload = tmp_path / ".agents/hard-eng/current"
    (payload / "skills/plain-english").mkdir(parents=True)
    (payload / "skills/plain-english/SKILL.md").write_text("old\n")
    (tmp_path / ".claude/skills").mkdir(parents=True)
    (tmp_path / ".claude/skills/plain-english").symlink_to(
        "../../.agents/hard-eng/current/skills/plain-english"
    )
    (payload / "output-styles").mkdir()
    (payload / "output-styles/plain-english.md").write_text("old\n")
    (tmp_path / ".claude/output-styles").mkdir()
    (tmp_path / ".claude/output-styles/plain-english.md").symlink_to(
        "../../.agents/hard-eng/current/output-styles/plain-english.md"
    )
    (tmp_path / "CLAUDE.local.md").write_text("@.agents/hard-eng/current/AGENTS.md\n")
    old = f"bash {payload}/scripts/hooks/agent-hook.sh claude pretooluse"
    local = {
        "outputStyle": "Plain English",
        "permissions": {"allow": ["Bash(ls)"]},
        "hooks": {
            "PreToolUse": [
                {"hooks": [{"type": "command", "command": old}]},
                {"hooks": [{"type": "command", "command": "bash .hard-eng/hook.sh"}]},
            ]
        },
    }
    (tmp_path / ".claude/settings.local.json").write_text(json.dumps(local))
    (tmp_path / ".codex").mkdir()
    (tmp_path / ".codex/config.toml").write_text(
        'model = "o3"\nproject_doc_max_bytes = 65536 # Generated by Hard Eng\n'
    )
    exclude = tmp_path / ".git/info/exclude"
    exclude.write_text(
        "*.log\n\n# >>> hard-eng repository fallback >>>\n/.agents/hard-eng/\n"
        "/.claude/settings.local.json\n/.claude/output-styles/plain-english.md\n"
        "# <<< hard-eng repository fallback <<<\n"
    )
    installer.install(tmp_path)
    assert not (tmp_path / ".agents/hard-eng").exists()
    assert not (tmp_path / ".claude/skills/plain-english").is_symlink()
    assert not (tmp_path / ".claude/output-styles/plain-english.md").is_symlink()
    assert not (tmp_path / "CLAUDE.local.md").exists()
    assert json.loads((tmp_path / ".claude/settings.local.json").read_text()) == {
        "permissions": {"allow": ["Bash(ls)"]}
    }
    codex = (tmp_path / ".codex/config.toml").read_text()
    assert codex.startswith('model = "o3"\n')
    assert "project_doc_max_bytes" not in codex
    assert exclude.read_text() == (
        "*.log\n\n/.agents/hard-eng/\n/.claude/settings.local.json\n"
        "/.claude/output-styles/plain-english.md\n"
    )
    assert not (tmp_path / "CLAUDE.md").exists()


def test_install_leaves_linked_legacy_folders_untouched(
    installer: ModuleType, tmp_path: Path
) -> None:
    shared = tmp_path / "shared"
    (shared / "agents/hard-eng/current").mkdir(parents=True)
    (shared / "claude").mkdir()
    settings = '{"outputStyle": "Plain English"}'
    (shared / "claude/settings.local.json").write_text(settings)
    root = tmp_path / "project"
    root.mkdir()
    repository(root)
    (root / ".agents").symlink_to(shared / "agents", target_is_directory=True)
    (root / ".claude").symlink_to(shared / "claude", target_is_directory=True)
    with pytest.raises(ValueError, match=r"\.agents|\.claude"):
        installer.install(root)
    assert (shared / "agents/hard-eng/current").is_dir()
    assert (shared / "claude/settings.local.json").read_text() == settings


def test_install_refuses_a_skills_folder_linked_into_another_copy(
    installer: ModuleType, tmp_path: Path
) -> None:
    shared = tmp_path / "other/.agents/hard-eng/current/skills"
    shared.mkdir(parents=True)
    root = tmp_path / "project"
    root.mkdir()
    repository(root)
    (root / ".agents").mkdir()
    (root / ".agents/skills").symlink_to(shared, target_is_directory=True)
    with pytest.raises(ValueError, match="symlink"):
        installer.install(root)
    assert not any(shared.iterdir())


def test_install_keeps_the_old_copy_when_local_settings_are_malformed(
    installer: ModuleType, tmp_path: Path
) -> None:
    repository(tmp_path)
    (tmp_path / ".agents/hard-eng/current").mkdir(parents=True)
    (tmp_path / ".claude").mkdir()
    (tmp_path / ".claude/settings.local.json").write_text("{")
    with pytest.raises(ValueError):
        installer.install(tmp_path)
    assert (tmp_path / ".agents/hard-eng/current").is_dir()


@pytest.mark.parametrize("repair", [True, False])
def test_update_replaces_old_skill_links_and_cleans_local_settings(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch, repair: bool
) -> None:
    _, target, _ = release
    (target / ".agents/hard-eng/current/skills/he").mkdir(parents=True)
    link = target / ".claude/skills/he"
    link.unlink()
    link.symlink_to("../../.agents/hard-eng/current/skills/he")
    local = {
        "hooks": {
            "Stop": [
                {"hooks": [{"type": "command", "command": "bash .hard-eng/hook.sh"}]}
            ]
        }
    }
    (target / ".claude/settings.local.json").write_text(json.dumps(local))
    monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    update.update(target, repair=repair)
    assert link.resolve() == (target / ".agents/skills/he").resolve()
    assert not (target / ".agents/hard-eng").exists()
    assert json.loads((target / ".claude/settings.local.json").read_text()) == {}


def link_skill_into_old_copy(target: Path) -> Path:
    skill = target / ".agents/skills/he"
    (target / ".agents/hard-eng/current/skills").mkdir(parents=True)
    skill.rename(target / ".agents/hard-eng/current/skills/he")
    skill.symlink_to("../hard-eng/current/skills/he", target_is_directory=True)
    with (target / ".git/info/exclude").open("a") as exclude:
        exclude.write(".agents/hard-eng/\n")
    git(target, "add", "--all", ".agents/skills")
    commit(target, "old skill link")
    return skill


@pytest.mark.parametrize("repair", [True, False])
def test_update_replaces_a_skill_folder_linked_into_the_old_copy(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch, repair: bool
) -> None:
    source, target, _ = release
    skill = link_skill_into_old_copy(target)
    if repair:
        monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    else:
        select_release(source, monkeypatch)
    update.update(target, repair=repair)
    assert not skill.is_symlink()
    assert (target / ".claude/skills/he/SKILL.md").is_file()
    assert not (target / ".agents/hard-eng").exists()
    assert git(target, "status", "--porcelain") == ""


def test_install_replaces_older_skill_files_behind_an_old_link(
    installer: ModuleType, tmp_path: Path
) -> None:
    repository(tmp_path)
    old = tmp_path / ".agents/hard-eng/current/skills/he"
    old.mkdir(parents=True)
    (old / "SKILL.md").write_text("older release\n")
    (tmp_path / ".agents/skills").mkdir()
    (tmp_path / ".agents/skills/he").symlink_to("../hard-eng/current/skills/he")
    installer.install(tmp_path)
    skill = tmp_path / ".agents/skills/he/SKILL.md"
    assert not skill.parent.is_symlink()
    assert (
        skill.read_text()
        == (installer.SOURCE / ".agents/skills/he/SKILL.md").read_text()
    )
    assert not (tmp_path / ".agents/hard-eng").exists()


def test_update_checks_local_settings_before_committing(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch
) -> None:
    source, target, _ = release
    (target / ".agents/hard-eng/current").mkdir(parents=True)
    settings = target / ".claude/settings.local.json"
    settings.write_text("{")
    select_release(source, monkeypatch)
    with pytest.raises(subprocess.CalledProcessError):
        update.update(target)
    assert (target / ".agents/hard-eng/current").is_dir()
    assert settings.read_text() == "{"
    settings.write_text('{"outputStyle": "Plain English"}')
    update.update(target)
    assert not (target / ".agents/hard-eng").exists()
    assert json.loads(settings.read_text()) == {}


def test_update_plan_deletes_only_tracked_old_files(
    installer: ModuleType, tmp_path: Path
) -> None:
    repository(tmp_path)
    write_old_generation(tmp_path)
    git(tmp_path, "add", "--force", "AGENTS.override.md")
    git(tmp_path, "commit", "-qm", "tracked old file")
    *_, retired = installer.plan_install(tmp_path)
    assert set(retired) == {"AGENTS.override.md", ".github/hooks/hard-eng.json"}


def test_session_start_removes_untracked_fallback_files(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch
) -> None:
    _, target, _ = release
    (target / "AGENTS.override.md").write_text(OLD_FILES["AGENTS.override.md"])
    (target / "CLAUDE.local.md").write_text("@.agents/hard-eng/current/AGENTS.md\n")
    exclude = target / ".git/info/exclude"
    before = exclude.read_text()
    exclude.write_text(
        before + "# >>> hard-eng repository fallback >>>\n/AGENTS.override.md\n"
        "/CLAUDE.local.md\n# <<< hard-eng repository fallback <<<\n"
    )
    monkeypatch.setattr(update, "latest_verified", Mock(return_value=None))
    update.update(target)
    assert not (target / "AGENTS.override.md").exists()
    assert not (target / "CLAUDE.local.md").exists()
    assert exclude.read_text() == before + "/AGENTS.override.md\n/CLAUDE.local.md\n"
    assert git(target, "status", "--porcelain") == ""


def test_install_refuses_linked_local_settings_that_run_the_old_copy(
    installer: ModuleType, tmp_path: Path
) -> None:
    root = tmp_path / "project"
    root.mkdir()
    repository(root)
    (root / ".agents/hard-eng/current").mkdir(parents=True)
    shared = tmp_path / "settings.local.json"
    command = "bash .agents/hard-eng/current/scripts/hooks/agent-hook.sh"
    shared.write_text(
        json.dumps({"hooks": {"Stop": [{"hooks": [{"command": command}]}]}})
    )
    (root / ".claude").mkdir()
    (root / ".claude/settings.local.json").symlink_to(shared)
    with pytest.raises(ValueError, match="settings.local.json"):
        installer.install(root)
    assert (root / ".agents/hard-eng/current").is_dir()


def test_update_fetches_each_revisions_pinned_skill_submodule(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    canonical, upstream = tmp_path / "canonical", tmp_path / "upstream"
    init(canonical)
    dependency = tmp_path / "dependency"
    init(dependency)
    contract = dependency / "contract.txt"
    contract.write_text("pinned dependency\n")
    commit(dependency, "pinned dependency")
    git(
        canonical,
        "-c",
        "protocol.file.allow=always",
        "submodule",
        "add",
        dependency.as_uri(),
        "dependency",
    )
    contract.write_text("newer dependency\n")
    commit(dependency, "unpinned dependency")
    skill = canonical / "skills/canonical/SKILL.md"
    skill.parent.mkdir(parents=True)
    skill.write_text("first revision\n")
    commit(canonical, "first skill")
    init(upstream)
    git(
        upstream,
        "-c",
        "protocol.file.allow=always",
        "submodule",
        "add",
        canonical.as_uri(),
        ".agents/skill-sources/canonical",
    )
    link = upstream / ".agents/skills/canonical"
    link.parent.mkdir()
    link.symlink_to("../skill-sources/canonical/skills/canonical")
    previous = commit(upstream, "first pin")
    skill.write_text("second revision\n")
    revision = commit(canonical, "second skill")
    module = upstream / ".agents/skill-sources/canonical"
    git(module, "fetch", "origin")
    git(module, "checkout", "--detach", revision)
    current = commit(upstream, "second pin")
    skill.write_text("unpublished revision\n")
    commit(canonical, "unpinned skill")
    monkeypatch.setenv("GIT_CONFIG_COUNT", "2")
    monkeypatch.setenv("GIT_CONFIG_KEY_0", f"url.{upstream.as_uri()}.insteadOf")
    monkeypatch.setenv(
        "GIT_CONFIG_VALUE_0", f"https://github.com/{update.UPSTREAM}.git"
    )
    monkeypatch.setenv("GIT_CONFIG_KEY_1", "protocol.file.allow")
    monkeypatch.setenv("GIT_CONFIG_VALUE_1", "always")
    checkout = tmp_path / "checkout"
    checkout.mkdir()
    source, old = update.fetch_sources(checkout, current, previous)
    name = ".agents/skills/canonical/SKILL.md"
    assert (source / name).read_text() == "second revision\n"
    assert (old / name).read_text() == "first revision\n"
    assert name in update.scaffold_files(source)
    for tree in (source, old):
        module = tree / ".agents/skill-sources/canonical"
        assert (module / "dependency/contract.txt").read_text() == "pinned dependency\n"
        for checkout in (module, module / "dependency"):
            assert git(checkout, "rev-parse", "--is-shallow-repository") == "true"
            assert git(checkout, "rev-list", "--count", "HEAD") == "1"


def test_setup_runs_the_verified_revisions_own_install_step(
    release: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch
) -> None:
    source, target, _ = release
    git(source, "branch", "-M", "main")
    module = source.parent / "component"
    init(module)
    (module / "contract.txt").write_text("pinned")
    commit(module, "pinned component")
    monkeypatch.setenv("GIT_ALLOW_PROTOCOL", "file")
    git(source, "submodule", "add", module.as_uri(), "component")
    (module / "contract.txt").write_text("unpinned")
    commit(module, "later component")
    entry = (source / "setup.sh").read_text()
    installer = source / ".hooks/update.py"
    main_installer = installer.read_text()
    (source / "setup.sh").write_text(entry.replace(", repair=True", ""))
    installer.write_text(
        "import subprocess\nfrom pathlib import Path\n\n"
        "SOURCE_FILE = '.hooks/hard-eng-source.json'\n\n\n"
        "def latest_verified(previous: str) -> None:\n    return None\n\n\n"
        "def update(root: object, repair: bool = False) -> str:\n"
        "    module = Path(__file__).parents[1] / 'component'\n"
        "    assert (module / 'contract.txt').read_text() == 'pinned'\n"
        "    assert subprocess.check_output(['git', '-C', str(module), 'rev-parse', '--is-shallow-repository'], text=True).strip() == 'true'\n"
        "    return 'Verified installer ran.'\n"
    )
    verified = commit(source, "verified installer without repair")
    (source / "setup.sh").write_text(entry)
    installer.write_text(
        main_installer
        + f"\n\ndef latest_verified(previous: str) -> str:\n    return {verified!r}\n"
    )
    commit(source, "main setup passes repair")
    monkeypatch.setenv("UV_OFFLINE", "1")
    result = subprocess.run(
        ["sh"], input=entry, cwd=target, capture_output=True, text=True, check=False
    )
    assert result.returncode == 0, result.stderr
    assert "Verified installer ran." in result.stdout


@pytest.mark.parametrize("separator", [" && ", "\n"])
@pytest.mark.parametrize(
    "name",
    [".claude/settings.json", ".codex/hooks.json", ".claude/settings.local.json"],
)
def test_plan_preserves_compound_legacy_checks_before_writes(
    installer: ModuleType, tmp_path: Path, name: str, separator: str
) -> None:
    repository(tmp_path)
    path = tmp_path / name
    path.parent.mkdir()
    original = json.dumps(
        {
            "hooks": {
                "PreToolUse": [
                    {
                        "hooks": [
                            {
                                "type": "command",
                                "command": "bash .hard-eng/hook.sh claude"
                                + separator
                                + "./project-guard",
                            }
                        ]
                    }
                ]
            }
        }
    )
    path.write_text(original)
    with pytest.raises(ValueError, match="preserve the separate project checks"):
        installer.plan_install(tmp_path)
    assert path.read_text() == original
    assert not (tmp_path / ".hooks").exists()


@pytest.mark.parametrize(
    "reference",
    [
        '".agents/skills/appwrite-backend/scripts/appwrite-schema-guard.mjs"',
        '".agents" / "skills" / "appwrite-backend" / "scripts" / "appwrite-schema-guard.mjs"',
        '".claude/skills/appwrite-backend/scripts/appwrite-schema-guard.mjs"',
    ],
)
def test_appwrite_cli_retirement_preserves_required_project_guard(
    installer: ModuleType,
    release: tuple[Path, Path, str],
    monkeypatch: pytest.MonkeyPatch,
    reference: str,
) -> None:
    from mcp_setup import APPWRITE_CLI_FILES

    source, target, old = release
    previous = target.parent / "previous"
    shutil.copytree(source, previous, symlinks=True)
    git(previous, "restore", "--source", old, "--", ".")
    for name in APPWRITE_CLI_FILES:
        (source / name).unlink(missing_ok=True)
        for tree in (previous, target):
            path = tree / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text("// Previous source-owned file\n")
    monkeypatch.setattr(installer, "SOURCE", source)
    caller = target / "scripts/schema-check.py"
    caller.parent.mkdir()
    caller.write_text(f"from pathlib import Path\nGUARD = Path.cwd() / {reference}\n")
    (target / "history.md").write_text(reference)
    before = snapshot(target)
    with pytest.raises(ValueError, match="schema-check.py references"):
        installer.install(target, previous)
    assert snapshot(target) == before
    git(target, "add", "scripts/schema-check.py")
    status = git(target, "status", "--porcelain")
    with pytest.raises(subprocess.CalledProcessError):
        update.update_plan(target, source, previous)
    assert snapshot(target) == before
    assert git(target, "status", "--porcelain") == status

    producer = target / "scripts/appwrite-schema-guard.mjs"
    producer.write_text("// Project-owned deployment guard\n")
    caller.write_text(
        'from pathlib import Path\nGUARD = Path.cwd() / "scripts" / "appwrite-schema-guard.mjs"\n'
    )
    old_guard = target / APPWRITE_CLI_FILES[1]
    old_guard.write_text("// Local custom guard\n")
    before = snapshot(target)
    with pytest.raises(ValueError, match="Preserve local Appwrite CLI file"):
        installer.install(target, previous)
    assert snapshot(target) == before
    old_guard.write_bytes((previous / APPWRITE_CLI_FILES[1]).read_bytes())
    installer.install(target, previous)
    assert all(not (target / name).exists() for name in APPWRITE_CLI_FILES)
    assert producer.read_text() == "// Project-owned deployment guard\n"
    assert '"scripts" / "appwrite-schema-guard.mjs"' in caller.read_text()
    assert (target / "history.md").read_text() == reference
