"""Generated per-agent files and links for one repository fallback."""

from __future__ import annotations

import json
import re
import shlex
from pathlib import Path

from .errors import ConfigurationError

MAX_SNAPSHOT_BYTES = 1024 * 1024
CODEX_PROJECT_DOC_LIMIT = 32 * 1024
NAME = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
CLAUDE_LOCAL = b"@.agents/hard-eng/current/AGENTS.md\n"
CODEX_NOTE = (
    b"<!-- Generated by Hard Eng for Codex: the repository rules from AGENTS.md followed by the Hard Eng rules "
    b"from .agents/hard-eng/current/AGENTS.md. Edit those files, then rerun "
    b"`npx -y github:sgaabdu4/hard-eng --repo`. -->\n\n"
)
COPILOT_NOTE = (
    b'---\napplyTo: "**"\n---\n\n'
    b"<!-- Generated by Hard Eng from .agents/hard-eng/current/AGENTS.md. Edit that release or rerun "
    b"`npx -y github:sgaabdu4/hard-eng --repo`; do not edit this copy. -->\n\n"
)
CLAUDE_MATCHER = "Bash|Edit|Write|MultiEdit|NotebookEdit|Agent|mcp__.*"
HOOK_FILES = (".codex/hooks.json", ".claude/settings.local.json", ".github/hooks/hard-eng.json")


class HookOwner:
    def __init__(self, path: Path, event: str, hook: dict[str, object], *, nested: bool, settings: dict[str, object]):
        self.path = path
        self.event = event
        self.hook = hook
        self.nested = nested
        self.settings = settings


def load_json(path: Path) -> dict[str, object]:
    if not path.exists():
        return {}
    if path.is_symlink() or not path.is_file():
        raise ConfigurationError(f"provider configuration is not a regular file: {path}")
    if path.stat().st_size > MAX_SNAPSHOT_BYTES:
        raise ConfigurationError(f"provider configuration is too large to compose safely: {path}")
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise ConfigurationError(f"provider configuration is invalid JSON: {path}: {error}") from error
    if not isinstance(value, dict):
        raise ConfigurationError(f"provider configuration must be a JSON object: {path}")
    return value


def _owned_hook(value: object, expected: dict[str, object]) -> bool:
    if not isinstance(value, dict):
        return False
    return any(
        isinstance(expected.get(key), str) and value.get(key) == expected[key]
        for key in ("command", "bash", "powershell")
    )


def _dump(value: dict[str, object]) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True) + "\n").encode()


def _nested_entries(value: dict[str, object], event: str, path: Path) -> tuple[dict[str, object], list[object]]:
    hooks = value.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        raise ConfigurationError(f"hooks must be a JSON object: {path}")
    entries = hooks.setdefault(event, [])
    if not isinstance(entries, list):
        raise ConfigurationError(f"hooks.{event} must be an array: {path}")
    return hooks, entries


def _without_nested(entries: list[object], hook: dict[str, object], path: Path, event: str) -> list[object]:
    kept: list[object] = []
    for entry in entries:
        if not isinstance(entry, dict) or not isinstance(entry.get("hooks"), list):
            raise ConfigurationError(f"hooks.{event} contains an unsupported entry: {path}")
        inner = [item for item in entry["hooks"] if not _owned_hook(item, hook)]
        if inner:
            kept.append({**entry, "hooks": inner})
    return kept


def compose_hook(owner: HookOwner) -> bytes:
    value = load_json(owner.path)
    for key, expected in owner.settings.items():
        if key in value and value[key] != expected:
            raise ConfigurationError(f"{key} has another owner: {owner.path}")
        value[key] = expected
    if owner.nested:
        hooks, entries = _nested_entries(value, owner.event, owner.path)
        kept = _without_nested(entries, owner.hook, owner.path, owner.event)
        if kept == entries:
            hooks[owner.event] = [*entries, {"hooks": [owner.hook]}]
        return _dump(value)
    value["version"] = 1
    hooks, entries = _nested_entries(value, owner.event, owner.path)
    if not all(isinstance(entry, dict) for entry in entries):
        raise ConfigurationError(f"hooks.{owner.event} must be an object array: {owner.path}")
    if not any(_owned_hook(entry, owner.hook) for entry in entries):
        hooks[owner.event] = [*entries, owner.hook]
    return _dump(value)


def strip_hook(owner: HookOwner) -> bytes:
    value = load_json(owner.path)
    for key, expected in owner.settings.items():
        if value.get(key) == expected:
            del value[key]
    hooks, entries = _nested_entries(value, owner.event, owner.path)
    if owner.nested:
        remaining = _without_nested(entries, owner.hook, owner.path, owner.event)
    else:
        remaining = [entry for entry in entries if not _owned_hook(entry, owner.hook)]
    if remaining:
        hooks[owner.event] = remaining
    else:
        del hooks[owner.event]
    if not hooks:
        del value["hooks"]
    return _dump(value)


def _rules(path: Path, label: str) -> bytes:
    if path.is_symlink() or not path.is_file():
        raise ConfigurationError(f"{label} must be a regular file: {path}")
    if path.stat().st_size > MAX_SNAPSHOT_BYTES:
        raise ConfigurationError(f"{label} is too large to compose: {path}")
    raw = path.read_bytes()
    if not raw.strip():
        raise ConfigurationError(f"{label} is empty: {path}")
    return raw


def codex_override(repository: Path, payload: Path) -> bytes:
    repository_rules = _rules(repository / "AGENTS.md", "repository AGENTS.md")
    hard_eng_rules = _rules(payload / "AGENTS.md", "Hard Eng AGENTS.md")
    composed = CODEX_NOTE + repository_rules.rstrip(b"\n") + b"\n\n" + hard_eng_rules
    if len(composed) > CODEX_PROJECT_DOC_LIMIT:
        raise ConfigurationError(
            f"Codex reads at most {CODEX_PROJECT_DOC_LIMIT} bytes of repository instructions; AGENTS.md "
            f"({len(repository_rules)} bytes) plus the Hard Eng rules ({len(hard_eng_rules)} bytes) exceed it. "
            "Shorten AGENTS.md or install Hard Eng globally with `npx -y github:sgaabdu4/hard-eng --global`."
        )
    return composed


def copilot_instructions(payload: Path) -> bytes:
    return COPILOT_NOTE + _rules(payload / "AGENTS.md", "Hard Eng AGENTS.md")


def hook_owners(repository: Path, payload: Path) -> tuple[HookOwner, ...]:
    command = f"bash {shlex.quote(str(payload / 'scripts/hooks/agent-hook.sh'))}"
    return (
        HookOwner(
            repository / ".codex/hooks.json",
            "PreToolUse",
            {"command": f"{command} codex pretooluse", "timeout": 2, "type": "command"},
            nested=True,
            settings={},
        ),
        HookOwner(
            repository / ".claude/settings.local.json",
            "PreToolUse",
            {"matcher": CLAUDE_MATCHER, "command": f"{command} claude pretooluse", "type": "command"},
            nested=True,
            settings={"outputStyle": "Plain English"},
        ),
        HookOwner(
            repository / ".github/hooks/hard-eng.json",
            "preToolUse",
            {"bash": f"{command} copilot pretooluse", "timeoutSec": 2, "type": "command"},
            nested=False,
            settings={},
        ),
    )


def exclusive_files(repository: Path) -> tuple[Path, ...]:
    return (
        repository / "AGENTS.override.md",
        repository / "CLAUDE.local.md",
        repository / ".github/instructions/hard-eng.instructions.md",
    )


def composable_files(repository: Path) -> set[Path]:
    return {repository / relative for relative in HOOK_FILES}


def expected_files(repository: Path, payload: Path) -> dict[Path, tuple[bytes, int]]:
    files: dict[Path, tuple[bytes, int]] = {
        repository / "AGENTS.override.md": (codex_override(repository, payload), 0o644),
        repository / "CLAUDE.local.md": (CLAUDE_LOCAL, 0o644),
        repository / ".github/instructions/hard-eng.instructions.md": (copilot_instructions(payload), 0o644),
    }
    for owner in hook_owners(repository, payload):
        files[owner.path] = (compose_hook(owner), 0o600)
    return files


def _skills(payload: Path) -> list[str]:
    root = payload / "skills"
    if root.is_symlink() or not root.is_dir():
        raise ConfigurationError("fallback release skills directory is missing")
    names = sorted(path.name for path in root.iterdir() if path.is_dir() and (path / "SKILL.md").is_file())
    if "plain-english" not in names:
        raise ConfigurationError("fallback release is missing the plain-english skill")
    return names


def expected_links(repository: Path, payload: Path) -> dict[Path, Path]:
    links: dict[Path, Path] = {}
    for name in _skills(payload):
        target = payload / "skills" / name
        links[repository / ".agents/skills" / name] = target
        links[repository / ".claude/skills" / name] = target
    agents = payload / "agents"
    if agents.is_dir() and not agents.is_symlink():
        adapters = {
            "claude.md": (repository / ".claude/agents", ".md"),
            "codex.toml": (repository / ".codex/agents", ".toml"),
            "copilot.agent.md": (repository / ".github/agents", ".agent.md"),
        }
        for package in sorted(agents.iterdir()):
            if not package.is_dir() or package.is_symlink() or not NAME.fullmatch(package.name):
                continue
            for source_name, (destination, suffix) in adapters.items():
                source = package / source_name
                if source.is_file() and not source.is_symlink():
                    links[destination / f"{package.name}{suffix}"] = source
    styles = payload / "output-styles"
    if styles.is_dir() and not styles.is_symlink():
        for source in sorted(styles.glob("*.md")):
            if source.is_file() and not source.is_symlink():
                links[repository / ".claude/output-styles" / source.name] = source
    return links
