"""Shared wiring: the committed bootstrap and guard shim that give every clone the newest Hard Eng."""

from __future__ import annotations

import json
import os
import stat
from pathlib import Path

from . import SUPPORTED_AGENTS
from .errors import ConfigurationError, FetchError
from .jsonstyle import render, style_for
from .source import Checkout, SourceError, local_root, read_checkout, refresh

GENERATED = "Generated by Hard Eng"
BOOTSTRAP = ".hard-eng/bootstrap.sh"
SHIM = ".hard-eng/hook.sh"
GLOBAL_GUARD = ".agents/hard-eng/global-guard"
SHARED_POLICY = {"schema_version": 1, "wiring": "shared"}
BOOTSTRAP_HEADER = r"""#!/usr/bin/env bash
# Generated by Hard Eng. Fetches the newest Hard Eng into .agents/hard-eng, then prepares this checkout.
# Usage: bootstrap.sh <claude|codex|copilot>   at session start
#        bootstrap.sh download                 fetch or refresh only
set -euo pipefail
mode=${1:?usage: bootstrap.sh <claude|codex|copilot|download>}
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
if ! command -v python3 >/dev/null 2>&1 || ! python3 -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 12) else 1)'; then
  echo "hard-eng bootstrap: python3 3.12 or newer is required" >&2
  exit 1
fi
if ! command -v git >/dev/null 2>&1; then
  echo "hard-eng bootstrap: git is required" >&2
  exit 1
fi
export PYTHONDONTWRITEBYTECODE=1
exec python3 - "$root" "$mode" <<'PY'
"""
BOOTSTRAP_SCRIPT = BOOTSTRAP_HEADER + Path(__file__).with_name("source.py").read_text(encoding="utf-8") + "PY\n"
SHIM_SCRIPT = r"""#!/usr/bin/env bash
# Generated by Hard Eng. Runs the repository copy of Hard Eng, or denies tool calls until it is fetched.
set -u
agent=${1:-}
event=${2:-}
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
cache=$root/.agents/hard-eng
if [ -f "$cache/global-guard" ] && grep -qx -- "$agent" "$cache/global-guard"; then
  exit 0
fi
guard=$cache/current/scripts/hooks/agent-hook.sh
if [ -f "$guard" ]; then
  exec bash "$guard" "$@"
fi
case $event in
  posttooluse|stop) exit 0 ;;
esac
detail=""
bootstrap=$root/.hard-eng/bootstrap.sh
if [ -f "$bootstrap" ]; then
  heal=$(bash "$bootstrap" download 2>&1 >/dev/null)
  printf '%s\n' "$heal" >&2
  if [ -f "$guard" ]; then
    exec bash "$guard" "$@"
  fi
  detail=$(printf '%s\n' "$heal" | tail -n1 | tr -d '\000-\037' | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')
fi
reason="Hard Eng is not downloaded for this repository yet, so this tool call was denied. Run: bash .hard-eng/bootstrap.sh $agent"
[ -n "$detail" ] && reason="$reason ($detail)"
if [ "$agent" = copilot ]; then
  printf '{"permissionDecision":"deny","permissionDecisionReason":"%s"}' "$reason"
else
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}' "$reason"
fi
"""


def replace_file(path: Path, raw: bytes, mode: int) -> None:
    if path.is_symlink() or (path.exists() and not path.is_file()):
        raise ConfigurationError(f"refusing to replace unsafe path: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    descriptor = os.open(temporary, os.O_CREAT | os.O_EXCL | os.O_WRONLY, mode)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(raw)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        os.chmod(path, mode)
    except BaseException:
        if temporary.is_file() and not temporary.is_symlink():
            temporary.unlink()
        raise


def write_policy(root: Path, *, shared: bool) -> None:
    """Record or clear the shared wiring in hard-eng.gates.json, keeping every other key."""
    marker = root / "hard-eng.gates.json"
    try:
        value = json.loads(marker.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise ConfigurationError(f"hard-eng.gates.json could not be read: {error}") from error
    if not isinstance(value, dict):
        raise ConfigurationError("hard-eng.gates.json must be a JSON object")
    if shared:
        value["hard_eng"] = dict(SHARED_POLICY)
    else:
        value.pop("hard_eng", None)
    replace_file(marker, render(value, style_for(marker)).encode(), stat.S_IMODE(marker.stat().st_mode))


def ensure_checkout(root: Path, *, fetch: bool) -> Checkout:
    """The repository copy of Hard Eng; clone or refresh it when asked or when none is usable."""
    try:
        if not fetch:
            checkout = read_checkout(local_root(root))
            if checkout is not None:
                return checkout
        return refresh(root)
    except SourceError as error:
        raise FetchError(str(error)) from error


def global_guard_agents(root: Path) -> set[str]:
    path = root / GLOBAL_GUARD
    if path.is_symlink() or not path.is_file():
        return set()
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeError):
        return set()
    return {line.strip() for line in lines if line.strip() in SUPPORTED_AGENTS}


def set_global_guard(root: Path, agent: str, deferring: bool) -> None:
    """Record whether the shim should stand aside for this agent because the global guard already runs."""
    agents = global_guard_agents(root)
    updated = agents | {agent} if deferring else agents - {agent}
    path = root / GLOBAL_GUARD
    if updated == agents and (path.is_file() or not updated):
        return
    if not updated:
        if path.is_file() and not path.is_symlink():
            path.unlink()
        return
    replace_file(path, "".join(f"{name}\n" for name in sorted(updated)).encode(), 0o600)
