"""Shared wiring: one committed release pin, bootstrap, and guard shim that every clone can use."""

from __future__ import annotations

import json
import os
import stat
import subprocess
import tempfile
from pathlib import Path

from . import SUPPORTED_AGENTS
from .errors import ConfigurationError, ReleaseError
from .jsonstyle import render, style_for
from .models import MarkerPolicy, ReleasePin
from .release import (
    STATE_SCHEMA,
    ActiveRelease,
    activate,
    activation_lock,
    download_release,
    file_sha,
    payload_health,
    read_current,
    require_runtime,
    select_release,
    tree_digest,
    validate_manifest,
)

GENERATED = "Generated by Hard Eng"
BOOTSTRAP = ".hard-eng/bootstrap.sh"
SHIM = ".hard-eng/hook.sh"
GLOBAL_GUARD = ".agents/hard-eng/global-guard"
BOOTSTRAP_TIMEOUT_SECONDS = 600
BOOTSTRAP_SCRIPT = r"""#!/usr/bin/env bash
# Generated by Hard Eng. Downloads the release pinned in hard-eng.gates.json, then prepares this checkout.
# Usage: bootstrap.sh <claude|codex|copilot>   at session start
#        bootstrap.sh download                 download and verify only
set -euo pipefail
mode=${1:?usage: bootstrap.sh <claude|codex|copilot|download>}
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
if ! command -v python3 >/dev/null 2>&1 || ! python3 -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 12) else 1)'; then
  echo "hard-eng bootstrap: python3 3.12 or newer is required" >&2
  exit 1
fi
export PYTHONDONTWRITEBYTECODE=1
exec python3 - "$root" "$mode" <<'PY'
import hashlib
import json
import os
import shutil
import stat
import subprocess
import sys
import tarfile
import tempfile
import urllib.request
from pathlib import Path

root, mode = Path(sys.argv[1]), sys.argv[2]
MAX_ARCHIVE = 64 * 1024 * 1024
MAX_MANIFEST = 1024 * 1024
AGENTS = ("claude", "codex", "copilot")


def log(message):
    print(f"hard-eng bootstrap: {message}", file=sys.stderr, flush=True)


def fail(message):
    log(message)
    raise SystemExit(1)


if mode not in (*AGENTS, "download"):
    fail(f"unknown mode: {mode}")
try:
    policy = json.loads((root / "hard-eng.gates.json").read_text(encoding="utf-8"))["hard_eng"]
    pin = policy["pin"]
    tag, archive_sha, manifest_sha = pin["tag"], pin["archive_sha256"], pin["manifest_sha256"]
except (OSError, ValueError, KeyError, TypeError) as error:
    fail(f"hard-eng.gates.json has no usable Hard Eng pin: {error}")
release_repository = policy.get("release_repository", "sgaabdu4/hard-eng")
base = os.environ.get("HARD_ENG_RELEASE_BASE_URL") or f"https://github.com/{release_repository}/releases/download"
local = root / ".agents" / "hard-eng"
target = local / "releases" / tag


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def fetch(name, destination, expected, limit):
    url = f"{base}/{tag}/{name}"
    try:
        with urllib.request.urlopen(url, timeout=120) as response, destination.open("wb") as handle:
            copied = 0
            while block := response.read(1024 * 1024):
                copied += len(block)
                if copied > limit:
                    fail(f"{name} is larger than the {limit} byte limit")
                handle.write(block)
    except OSError as error:
        fail(f"could not download {url}: {error}")
    if sha256(destination) != expected:
        fail(f"{name} does not match the digest pinned in hard-eng.gates.json")


def tree_digest(base_dir):
    digest = hashlib.sha256()
    for path in sorted(base_dir.rglob("*"), key=lambda value: value.relative_to(base_dir).as_posix()):
        relative = path.relative_to(base_dir).as_posix()
        metadata = path.lstat()
        kind = b"directory" if stat.S_ISDIR(metadata.st_mode) else b"file"
        digest.update(kind + b"\0" + relative.encode() + b"\0")
        digest.update(f"{stat.S_IMODE(metadata.st_mode):04o}".encode() + b"\0")
        if kind == b"file":
            digest.update(str(metadata.st_size).encode() + b"\0")
            with path.open("rb") as handle:
                for block in iter(lambda: handle.read(1024 * 1024), b""):
                    digest.update(block)
    return digest.hexdigest()


def write_json(path, value):
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        handle.write(json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n")
    os.chmod(temporary, 0o600)
    os.replace(temporary, path)


def cached():
    try:
        state = json.loads((local / "last-check.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return False
    if not isinstance(state, dict) or state.get("pin") != pin or not (local / "current").is_symlink():
        return False
    return (target / ".hard-eng-release.json").is_file() and tree_digest(target) == state.get("payload_digest")


def extract(archive, stage):
    prefix = f"hard-eng-{tag}/"
    with tarfile.open(archive, "r:gz") as bundle:
        members = []
        for member in bundle.getmembers():
            if member.name == prefix.rstrip("/"):
                continue
            if not member.name.startswith(prefix) or not (member.isdir() or member.isfile()):
                fail(f"unexpected release archive entry: {member.name}")
            member.name = member.name[len(prefix) :]
            members.append(member)
        bundle.extractall(stage, members=members, filter="data")


def remove_path(path, *, ignore_errors=False):
    if path.is_symlink() or path.is_file():
        try:
            path.unlink()
        except OSError:
            if not ignore_errors:
                raise
    elif path.is_dir():
        shutil.rmtree(path, ignore_errors=ignore_errors)


def download():
    with tempfile.TemporaryDirectory(prefix="hard-eng-bootstrap-") as temporary:
        archive = Path(temporary) / f"hard-eng-{tag}.tar.gz"
        manifest_path = Path(temporary) / f"hard-eng-{tag}.manifest.json"
        fetch(archive.name, archive, archive_sha, MAX_ARCHIVE)
        fetch(manifest_path.name, manifest_path, manifest_sha, MAX_MANIFEST)
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        if not isinstance(manifest, dict) or manifest.get("version") != tag:
            fail("the release manifest does not describe the pinned tag")
        for directory in (local.parent, local, local / "releases"):
            directory.mkdir(mode=0o700, exist_ok=True)
        stage = Path(tempfile.mkdtemp(prefix=".installing-", dir=local / "releases"))
        try:
            extract(archive, stage)
            write_json(stage / ".hard-eng-release.json", manifest)
            remove_path(target)
            os.replace(stage, target)
        finally:
            remove_path(stage, ignore_errors=True)
    link = local / "current"
    temporary_link = local / f".current.{os.getpid()}"
    temporary_link.symlink_to(Path("releases") / tag)
    os.replace(temporary_link, link)
    write_json(
        local / "last-check.json",
        {
            "active_version": tag,
            "channel": policy.get("channel"),
            "last_result": "pinned-verified",
            "marker_digest": None,
            "minimum_version": policy.get("minimum_version"),
            "newest_allowed_version": tag,
            "payload_digest": tree_digest(target),
            "pin": pin,
            "release_repository": release_repository,
            "schema_version": 1,
            "source_commit": manifest.get("source_commit"),
        },
    )
    log(f"downloaded and verified Hard Eng {tag}")


def session(agent):
    first_claude_session = agent == "claude" and not (root / "CLAUDE.local.md").exists()
    environment = {name: value for name, value in os.environ.items() if not name.startswith("GIT_")}
    result = subprocess.run(
        [sys.executable, str(target / "bin" / "hard-eng"), "prepare", "--repo", str(root), "--agent", agent],
        check=False,
        capture_output=True,
        text=True,
        env=environment,
        stdin=subprocess.DEVNULL,
        timeout=600,
    )
    if result.returncode != 0:
        fail(result.stderr.strip() or result.stdout.strip() or "hard-eng prepare failed")
    if first_claude_session:
        rules = (target / "AGENTS.md").read_text(encoding="utf-8")
        output = {"hookEventName": "SessionStart", "additionalContext": rules, "reloadSkills": True}
        print(json.dumps({"hookSpecificOutput": output}))


if not cached():
    download()
if mode != "download":
    session(mode)
PY
"""
SHIM_SCRIPT = r"""#!/usr/bin/env bash
# Generated by Hard Eng. Runs the pinned Hard Eng guard, or denies tool calls until the release is downloaded.
set -u
agent=${1:-}
event=${2:-}
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
cache=$root/.agents/hard-eng
if [ -f "$cache/global-guard" ] && grep -qx -- "$agent" "$cache/global-guard"; then
  exit 0
fi
guard=$cache/current/scripts/hooks/agent-hook.sh
if [ -f "$guard" ]; then
  exec bash "$guard" "$@"
fi
case $event in
  posttooluse|stop) exit 0 ;;
esac
detail=""
bootstrap=$root/.hard-eng/bootstrap.sh
if [ -f "$bootstrap" ]; then
  heal=$(bash "$bootstrap" download 2>&1 >/dev/null)
  printf '%s\n' "$heal" >&2
  if [ -f "$guard" ]; then
    exec bash "$guard" "$@"
  fi
  detail=$(printf '%s\n' "$heal" | tail -n1 | tr -d '\000-\037' | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')
fi
reason="Hard Eng is not downloaded for this repository yet, so this tool call was denied. Run: bash .hard-eng/bootstrap.sh $agent"
[ -n "$detail" ] && reason="$reason ($detail)"
if [ "$agent" = copilot ]; then
  printf '{"permissionDecision":"deny","permissionDecisionReason":"%s"}' "$reason"
else
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}' "$reason"
fi
"""


def replace_file(path: Path, raw: bytes, mode: int) -> None:
    if path.is_symlink() or (path.exists() and not path.is_file()):
        raise ConfigurationError(f"refusing to replace unsafe path: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    descriptor = os.open(temporary, os.O_CREAT | os.O_EXCL | os.O_WRONLY, mode)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(raw)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        os.chmod(path, mode)
    except BaseException:
        if temporary.is_file() and not temporary.is_symlink():
            temporary.unlink()
        raise


def write_policy(root: Path, policy: MarkerPolicy) -> None:
    """Record or clear the shared pin in hard-eng.gates.json, keeping every other key."""
    marker = root / "hard-eng.gates.json"
    try:
        value = json.loads(marker.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise ConfigurationError(f"hard-eng.gates.json could not be read: {error}") from error
    if not isinstance(value, dict) or not isinstance(value.get("hard_eng"), dict):
        raise ConfigurationError("hard-eng.gates.json has no hard_eng policy object")
    hard_eng = dict(value["hard_eng"])
    hard_eng.pop("wiring", None)
    hard_eng.pop("pin", None)
    if policy.shared:
        if policy.pin is None:
            raise ConfigurationError("shared wiring needs a release pin")
        hard_eng["wiring"] = "shared"
        hard_eng["pin"] = policy.pin.json_value()
    value["hard_eng"] = hard_eng
    replace_file(marker, render(value, style_for(marker)).encode(), stat.S_IMODE(marker.stat().st_mode))


def pinned_cache(local_root: Path, pin: ReleasePin) -> ActiveRelease | None:
    """The verified copy of the pinned release under .agents/hard-eng, or None when it must be fetched."""
    if not (local_root / "current").is_symlink():
        return None
    current = read_current(local_root)
    state_path = local_root / "last-check.json"
    if current is None or state_path.is_symlink() or not state_path.is_file():
        return None
    try:
        state = json.loads(state_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        return None
    if not isinstance(state, dict) or state.get("schema_version") != STATE_SCHEMA:
        return None
    if state.get("pin") != pin.json_value():
        return None
    version, commit = payload_health(current)
    digest = state.get("payload_digest")
    if version != pin.tag or not isinstance(digest, str) or tree_digest(current) != digest:
        return None
    return ActiveRelease(current, version, commit, version, "pinned-verified")


def _run_bootstrap(root: Path) -> None:
    bootstrap = root / BOOTSTRAP
    if bootstrap.is_symlink() or not bootstrap.is_file():
        raise ConfigurationError(f"{BOOTSTRAP} is missing; rerun `hard-eng prepare --shared` where it was created")
    environment = {name: value for name, value in os.environ.items() if not name.startswith("GIT_")}
    try:
        result = subprocess.run(
            ["bash", str(bootstrap), "download"],
            check=False,
            cwd=root,
            env=environment,
            capture_output=True,
            text=True,
            stdin=subprocess.DEVNULL,
            timeout=BOOTSTRAP_TIMEOUT_SECONDS,
        )
    except (OSError, subprocess.SubprocessError) as error:
        raise ReleaseError(f"the Hard Eng bootstrap could not run: {error}") from error
    if result.returncode != 0:
        detail = (result.stderr.strip() or result.stdout.strip() or "no output").splitlines()[-1]
        raise ReleaseError(f"the pinned Hard Eng release could not be downloaded: {detail}")


def ensure_pinned_release(root: Path, policy: MarkerPolicy, *, agent: str) -> ActiveRelease:
    """Return the verified pinned release for this checkout, fetching it with the committed bootstrap if needed."""
    if policy.pin is None:
        raise ConfigurationError("hard_eng.pin is missing")
    local_root = root / ".agents/hard-eng"
    with activation_lock(local_root):
        require_runtime()
        cached = pinned_cache(local_root, policy.pin)
        if cached is not None:
            return cached
        _run_bootstrap(root)
        cached = pinned_cache(local_root, policy.pin)
        if cached is None:
            raise ReleaseError("the downloaded Hard Eng release does not match the committed pin")
        validate_manifest_for(cached, agent)
        return cached


def validate_manifest_for(active: ActiveRelease, agent: str) -> None:
    manifest_path = active.root / ".hard-eng-release.json"
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise ReleaseError("installed release identity is invalid") from error
    agents = manifest.get("compatibility", {}).get("agents") if isinstance(manifest, dict) else None
    if not isinstance(agents, list) or agent not in agents:
        raise ReleaseError(f"the pinned release does not support {agent}")


def pin_release(root: Path, policy: MarkerPolicy, marker_digest: str) -> tuple[ActiveRelease, ReleasePin]:
    """Select the newest allowed release with gh, verify it for every agent, activate it, and return its pin."""
    local_root = root / ".agents/hard-eng"
    with activation_lock(local_root):
        require_runtime()
        candidate = select_release(policy)
        with tempfile.TemporaryDirectory(prefix="hard-eng-release-") as temporary:
            archive, manifest_path, manifest = download_release(candidate, policy.release_repository, Path(temporary))
            for name in SUPPORTED_AGENTS:
                validate_manifest(candidate, archive, manifest, agent=name)
            pin = ReleasePin(candidate.tag, file_sha(archive), file_sha(manifest_path))
            active = activate(
                local_root, candidate, archive, manifest, policy, marker_digest, extra={"pin": pin.json_value()}
            )
    return active, pin


def global_guard_agents(root: Path) -> set[str]:
    path = root / GLOBAL_GUARD
    if path.is_symlink() or not path.is_file():
        return set()
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeError):
        return set()
    return {line.strip() for line in lines if line.strip() in SUPPORTED_AGENTS}


def set_global_guard(root: Path, agent: str, deferring: bool) -> None:
    """Record whether the shim should stand aside for this agent because the global guard already runs."""
    agents = global_guard_agents(root)
    updated = agents | {agent} if deferring else agents - {agent}
    path = root / GLOBAL_GUARD
    if updated == agents and (path.is_file() or not updated):
        return
    if not updated:
        if path.is_file() and not path.is_symlink():
            path.unlink()
        return
    replace_file(path, "".join(f"{name}\n" for name in sorted(updated)).encode(), 0o600)
