"""Keep a project's own pre-push hook running ahead of Hard Eng's."""

import os
import shutil
import subprocess
from pathlib import Path

PYTHON_LAUNCHER = """#!/usr/bin/env python3
import subprocess
import sys

root = subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip()
sys.exit(subprocess.call([sys.executable, root + "/.hooks/hard-eng.py", "pre-push"]))
"""
SHELL_LAUNCHER = '#!/usr/bin/env sh\nexec python3 "$(git rev-parse --show-toplevel)/.hooks/hard-eng.py" pre-push\n'
CHAINED_LAUNCHER = """#!/usr/bin/env sh
original="$0.project"
input=$(mktemp) || exit 1
trap 'rm -f "$input"' EXIT
cat > "$input"
if [ -x "$original" ]; then
  "$original" "$@" < "$input" || exit $?
fi
python3 "$(git rev-parse --show-toplevel)/.hooks/hard-eng.py" pre-push < "$input"
"""
HUSKY_CHAINED_LAUNCHER = CHAINED_LAUNCHER.replace(
    'if [ -x "$original" ]; then\n  "$original" "$@"',
    'if [ -f "$original" ]; then\n  sh -e "$original" "$@"',
)
MANAGER_MARKERS = {
    "lefthook": "LEFTHOOK",
    "pre-commit": "File generated by pre-commit",
    "husky": "husky.sh",
}
LAUNCHERS = {
    PYTHON_LAUNCHER,
    SHELL_LAUNCHER,
    CHAINED_LAUNCHER,
    HUSKY_CHAINED_LAUNCHER,
}
KEPT = "Kept your existing pre-push hook; it runs before Hard Eng's checks. Compare its checks with Hard Eng's (he references: adopting existing checks)."
RESTORE = "Hard Eng's pre-push hook is missing or was replaced (another tool may have reinstalled its own), so pushes are not checked. Rerun setup to restore it: curl -fsSL https://raw.githubusercontent.com/sgaabdu4/hard-eng/main/setup.sh | sh"


def locate(root: Path) -> tuple[Path, Path]:
    from agent_hooks import project_pre_push

    hook = Path(
        subprocess.check_output(
            ["git", "rev-parse", "--git-path", "hooks/pre-push"], cwd=root, text=True
        ).strip()
    )
    hook = hook if hook.is_absolute() else root / hook
    return hook, project_pre_push(root, hook)


def project_copy(hook: Path) -> Path:
    return hook.with_name(hook.name + ".project")


def is_own(root: Path, hook: Path) -> bool:
    if hook.is_symlink():
        return hook.resolve() == root / ".hooks/hard-eng.py"
    return hook.is_file() and hook.read_text(errors="replace") in LAUNCHERS


def foreign_hook(root: Path, hook: Path) -> bool:
    return (hook.exists() or hook.is_symlink()) and not is_own(root, hook)


def kept_copy_matches(hook: Path) -> bool:
    copy = project_copy(hook)
    return copy.exists() and copy.read_bytes() == hook.read_bytes()


def manager(path: Path) -> str | None:
    text = path.read_text(errors="replace")
    return next((name for name, mark in MANAGER_MARKERS.items() if mark in text), None)


def reinstalled(hook: Path) -> bool:
    """The hook manager that wrote the kept copy wrote the new hook too, so the new one is newer."""
    kept = manager(project_copy(hook))
    return kept is not None and kept == manager(hook)


def check_free(root: Path, hook: Path) -> None:
    copy = project_copy(hook)
    if (
        foreign_hook(root, hook)
        and copy.exists()
        and not kept_copy_matches(hook)
        and not reinstalled(hook)
    ):
        raise ValueError(
            f"{hook.name} was replaced while {copy.name} holds another project hook; merge them into {copy.name} and rerun setup"
        )


def preserve(root: Path, hook: Path) -> bool:
    check_free(root, hook)
    if not foreign_hook(root, hook):
        return False
    if not kept_copy_matches(hook):
        shutil.copy2(hook, project_copy(hook))
    return True


def restore_note(root: Path) -> str:
    from update import SOURCE_FILE

    if not (root / SOURCE_FILE).exists():
        return ""
    try:
        target = locate(root)[1]
    except (OSError, ValueError, subprocess.SubprocessError):
        return ""
    return "" if is_own(root, target) else RESTORE


def use_own_hooks(root: Path, candidate: Path) -> None:
    """Make a hooks path `git worktree add` copied from `root` name the candidate's own files."""
    where = [
        "--path-format=absolute",
        "--git-path",
        "config.worktree",
        "--git-common-dir",
    ]
    config, common = subprocess.check_output(
        ["git", "rev-parse", *where], cwd=candidate, text=True
    ).splitlines()
    setting = ["git", "config", "--file", config]
    found = subprocess.run(
        [*setting, "core.hooksPath"],
        cwd=candidate,
        capture_output=True,
        text=True,
        check=False,
    ).stdout.strip()
    path = Path(found).expanduser()
    if (
        not found
        or not path.is_absolute()
        or path.resolve().is_relative_to(Path(common).resolve())
    ):
        return
    checkouts = [root, Path(common).parent] if Path(common).name == ".git" else [root]
    for checkout in checkouts:
        if path.resolve().is_relative_to(checkout.resolve()):
            own = path.resolve().relative_to(checkout.resolve()).as_posix()
            replace = [*setting, "--replace-all", "core.hooksPath", own]
            subprocess.run(replace, cwd=candidate, check=True)
            return


def planned_hook(root: Path, plan: object) -> tuple[str, str]:
    if not isinstance(plan, dict):
        raise TypeError("Setup plan must be an object")
    hook = plan.get("hook")
    if not isinstance(hook, dict):
        raise TypeError("Setup plan is missing the pre-push hook")
    hook_path, hook_content = hook.get("path"), hook.get("content")
    if not isinstance(hook_path, str) or not isinstance(hook_content, str):
        raise TypeError("Setup plan has an invalid pre-push hook")
    if hook_path == ".husky/pre-push":
        if (root / hook_path).is_symlink():
            raise ValueError("Preserve the existing hook symlink before updating")
        if foreign_hook(root, root / hook_path) and not (
            project_copy(root / hook_path).exists()
        ):
            raise ValueError(
                "Existing pre-push hook must be preserved; run the setup command to keep it"
            )
        files = plan.get("files")
        if not isinstance(files, dict):
            raise TypeError("Setup plan must include file changes")
        files[hook_path] = hook_content
    return hook_path, hook_content


def own_hooks_env(root: Path) -> dict[str, str] | None:
    """CI never runs the pre-push hook, so a runner's hooks folder outside the checkout must not fail the check."""
    try:
        locate(root)
    except ValueError:
        common = subprocess.check_output(
            ["git", "rev-parse", "--path-format=absolute", "--git-common-dir"],
            cwd=root,
            text=True,
        ).strip()
        env = dict(os.environ)
        count = int(env.get("GIT_CONFIG_COUNT", "0"))
        return env | {
            "GIT_CONFIG_COUNT": str(count + 1),
            f"GIT_CONFIG_KEY_{count}": "core.hooksPath",
            f"GIT_CONFIG_VALUE_{count}": str(Path(common) / "hooks"),
        }
    return None
