#!/usr/bin/env python3
"""Single owner for prose-anchor doc contracts; wording assertions live only here."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

ANCHORS: dict[str, tuple[str, ...]] = {
    "AGENTS.md": (
        "| Direct | bounded clear outcome",
        "lean Feature Brief → one Ready-to-build approval",
        "Feature alignment = `question-me` until aligned",
        "arbitrary question limit = none",
        "delivery form/lifetime when it changes observable operation",
        "Terminal PLAN cleanup = prove terminal state + exact path/hash",
        "active/nonterminal PLAN deletion forbidden",
        "Terminal lifecycle status noise = exact terminal slug PLAN + receipts",
        "Terminal handoff + unrelated request = recommend fresh task",
        "Shared session/preferences/account CLI = sequential",
        "Multi-repo shell probe = selected-repo cwd OR absolute repo-root paths",
        "Commentary = material state change + blocker + approval boundary + proof",
        "Critical overlay = slice-scoped; safe slices keep standard flow.",
        "bug + flake + failure + regression",
        "root cause + blast radius",
        "regression proof green",
        "product outcome + UX behavior + default/policy + security/privacy + data loss + irreversible choice",
        "Accepted outcome or material risk contract change",
        "show exact delta → confirm",
        "Replan = accepted outcome change OR material risk contract change",
        "File/owner/caller/schema/key/test/route discovery with unchanged outcome/risk",
        "reapproval forbidden",
        "unchanged outcome/risk continues automatically",
        "Commit changing product truth =",
        "unchanged product truth = no read",
        "Process learning =",
        "block only when continued work risks protected boundary",
        "Subagents = current user prompt explicitly requests",
        "one depth-1 `he-learn` helper after a verified repository trigger",
        "deterministic prevention first",
        "Review = actual diff + affected behavior + risk-targeted proof",
        "Tests/QA/TDD → `test-quality`",
        "real UI proof → `e2e`",
        "Security → `security-review`",
        "Implement ⇄ Verify",
        "Gate scope = affected-full",
        "or uncertainty → full repository",
        "Gate concurrency = independent affected owners parallel",
        "Efficiency target = smallest correct maintainable outcome",
        "minimum concepts + files + steps + tokens/context + wall time + paid compute",
        "product-performance claim requires measurement",
        "reuse exact-tree proof/artifact",
        "duplicate equivalent setup/build/gate forbidden",
        "Code comment = none by default",
        "cannot be expressed by deletion + naming + types/API + structure + test + canonical docs",
        "narration + restatement + history + TODO prose forbidden",
        "Output tokens = shortest complete decision/answer",
        "omit prompt restatement + internal process + praise + optional tangents + repeated summary",
        "User-direction ledger = explicit outcome",
        "Pre-implementation check = accepted outcome + actual owner/flow/operations",
        "analysis depth ≠ response length",
        "Collection scope = enumerate candidates",
        "Explicit terminal outcome = persistent completion contract",
        "Bug-fix implementation admission = preserved red-capable reproduction",
        "External/native or paid failure = stop actor",
        "approach fingerprint (mechanism + dependency/tool + mode/target)",
        "Read-only failure/retry = no approval",
        "Planning-first = Feature Loop evidence + lean brief + Ready-to-build approval",
        "Outcome-first = after readiness/approval, complete the thinnest accepted",
        "including `before commit/push`, waits until behavior works",
        "Build-entry exception = failed `write`/setup",
        "other pre-behavior diversion forbidden",
        "Publish execution = verify named target",
        "Release actor = one per target + environment + revision",
        "Release recovery = failed external mutation/paused cutover",
        "same-revision correction retry explicitly forces that mode",
        "terminal readback before closure",
        "correction-only classifier non-entry ≠ completion",
        "Remote PASS = required CI jobs green for the delivered commit",
    ),
    "README.md": (
        "Fix the typo in the account menu.",
        "# Direct",
        "lean Feature Brief",
        "one Ready-to-build approval",
        "Independent questions in one dependency frontier are asked together",
        "Before each dependency frontier, the agent researches the available evidence",
        "There is no arbitrary limit on material questions.",
        "Ready-to-build approval rounds before standard build",
        "Material question cadence",
        "A decision answer is not called an approval",
        "Planning needs a readable selected checkout, not a build-ready toolchain.",
        "smallest safety repair and focused proof needed to unlock the checkout",
        "original reported examples at the boundary where users observed them",
        "remove only the exact terminal PLAN paths the user approves",
        "Unrelated work starts a fresh task after a long delivery",
        "Routine tool narration and unchanged polling are omitted",
        "Critical overlay follows risk",
        "for that slice only",
        "reported failure is rechecked",
        "first complete rung wins",
        "Explicit outcomes, constraints, examples, and corrections stay open",
        "current primary sources plus a bounded analogous-incident search",
        "failed paid/native/external attempt ends that mechanism",
        "Security controls require a concrete asset, plausible threat, and impact",
        "Optimize the work itself",
        "one proof/build per exact candidate and required seam",
        "measure product hot spots before performance changes",
        "Think deeply before implementation",
        "fewest tokens that preserve the requested result, proof, risk, and next action",
        "Source comments default to none",
        "requested terminal artifact survives recoverable CI failures",
        "root cause and blast radius",
        "product outcome or user-visible behavior",
        "security or privacy",
        "data-loss exposure",
        "an irreversible decision",
        "shows the exact delta and asks for confirmation",
        "caller, file, owner, schema, route, test, or configuration",
        "without reopening the brief",
        "Reading and reversible local or external work run automatically",
        "exact request covers the unchanged delivery",
        "Approval is reserved for irreversible destructive loss",
        "Product delivery continues",
        "unless continuing would risk security, privacy, accessibility, data integrity",
        "actual diff, affected behavior, blast radius, and risk-targeted evidence",
        "Deterministic project gates",
        "browser or device evidence",
        "Implement ⇄ Verify",
    ),
    "PRODUCT.md": (
        "one lean Feature Brief",
        "one Ready-to-build approval",
        "approved before build-readiness debt",
        "Implement ⇄ Verify",
        "runs affected-full gates",
        "proves compatible real-tool seams before paid/native retries",
        "repeated failed mechanism after one external/native/paid failure",
        "duplicate equivalent setup/build/gate/paid actor per exact tree + seam",
        "tokens not required for the decision, proof, risk, or next action",
        "new source comments expressible through code, tests, or canonical docs",
        "explicit outcomes/constraints omitted or silently narrowed",
        "shared behavior = agent-agnostic canonical skills",
        "restating them here forbidden",
    ),
    "DESIGN.md": ("risk marker on affected slice only", "Implement ⇄ Verify", "Ready-to-build"),
    "skills/question-me/SKILL.md": (
        "Before every question = refresh",
        "evidence-settled item → record + never ask",
        "Question cadence = one dependency frontier per turn",
        "batch every mutually independent material decision",
        "next frontier branches from accepted answers",
        "Unlimited material questions",
        "Delivery form/lifetime = material only when",
    ),
    "skills/question-me/references/direct.md": (
        "Select next dependency frontier by impact",
        "batch every independent material decision",
    ),
    "skills/question-me/references/feature-brief.md": (
        "Select next `user-decision` dependency frontier by impact",
        "batch independent decisions",
    ),
    "skills/he/SKILL.md": (
        "exact user-authorized terminal PLAN file cleanup",
        "Terminal checkpoint = exact slug PLAN + receipts",
        "lifecycle_status",
        "Ready-to-build",
        "Engineering-only discovery",
        "material security/privacy/data-loss/irreversible contract",
        "planning-only PLAN init/edit",
        "Planning route cannot be preempted",
    ),
    "skills/he-plan/SKILL.md": (
        "[feature-brief.md](references/feature-brief.md)",
        "Unknown implementation owner/file/test",
        "Ready-to-build",
        "Outcome",
        "Non-goals",
        "Material decisions",
        "Acceptance examples",
        "Affected canonical areas",
        "Risk and rollback",
        "First vertical slice",
        "every required persistence/API/backend/UI owner",
        "Build readiness/setup/full gates = build-entry concerns",
        "failed product `write` gate alone does not block `he-plan`",
        "accepted proposed-state design",
        "current screenshot alone is never the approval reference",
        "ImageGen mock OR HTML/CSS wireframe rendered to an image",
        "serve on localhost + open exact preview URL in that browser",
        "User requests visual change → update same preview",
        "superseded visual cannot receive Ready-to-build approval",
        "Path-only, `file://`, or unopened localhost HTML = not delivered",
        "display that exact image in chat before asking for approval",
    ),
    "skills/he-plan/references/feature-brief.md": (
        "exact Ready-to-build challenge",
        "case-sensitive `APPROVE <code>`",
        "Approval fingerprint = frozen content only.",
        "reference media shows the proposed state in chat and is never committed",
        "one smallest sufficient proposed-state visual",
        "localhost preview opened and kept live for user review",
        "one reusable localhost server/tab + matching chat image",
        "User visual feedback = update same preview",
        "superseded visual is invalid",
        "remaining independent read-only brief discovery runs in parallel",
        "no extra model review, serial design stage, or separate design approval round",
    ),
    "skills/he-build/SKILL.md": (
        "one active independently demonstrable vertical slice",
        "actual-diff review",
        "affected proof",
        "relevant E2E/security proof",
        "targeted independent review by every applicable protected-boundary owner",
        "Planning reopens only",
        "Candidate patches + path manifests + patch/hash admission + repeated final LLM audits = forbidden",
        "one successful full pre-ship gate",
        "Learning = record verified `he-learn` trigger + continue",
        "slice-gate receipt on the final tree",
        "Implement ⇄ Verify",
        "Build order = failed `write`/setup",
        "complete accepted persistence/API/backend/UI path",
        "unrelated tooling/reference/receipt debt waits",
        "Working instruction ledger = accepted brief",
        "Before each mutation/resume = reconcile ledger",
        "Every instruction-ledger item = proven",
    ),
    "skills/he-build/references/workflow.md": (
        "reproduce first",
        "canonical owner + every connected caller/schema/key/route/config/test/doc",
        "Review actual diff once",
        "finding-scoped re-review",
        "preserve inspected `completed_slices` exactly",
        "first remaining planned `S-ID`",
        "`building + active_slice=none + completed_slices!=none`",
        "resetting/omitting completed progress = forbidden",
        "one unchanged corrected snapshot with full gate PASS",
        "data-loss/irreversible/schema/recovery",
        "no routine cross-repository source pause",
        "Final Pre-ship Gate",
        "canonical `e2e` receipt PASS",
        "run the slice gate on the final slice tree",
        "slice gate `--full` receipt on the same snapshot",
        "`slice_receipt|full_receipt` debt",
        "required persistence/API/backend/UI = one path",
        "visual acceptance never pauses persistence/API/backend work",
        "keep active behavior on the critical path",
        "reference/screenshot/receipt work never gates unfinished backend/persistence wiring",
    ),
    "skills/he-build/agents/openai.yaml": ("allow_implicit_invocation: true",),
    "skills/he-ship/SKILL.md": (
        "exact green snapshot",
        "Commit/push/PR/merge/publish + named deploy + recoverable live data/schema work",
        "Unrequested irreversible destructive delivery action",
        "`deterministic-checks` `publish` PASS",
        "later local lifecycle-state bytes are not part of that artifact",
        "Force push without exact protected approval + bypassed hook/check",
        "protected-boundary evidence",
        "Explicit terminal delivery outcome persists across recoverable build/CI failures",
        "one failed attempt never narrows the goal",
    ),
    "skills/he-ship/references/workflow.md": (
        "git push --dry-run",
        "After commit hooks complete + before dry-run/push",
        "resolve the target + hooks + automatic workflows + downstream writes",
        "active release actors",
        "`github_delivery.py`",
        "affected-full classifier",
        "record run IDs/URLs + results for the delivered commit",
        "Failure after external mutation",
        "apply global Release recovery",
        "CI ⇄ Build",
        "`he-build` root fix",
        "canonical `e2e` receipt validator PASS",
        "do not amend/create/push another commit",
        "--set lifecycle_status=shipped",
        "assert-green --delivered-head",
        "New deterministic failure/root → new `diagnosing-bugs` + `he-build` loop",
        "Explicit terminal artifact goal remains open",
    ),
    "skills/he-ship/agents/openai.yaml": ("allow_implicit_invocation: true",),
    "skills/he-learn/SKILL.md": (
        "protected boundary",
        "spawn one depth-1 `he-learn` helper only when output says `helper=he-learn`",
        "Global `~/.agents` = learning engine only",
        "Skill fallback = same root proven ≥2",
        "Codex + Copilot read canonical `.agents/skills` directly",
        "`~/.agents/setup.sh repo-check <repo>` PASS",
        "Mechanically detectable prevention = executable rule/tool/fixture",
        "Prevention placement = before the expensive/failure boundary",
    ),
    "skills/diagnosing-bugs/SKILL.md": (
        "Reporter failures + constraints + examples + rejected remedies = immutable diagnosis ledger",
        "Problem admission = observable violation still reproduces",
        "Bug-fix implementation admission = preserved red-capable reproduction",
        "Solution admission = [fix.md](references/fix.md) ladder `PASS` before edit",
        "dependency/native packaging requires unique needed behavior",
        "External/runtime/platform assumption → `research`",
    ),
    "skills/diagnosing-bugs/references/diagnose.md": (
        "Reporter-provided examples = immutable reproduction inventory",
        "interpreter/compiler/runner behavior requires execution at the compatible seam",
    ),
    "skills/diagnosing-bugs/references/fix.md": (
        "Solution ladder = remove → reuse/repair existing owner",
        "stop at first complete rung",
        "Record ladder receipt = considered rungs + selected rung",
        "observed public/package/release boundary",
        "audit adjacent assumptions across syntax, cardinality, quoting, paths, waits, job boundaries, platform, version, and state",
        "compatible real-tool sentinel",
    ),
    "skills/repeated-failure-learning/SKILL.md": (
        "Failed candidate + original violation remains",
        "same theory/variant mutation, retry, push, or publish = forbidden",
        "Comparable candidate fails twice → no third candidate",
    ),
    "skills/research/SKILL.md": (
        "User-supplied source/claim/checklist = minimum coverage ledger",
        "External/runtime/platform-dependent solution selection or implementation",
        "External/runtime/dependency remedy = current primary contract + bounded public analogous-incident/remedy search before edit",
        "peer workaround = discovery, never authority",
        "compatible parser/compiler/runner probe proves local semantics",
    ),
    "skills/research/references/external.md": (
        "Research PASS precedes external/runtime/platform-dependent solution selection or implementation",
        "Official documentation ≠ local execution proof",
    ),
    "skills/test-quality/SKILL.md": ("Interpreter/compiler/runner behavior seam = actual compatible tool execution",),
    "skills/deterministic-checks/SKILL.md": (
        "github_delivery.py",
        "Gate efficiency = one execution per exact tree + actor + required seam",
        "rerun only after tree/environment/mechanism change or invalid receipt",
        "duplicate equivalent setup/build/gate = `FAIL`",
        "Diagnostic/validation-only workflow path",
        "Nested timeout",
        "Structured external-tool result",
        "dedicated output file or machine-only stdout",
        "whole-channel parse",
        "first `{`/`[` inference from human logs forbidden",
        "ANSI/warning/version/update/bracket prefix",
        "trailing non-whitespace = ambiguous → `FAIL`",
        "External CLI with tracked-config write potential",
        "prefer no-write mode or isolated checkout",
        "exclusive single-writer ownership",
        "exact preimage of bytes/mode/index entries+flags/full status",
        "Approved CLI output = preserve + validate",
        "incidental out-of-approved-scope writes only",
        "current state exactly matches captured CLI postimage",
        "mismatch/concurrent drift → `FAIL` without overwrite",
        "Remote CI PASS",
        "[Affected-full gates](references/affected-full.md)",
        "proven non-impacted scope may skip",
        "[Slice gate](references/slice-gate.md)",
        "[Retry readiness](references/retry-readiness.md)",
        "Compatible real-tool proof = interpreter/compiler/runner behavior",
        "Paid/native retry = [Retry readiness](references/retry-readiness.md) PASS first",
    ),
    "skills/deterministic-checks/references/retry-readiness.md": (
        "Run cheapest compatible real-tool parse/compile/execute sentinel",
        "Parallelize independent cheap checks",
        "Failure ends actor + any protected state-changing/paid retry authorization",
        "approach fingerprint = mechanism + dependency/tool + mode/target",
        "Further protected state-changing external/native OR paid attempt = fresh explicit user approval",
        "Read-only failure = choose a changed safe mechanism + retry automatically",
        "read-only access/retry = no approval",
        "continuity or prior approval cannot substitute",
        "Static/grep/substring/AST intent check ≠ interpreter/compiler/runner semantic proof",
    ),
    "skills/security-review/SKILL.md": (
        "Control admission = concrete asset + plausible threat actor/path",
        "simplest sufficient maintainable control",
        "preference/speculative hardening stays out of required scope",
        "Risk response = eliminate / mitigate / transfer / accept",
    ),
    "skills/security-review/references/broad.md": (
        "Distributable binary/container/archive → preflight source defaults",
        "generated/extracted artifact",
    ),
    "skills/deterministic-checks/references/affected-full.md": (
        "Affected-full = universal gates always + full applicable gate row per impacted owner.",
        "Proof graph = cheapest universal/admission first",
        "every job/step owns one distinct required seam",
        "global/shared/toolchain/CI/classifier change → full repository",
        "external mutation serial via one release actor",
        "Skip = only scope the classifier proved non-impacted.",
    ),
    "skills/deterministic-checks/references/hooks.md": (
        "`pre-push` = affected-full",
        "CI = same classifier + gate commands",
        "Protected CI control signal = unique non-secret marker",
        "downstream exact comparison",
        "GitHub can suppress secret-matching job outputs",
        "one always-run aggregate",
    ),
    "skills/deterministic-checks/references/worktree.md": (
        "Feature Loop planning = selected checkout `read` PASS",
        "Build-entry `write` failure = `repair` only the blocked setup/readiness owner",
        "Planning-only PLAN init/edit = `read` PASS exception",
    ),
    "skills/building-flutter-apps/SKILL.md": (
        "Global `deterministic-checks` `dart_decimate_gate.py` exits 0 after one full zero-finding scan",
        "changed/base/baseline/audit modes + inherited exceptions + raw scanner calls are forbidden",
        "once per affected Git root",
    ),
    "skills/building-flutter-apps/references/dart-decimate.md": (
        'Every project → `python3 "$HOME/.agents/skills/deterministic-checks/scripts/dart_decimate_gate.py"',
        "per-package full-repository rescans forbidden",
        "Changed/base/baseline/audit modes + inherited finding exceptions = forbidden",
    ),
}

FORBIDDEN: dict[str, tuple[str, ...]] = {
    "skills/he-build/references/workflow.md": ("--set completed_slices=none",),
    "skills/building-flutter-apps/SKILL.md": ("new-only audit", "changed-code audit"),
    "skills/building-flutter-apps/references/dart-decimate.md": ("dart-decimate@latest audit", "--gate new-only"),
}


def main() -> int:
    findings: list[str] = []
    for relative in sorted(set(ANCHORS) | set(FORBIDDEN)):
        path = ROOT / relative
        if not path.is_file():
            findings.append(f"missing owner: {relative}")
            continue
        text = path.read_text(encoding="utf-8")
        findings.extend(f"{relative}: missing {anchor!r}" for anchor in ANCHORS.get(relative, ()) if anchor not in text)
        findings.extend(f"{relative}: forbidden {term!r}" for term in FORBIDDEN.get(relative, ()) if term in text)
    if findings:
        raise SystemExit("doc-contracts: FAIL | " + " | ".join(findings))
    print(f"doc-contracts: PASS ({len(ANCHORS)} owners)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
