#!/usr/bin/env python3
"""Behavior checks for generated repository and README inventory."""

from __future__ import annotations

import importlib.util
import json
import tempfile
from pathlib import Path
from typing import Any, NoReturn

ROOT = Path(__file__).resolve().parents[1]
OWNER = ROOT / "scripts/repository-manifest.py"


def fail(message: str) -> NoReturn:
    raise SystemExit(f"repository-manifest-regressions: {message}")


def load() -> Any:
    specification = importlib.util.spec_from_file_location("repository_manifest", OWNER)
    if specification is None or specification.loader is None:
        fail("manifest owner could not be loaded")
    module = importlib.util.module_from_spec(specification)
    specification.loader.exec_module(module)
    return module


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def fixture(root: Path) -> None:
    write(root / ".skill-lock.json", '{"skills":{"managed-skill":{}}}\n')
    write(root / "skills/managed-skill/SKILL.md", "managed\n")
    write(root / "skills/local-skill/SKILL.md", "local\n")
    write(root / "scripts/setup/manifest.json", '{"requirements":{"node_min":"26.0.0"}}\n')
    write(root / "package.json", '{"engines":{"node":">=26.0.0"}}\n')
    write(root / "setup.sh", "install_tools() {\n  need git\n  need node\n  need codex\n}\n")
    for owner in ("PRODUCT.md", "DESIGN.md", "hard-eng.gates.json"):
        write(root / owner, "owner\n")


def main() -> int:
    module = load()
    module.check(ROOT)
    with tempfile.TemporaryDirectory(prefix="repository-manifest-") as temporary:
        root = Path(temporary)
        fixture(root)
        value = module.build_manifest(root)
        if value["skills"] != {
            "count": 2,
            "local": ["local-skill"],
            "managed": ["managed-skill"],
            "names": ["local-skill", "managed-skill"],
        }:
            fail("fixture ownership or count was wrong")
        readme = """| `skills/` | 2 focused skills for users |
## Skills
| Skill | What it helps with |
| --- | --- |
| `local-skill` | Local |
| `managed-skill` | Managed |
## Requirements
Node.js 26.0+, Codex is required; Claude Code and Copilot CLI are supported when installed.
npx -y github:sgaabdu4/hard-eng --global
npx -y github:sgaabdu4/hard-eng --repo
npx -y github:sgaabdu4/hard-eng --repo --ignore
"""
        if module.readme_errors(value, readme):
            fail("valid README inventory was rejected")
        for wrong in (
            readme.replace("2 focused", "3 focused"),
            readme.replace("| `local-skill` | Local |\n", ""),
            readme.replace("Node.js 26.0+", "Node.js 22.5+"),
            readme.replace("Codex is required", "Codex is optional"),
            readme.replace(" --global", " --computer"),
            readme.replace(" --repo --ignore", " --repo --private"),
        ):
            if not module.readme_errors(value, wrong):
                fail("README drift mutation was accepted")
        write(root / "repository.manifest.json", json.dumps(value) + "\n")
        write(root / "README.md", readme)
        module.check(root)
        generated = root / "generated.json"
        module.atomic_write(generated, b'{"ok":true}\n')
        if generated.read_bytes() != b'{"ok":true}\n':
            fail("atomic writer changed generated bytes")
        outside = root / "outside.json"
        outside.write_text("preserved\n", encoding="utf-8")
        generated.unlink()
        generated.symlink_to(outside)
        try:
            module.atomic_write(generated, b"forged\n")
        except module.ManifestError:
            pass
        else:
            fail("atomic writer accepted a symlink target")
        if outside.read_text(encoding="utf-8") != "preserved\n":
            fail("atomic writer changed a symlink target")
    print("repository-manifest-regressions: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
